### ISSUE TITLE
Rework Vodyani Lategame Ecology Laws

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#10]

**Comment by wakystuf** [comment]
It looked to me like the Vodyani late-game laws were the same X% bonus (usually 3%) per pop type? Were these reverted in a later update?

**Comment by wakystuf** [comment]
From testing in-game and then reviewing the code, I don't think this one ever happened (or if so then it was reverted in a later update). Maybe something to consider for 1.3.1 or later.

**Comment by captaincobbs** [comment]
I don't think it happened then, we haven't changed laws in this update

**Comment by wakystuf** [comment]
Sounds good. I've removed from the wiki

**Comment by wakystuf** [comment]
Now that I'm going back through the old issues to make sure I got everything, I'm going to add the Rejected tag to this one so that I don't accidentally document it
