### ISSUE TITLE
Redo academy diplomatic relation states

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#102]

**Comment by wakystuf** [comment]
I saw the code that listed the options in DiplomaticRelationStates[Academy].xml, but it wasn't immediately clear which ones were different vs vanilla since I don't have the expansion. Is that something to easily clarify?

**Comment by wakystuf** [comment]
OK, I think I figured this one out, but probably not a bad idea for someone else to check it at some point to make sure I got it right. I basically just used string comparison between the modded and vanilla code, but I don't actually know much of anything about Awakening
