### ISSUE TITLE
Remove the militarist support quest from the minor assimilation pool.

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1072]
Militarist factions are unlikely to get this since they'll skip diplomacy and it's a real pain if you're an anti militarist faction.

**Comment by NoProblemWithThisAcc** [comment]
Agreed. If we can't make as many support quests as we want, the spot should be reused into something else (like a pacifism version).

**Comment by captaincobbs** [comment]
There are already very few quests left in the minor faction quest pool, I don't think this is a good idea even if it's popular.

**Comment by Tat011** [comment]
Can't more be added then? they don't even have to be completely new just different versions of existing quests, like versions for the other fidsi for that one quest where you have to make X science before Y turns.

**Comment by captaincobbs** [comment]
The problem isn't that quests run out, the problem is that you'll be doing the same 3 quests over and over again at this point, because I believe we've removed a lot.

Since we've removed a lot, however, that means you could probably pretty easily make entirely new quests with different lore and objectives using the same images.

**Comment by NoProblemWithThisAcc** [comment]
I agree that adding more quests is good (and might help avoid that bug preventing you from getting an assimilation quest at all). The wiki doesn't have a nice list I can look up but for starters: a pacifism support quest, an industrialist support quest, and a scientific support quest seem doable for most every race.

**Comment by captaincobbs** [comment]
We've already fixed the bug with not getting an assimilation quest by allowing quests to be assigned multiple times, but each quest cannot be active multiple times simultaneously, so we need to ensure a minimum number of quests are available.

**Comment by wakystuf** [comment]
This has been replaced with "build 4 defense buildings"
