### ISSUE TITLE
Add Cushion of flat 50 to science rollover

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1073]
For early curio triggers

**Comment by captaincobbs** [comment]
Is it possible to add a flat cushion? I thought it was a multiplier.

**Comment by wakystuf** [comment]
Yeah that's a good question. I am not sure, but might be able to figure it out with math shenanigans

**Comment by NoProblemWithThisAcc** [comment]
Even if we crank the multiplier up, it seems to be always inefficient to not just spend your science as you get it anyway (opportunity costs). The only time I've ever "used" the bank was when I got screwed by the turn timer.

Even aside from early curios, if we had a crazy x99 cap or something, I don't see any problems.

**Comment by Arpharnator** [comment]
this is for early curio triggers
also
scrapping

also for the better player the bank is an extra way to acquire flexibility

**Comment by captaincobbs** [comment]
This was implemented correct?

**Comment by wakystuf** [comment]
Yep
