### ISSUE TITLE
UC and Vodyani can't undeplete but suffer depletion penalties.

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1085]
i think for this you should just make uc not suffer from depletion and to give the undepletion behemoth module to vodyani.

**Comment by wakystuf** [comment]
Petition (mostly) accepted. I made a new version of the module for the Vodyani that does not enable terraforming (IE, it's is strictly worse than what everybody else gets)

Note that the UC can already use the terraform/anti-depletion module
