### ISSUE TITLE
Balance the academy roles

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1088]
the academy roles as is are grossly unbalanced.
Spear one, best one unless youre not attacking anything purely because its the only one that isn't niche
law one, not that bad but it seems mostly only useful to dictatorships since federation/republic can get 2 parties they want if they play smart and democracy gets 3 so its unlikely you wont get what you want.
Question one, awful. you get to ask questions to isyander with most of them being irrelevant, the few useful ones dont even take uc into account either (you gotta pay for the answers too).
Dust one, you get 30 dust you cant even spend yourself and have to give to someone else.
How to balance in my opinion: Make the law one decrease law upkeep cost and increase the ammount of active laws you can have by 1
make the question one have more information to give and make the info free to access, make it do more too like maybe you can see what another player sees with it or you can remove fog of war, anything really.
make the dust one actually let isyander loan you dust like the description says with little to no interest (you already paid to acces this) and make you less vulnerable to inflation.

**Comment by captaincobbs** [comment]
I guarantee no one will volunteer to do this, so unless you have a solid plan I don't think this is going to happen.

1. The Spear is not so easy to balance, as it isn't a predetermined fleet that the Spearbearer gets. The Academy gives its most powerful fleet assigned to defense, meaning it scales with both your game speed and your academy difficulty. If the Spear is too strong, then lower your academy difficulty.

2. The Law already gives influence and some law upkeep reduction
3. The Dust one gives a sizeable increase to dust production and makes all mutual diplomacy options free for both parties.
4. The Question one gives you some science bonuses, along with the effect of the T0 science law, plus additional hacking speed. We are physically incapable of adding more questions that don't have a predetermined answer, but making it less vulnerable to inflation would be nice.

**Comment by captaincobbs** [comment]
No update on this in multiple months, closing.
