### ISSUE TITLE
Shield Regen Module Changes

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1090]
Make % Regen ship-only, and make Flat regen flotilla wide

**Comment by FluffiestPrincess** [comment]
I've implemented this but I never did find out why it was necessary in balance terms.

**Comment by NoProblemWithThisAcc** [comment]
Making flat regen flotilla wide does seem good. Not sure about the % regen nerf. Perhaps there was a stacking cheese.
