### ISSUE TITLE
Rework Eusocial Senator skill

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1096]
![image](https://user-images.githubusercontent.com/79942510/157162025-44caadf8-cea7-499b-82fa-661c9aefcf30.png)

Proposal: 0.5 approval and 1 infl per pop

**Comment by captaincobbs** [comment]
Frost's suggestion:
+15 Influence on Empire per Happy System
+30 Influence on Empire per Ecstatic System
(Flat not Dynamic)

**Comment by Provolonage** [comment]
i like the flat kinda maybe 30-50 and keep the approval per pop, since the eusocial hero is so rare i think it could use a really nice senator skill

**Comment by wakystuf** [comment]
Yeah I agree with @Provolonage . Let's implement as Frost suggested, except with larger #s and keeping the approval effect as well.

**Comment by wakystuf** [comment]
One other thing: I'll probably also increase the Primitive senator skill from +1 to +2 industry per pop; currently, it's a capstone and just doesn't compete with what some others get. And probably it will be rare to ever get it anyway given it's a capstone on a minor.

**Comment by wakystuf** [comment]
Implemented, works
![image](https://user-images.githubusercontent.com/79942510/157377509-31e4087e-b40a-4a70-a229-92250586457c.png)

**Comment by Arpharnator** [comment]
Isn't it an issue to have a skill that only works if you're a senator?

**Comment by wakystuf** [comment]
There's a non-senator effect as well that I wasn't messing with; it's +X influence per pop. I just didn't bother to screenshot that part.
