### ISSUE TITLE
Rework Federation Approval bonus

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1097]
Per conversation with @Eighth-of-Third 
Currently it avoids disapproval from out-of-power representatives, but that mechanic doesn't even work properly in some situations. Therefore, to switch to +X approval flat if under the colo cap.

**Comment by Tat011** [comment]
Isnt the appeal of fed to colonize as much as possible? it seems kinda bad for it to have a under the cap happiness buff

**Comment by wakystuf** [comment]
That's certainly one of the appeals, but it should be easily possible to stay under the cap:
* Vaulters are already strongly incentivized to stay under the cap for separate reasons
* UE has a comically huge colo cap that they struggle to even use
* Vodyani colonizes slowly enough that it's usually not that hard to stay under the cap
