### ISSUE TITLE
Curio adjustments

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1101]
* Rearrange battle tactics into later tiers of curios (since most of them are totally worthless at the beginning of the game when they currently become available)
* Slightly taper scaling of rewards to account for ESG's general speeding up of the game such that middle tiers are unlocked earlier (particularly T2-3)
* Reduce the probe regen portion of PROBE DEEP to conform with the other numerical bonuses of the law
* Reorganize loot luxes by tier, so that a) all luxes are evenly distributed, b) tiers match the tiers which reveal luxes, and c) luxes are consistently mapped to the same type of curio for those that are spread across multiple tiers
* Abolish the stupid XP curio that doesn't work properly (IE, provides the scout ship with XP that never matters)

**Comment by NoProblemWithThisAcc** [comment]
If you're messing with "Probe Deep" can you make it called "Probe Deeply" instead? The grammar...

What if probes give less of a movement penalty?

**Comment by captaincobbs** [comment]
Light it's a great law you just don't understand

**Comment by wakystuf** [comment]
Too good, actually; I've gotten some complaints about the regen part being higher than the other parts of it.

Also, Light you already got your present for this month in the form of the market tweaks.
