### ISSUE TITLE
Move Trade to T2 tech (the dust one)

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1108]
Per idea from @Provolonage 
Also make the buildings quite cheap to build

**Comment by Arpharnator** [comment]
I think increasing the dust yields instead might be a better idea
Gonna go test to see how much they provide

**Comment by wakystuf** [comment]
Remember that a) dust yields are the basis for all the other yields and b) they compound exponentially, so it's tricky. That could work, but it's hard to balance properly

**Comment by Arpharnator** [comment]
currently what im seeing is that there is a good chink of dust that is based on the luxes as they provide extra dust to the trade comp

**Comment by Arpharnator** [comment]
I think we do this : 
reduce luxury output by 33%
increase base by 50 (so now 150)
increase growth by 10%

**Comment by Arpharnator** [comment]
the reason for this is that  believe players want dust and not luxury resources especially when the market is now flooding with them.
Furhtermore comparing industry costs of trading comps with their output, there is a pretty big discreptancy. The growth isn't amazing since the nerf we did back then in the revert and the baseline is very bad compared to the costs

**Comment by wakystuf** [comment]
Hmm...those ideas seem mostly reasonable, though I still worry that it may still be optimal to skip the tech if it's in T3.

I would also still make the buildings cheap to build

**Comment by Arpharnator** [comment]
the buildings are ot unaffordable, just not worthwhile currently, so i think giving them the slight boost to base value helps them

**Comment by wakystuf** [comment]
OK, I took a shot at this, mostly how @Arpharnator suggested but with a couple tweaks:
* Lowered lux yields by 33%
* Increased base by 50 
* Cut the indy cost of the buildings to 280 and 560 (on Normal)
* Reduced the base cost of freighters and made them scale a bit less non-linearly

Probably makes sense to playtest that for a bit to make sure it doesn't make anything explode. I don't think it will, but the higher initial base will probably get the exponential growth rolling a bit faster.

**Comment by captaincobbs** [comment]
How come lux yields were reduced? Wasn't the main point of trade the luxuries?

**Comment by wakystuf** [comment]
Yeah, but people have complained that the dust outputs are too poor, so those are now higher, and the lux yields are simply a multiplier of the dust yields. So it'll probably end up only slightly reducing the lux outputs, in exchange for better dust output

**Comment by captaincobbs** [comment]
Ah I see, though I thought we were trying to make trade companies focus on luxuries as to not step on the toes of the dust buildings?

**Comment by NoProblemWithThisAcc** [comment]
I think this is a good edit. Misplaced subsidiaries before you know where all your luxes are means losing out on their potential. The dust/science is easier to plan for and luxes are much easier thanks to the marketplace changes and the AI actually using the marketplace.

**Comment by Arpharnator** [comment]
The trading comps were indeed focused on luxes but there is no point making several hundred a turn, especially now that they can't be converted into money.
After all 90% of the luxes generated by trade are just sold and end up being dust, except that doesn't work anymore.
