### ISSUE TITLE
Bug Report: Eternal War not working again

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1109]
![image](https://user-images.githubusercontent.com/16710532/160201677-a6d3ec96-aa42-4f0d-8062-63a58db57c19.png)

![image](https://user-images.githubusercontent.com/16710532/160201649-180e5986-99f1-4ce7-945d-99e0e59d6193.png)

**Comment by FluffiestPrincess** [comment]
I think I know what's happened here.

`<PathPrerequisite Flags="Prerequisite,FactionTraitEternalWar" Inverted="true">ClassEmpire,FactionTraitEternalWar/ClassSenate/ClassSenator,!Politics03</PathPrerequisite>`

This means "Disable this if there is any senator who is _not_ a pacifist".

The base game's requirement is 

`<PathPrerequisite Flags="Prerequisite,FactionTraitEternalWar" Inverted="true">ClassEmpire,FactionTraitEternalWar/ClassSenate/ClassSenator,Politics06</PathPrerequisite>`

Which means "disable if there is at least one Militarist senator".

**Comment by wakystuf** [comment]
Yeah, agreed. However, 2 notes:
1) Cravers can only have 1 senator at a time, so if there is a non-Pacifist senator then indeed the action should be disabled
2) We can't simply list "require a pacifist senator" as a pre-req, since the condition needs to be an inverted one based off the Eternal War trait

However, there may be a way to set it up more precisely using a meta-prereq for either a) ClassEmpire,!FactionTraitEternalWar or b) ClassEmpire,FactionTraitEternalWar/ClassSenate/ClassSenator,Politics03

**Comment by FluffiestPrincess** [comment]
I can't for the life of me figure out why it's coded as that wonky PathPrerequisite when a MetaPrerequisite or InterpreterPrerequisite would work better. Other EntityActions use InterpreterPrerequisites just fine. Maybe it's a performance thing?

**Comment by captaincobbs** [comment]
Metaprerequisites can't use flags, wouldnt suggest using them

**Comment by wakystuf** [comment]
Yeah so then probably should do an interpreter pre-req, since the path pre-req can't do it without using a meta.

**Comment by FluffiestPrincess** [comment]
If y'all are waiting for me to do this one, that probably isn't happening.

**Comment by wakystuf** [comment]
No problem. As best I can tell, this issue only exists for customs, right? We can just close the issue if so

**Comment by FluffiestPrincess** [comment]
We probably should fix it, eventually, but it's kind of low priority.

**Comment by captaincobbs** [comment]
I look forward to seeing this on the issues list for another year

**Comment by NoProblemWithThisAcc** [comment]
I, uh, think I already have a fix for this? It was one of the last things I did before running out of steam on an ESG-compatible mod. I'll check once I fire all that up again.

**Comment by FluffiestPrincess** [comment]
That would be great.
