### ISSUE TITLE
Change seeker science per anomaly skill

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1113]
Has a pretty bug where the effects apply again for each skill point spent and stay after the hero is unassigned

**Comment by wakystuf** [comment]
There were like 3 different issues with this skill:
* Missing the tag for CSS
* Missing the typing of HeroSkillSystem
* Linking 2 different sim descriptors

All of that has been cleaned up, and now the thing finally works properly
#1126  is the relevant PR
