### ISSUE TITLE
Virtual artifacts don't work

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1119]
![image](https://user-images.githubusercontent.com/49691625/162257823-6ae47e51-aacb-4871-af6b-c43760aba5ca.png)
175 manpower per pop * 55 = 9500
with colony base 10k
2 system developments with virtual artifacts, thus +120% extra at level 4
should get 22k but only get 10k

**Comment by wakystuf** [comment]
I will look into this one. I did recently mod that part, so I may have broken something

**Comment by wakystuf** [comment]
Good find, @Arpharnator. You were right. Just fixed the bug
