### ISSUE TITLE
UC Tweaks

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1135]
* Reinstate prior MP malus
* Instead, switch initial buildings (indy and science) to synergize with home system and apply ESG food building buff to UC version

**Comment by wakystuf** [comment]
#1126 is the PR that will resolve this issue, but I can't link more than 10 issues

**Comment by captaincobbs** [comment]
What exactly was changed?

**Comment by wakystuf** [comment]
* T1 Science and Indy buildings now provide +20 sci/indy per Crescent
* T1 food building is 10 per tag, just like everybody else
* MP malus reverted up to -75%, vs -50%
