### ISSUE TITLE
Vodyani offset for pop collection III setting

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1138]
Complete in #1126  per discussion with @Eighth-of-Third 
The UC got nice buffs to their buildings and the Horatio got lower splice costs. The Vodyani don't get anything as good as that, but their T5 modules might actually be usable now, at a cost of 2 orichalcix/quadrinix per module

Previously had discussed reduced retrofit cost, but that's probably too good so they just get this instead.

Also, a couple of minor QoL changes to reduce turn1 retrofitting:
* The starting scout and hero will be all missiles
* The starting ark will be 1 plating and 1 shield, instead of 2 plating

**Comment by captaincobbs** [comment]
What was changed?

**Comment by wakystuf** [comment]
The T5 strat ark-only modules now have lower costs, reduced from 4 orichalcix/quadrinix each to 2 each.
