### ISSUE TITLE
Add a game option for Jovian Terraforming

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#114]

**Comment by captaincobbs** [comment]
TODO - GUI Elements and Localization

**Comment by Arpharnator** [comment]
is this normal?
![image](https://user-images.githubusercontent.com/49691625/103171723-d13cbe00-484e-11eb-99a0-c765a10ed1b5.png)

**Comment by Arpharnator** [comment]
nevermind, it works, I just don't know which tech is required
![image](https://user-images.githubusercontent.com/49691625/103171776-2547a280-484f-11eb-92a9-4ef69b407042.png)

**Comment by Arpharnator** [comment]
Works with free terraform as well, even tho I can't terraform to gas from desert, same from arctic.

**Comment by captaincobbs** [comment]
It's not Desert or Arctic, it's Swamp.
