### ISSUE TITLE
Replace Dead Vody Questline

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1140]
Replaced the dead questline of reaching Cordial with a minor with instead exploring a certain number of nodes (or % of the galaxy, for tiny maps)

Finished #1126

**Comment by captaincobbs** [comment]
Can you elaborate on what was changed

**Comment by wakystuf** [comment]
Yes, in chapter 1, step 2, the option to "reach Cordial with a minor" was replaced with "explore 10 nodes (or 50% of the galaxy, if that is smaller)"

**Comment by NoProblemWithThisAcc** [comment]
How many other mainline quests require minor pop interactions? I'm curious because I like the idea of the x0 minor empire settings. It's a shame there's only x0 and .5x but not a .25x
