### ISSUE TITLE
Wrong science info in the trading screen

### ISSUE THREAD

**Issue by larssn** [captaincobbs/ESG-Mod#1143]
If your trading company cannot reach a subsidiary, this message is shown:
"This HQ is not able to trace a route to your Subsidiary (research Autonomous Materials to discover wormholes)."

Wrong tech for that, it should have said "Baryonic Shielding".

(This is the 1.6 beta from steam)

**Comment by Arpharnator** [comment]
@captaincobbs is it because of the toggle? I forgot if it existed, and if so, is it possible to have the localisation change accordingly?

**Comment by captaincobbs** [comment]
We can't have the localization change depending on the toggle I don't think, however, we could put like "This HQ is not able to trace a route to your Subsidiary. (Research Autonomous Materials or Baryonic Shielding to discover wormholes, depending on your game settings)."
