### ISSUE TITLE
Add a filter for Nakalim on the End Game screen

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#115]

**Comment by wakystuf** [comment]
Is this a reference to the "Empire Chronicles" page, or something different?

**Comment by captaincobbs** [comment]
I'm going to be honest, I have no idea, I just saw nakalim was missing from a list and added it

**Comment by wakystuf** [comment]
OK. That's what it must be then (unless you separately modded that somewhere else), since toggling the mod on/off makes them appear and disappear from that screen.
