### ISSUE TITLE
Give Vaulters a balanced start trigger

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1151]

**Comment by NoProblemWithThisAcc** [comment]
Make it check for their "Involuntary Nomads" trait, rather than their Portal gameplay affinity, please.

**Comment by captaincobbs** [comment]
It's not going to function for custom factions, too complicated to support that

**Comment by captaincobbs** [comment]
(And just to clarify, none of the balanced starts will work for custom factions, so this isn't unique. If you change the starting population or anything then it'll completely screw it up)
