### ISSUE TITLE
Increase the Variety of T2 luxuries that spawn in each constellation 

### ISSUE THREAD

**Issue by Provolonage** [captaincobbs/ESG-Mod#1171]
Getting 4 deposits of one type or just 1 deposit of 1 type of T2 is dull and incentivizes greeding for T3's

**Comment by wakystuf** [comment]
Increasing overall volume is quite easy, but altering the dispersion is extremely hard. Not literally impossible, but requires the kind of omegahack that I used in my balanced map gen code, which is many thousands of lines long.

Anyway, if nobody yells at me by the time I get around to it (probably in a week or so, but maybe I'll decide to do some on my laptop), then I'll plan to increase overall prevalence of the T2s by ~50%.

**Comment by wakystuf** [comment]
As promised, with no yelling after a week, this is now done
