### ISSUE TITLE
Proposal: nerf Antimatter Lock-on

### ISSUE THREAD

**Issue by FluffiestPrincess** [captaincobbs/ESG-Mod#1173]
> While we're at it, we should nerf Antimatter Lock-on. Stacking it with coordinator-only fleets is extremely strong in a similarly combat-breaking way. Maybe halve the damage boost or make it a unique boost per flotilla, if possible.

_Originally posted by @Eighth-of-Third in https://github.com/wakystuf/ESG-Mod/issues/1170#issuecomment-1120310765_

I'm creating a new issue for this because it'll get ignored entirely if it's only a comment on an otherwise unrelated issue, and I can't find Eighth-of-Third in the Discord to ask them about it.

- Do people think Antimatter Lock-On is a problem by itself?
- Do people think Antimatter Lock-On is a problem when used stacked in coordinator-only fleets?
- What's a good potential nerf, if one is needed?

For reference, Antimatter Lock-on is called `ModuleSupportAntiCarrier1Strategic4` in XML. It adds a 6% damage bonus "per target command point, on flotilla".

**Comment by Mermixer** [comment]
bad take i need something to stop certain creatures from rushing carriers for 0 reason
also bc its the only way to make uc coordinators useful (even though theyre even then 10x times worse than actual coords)

**Comment by NoProblemWithThisAcc** [comment]
I'm all for the unique boost per flotilla, if that means a buff to stop crazy stacking. That way there's still counter play but it doesn't get really bad

**Comment by FluffiestPrincess** [comment]
From discussions in the Discord, it seems the approach most people are happy with is:

1. Set a maximum limit on the stat buffed by Antimatter Lock-On, so that you don't get any benefit from having more than one per flotilla.
2. Increase the damage bonus. 10% would probably be reasonable.
3. Increase the cost accordingly.
4. Update the tooltip to clarify that the effect caps at one per flotilla.

**Comment by wakystuf** [comment]
Yes, I think that sounds like a good summary, though I'd likely buff the damage by more like 50% and double the antimatter cost.

One reminder is that I believe there is also an obscure curiosity module that uses quadrinix in a structurally similar way, so we should mirror the changes for that module

**Comment by Provolonage** [comment]
I'm not sure how you feel about the module but once it goes over 9% per cp its more optimal to have a coord with this module in the same flotilla as two carriers when fighting carriers, then to have a third carrier. Once you have 36 cp you can have two flotillas with one coord with lockon and two carriers, so this module will objectively "solve" late game carrier fleet comps, while being cheaper then building carriers, even if it costs 5 so 10 per coord, including coord extra slots its about 13 orange, which is about as much as a carrier with the orange booster anyway. I would suggest leaving it at 7-8% since mediums and small cannot honestly fight into carriers, which they shouldn't, otherwise this module is kinda op.

**Comment by wakystuf** [comment]
OK, this is done. Can someone please test?

![image](https://user-images.githubusercontent.com/79942510/169936182-95f546f2-385d-4b7b-b989-431cc12f901d.png)
![image](https://user-images.githubusercontent.com/79942510/169936102-3b95cd19-0521-4d65-9231-8b38fda57420.png)

**Comment by FluffiestPrincess** [comment]
Regret to report it's not working. The modules can be built just fine, but they don't seem to be having any effect - in combat, `DamageBonusPerTargetCommandPointsFromLockOnBasic` and all related values remain at 0 on the ship itself.

It's a bit late here, I'll look at the actual code tomorrow and see if I can figure it out.

**Comment by wakystuf** [comment]
OK, thanks for testing. How exactly are you viewing the numbers in combat? I believe in the Simulation viewer I'd expect them to be 0.

**Comment by FluffiestPrincess** [comment]
It's now really late; I'll get back to you tomorrow!

**Comment by FluffiestPrincess** [comment]
Ok, you're right - the Simulation Viewer doesn't display the effects of antimatter lock-on even when used mid-battle in vanilla.

However, I still think there are some errors in what you committed, and I think I know how to fix them. I'll have more time this evening to talk things over with you. Without the ability to view values for ships in combat, though, testing is going to be pretty laborious.

**Comment by FluffiestPrincess** [comment]
I committed some code that should fix it - and also buffs the power of the module to insane levels (+1000% damage) for testing purposes, because we can't see the effect in the simulation viewer.

**Comment by wakystuf** [comment]
I don't think the code seems to work (which is my fault--the changes made by @FluffiestPrincess actually resolved some issues).

Therefore, unless someone else wants to get it to work, how would people feel about making lock-on a) slightly larger #s (again), b) fleet-wide, instead of flotilla-wide, and c) capped to only benefit from 1 per fleet?

**Comment by FluffiestPrincess** [comment]
When you say "doesn't work", do you mean the modules aren't having any effect, or that they're having an effect but it's not capped?

**Comment by wakystuf** [comment]
Seems to have no effect. Feel free to test yourself in case I did something wrong, however

**Comment by wakystuf** [comment]
I'm changing assignees here. @FluffiestPrincess if you get sick of this one, then feel free to let me know and I'll make it fleet-wide (that part I'm confident I can do fairly easily, and is far easier to directly observe in the Simulation viewer)
