### ISSUE TITLE
Make shields scale equally with level as plating does

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#118]

**Comment by wakystuf** [comment]
Is this a reference to the following (IE, making them benefit from the multiplier of  a certain hull size), or something else?

`<Modifier TargetProperty="ShieldBonus"          Operation="Multiplication"      Value="$(Multiplier)"           Path="ClassModuleDefense" />`

**Comment by captaincobbs** [comment]
Nope, that's scaling with module multiplier
