### ISSUE TITLE
Proposal: Include the Better Planet Generation mod into ESG

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1181]
Hello,

This is mostly a request, but I'm wondering if the mods could be merged or at least have the game not generate 2 and 1 planet systems anymore because we all know they're most often than not dead weight and serve no purpose.

The mods are compatible with each other, but sometimes they crash the game when trying to start a game. Having it as an option in world generation would be a nice addition.

Let me know what you think

**Comment by captaincobbs** [comment]
Hello! Thanks for posting.

We have significantly boosted the chances for 3+ planet systems, and lowered the chances for 1 & 2 planet systems already, and the Balanced Galaxy Generation setting that @wakystuf is working on will help ensure that 1 & 2 planet systems don't significantly impact your gameplay, but the chance of us integrating Better Planet Generation isn't likely. There have been concerns that ESG is balancing the fun out of the game, so I've tried to make sure we take care to avoid doing that. Entirely removing systems with low amount of planets is a contentious issue we have talked about at length in the past, and our decision was ultimately that we should leave them alone.

**Comment by wakystuf** [comment]
There are also a bunch of quests that rely on those few-planet systems in order to work properly

**Comment by Arpharnator** [comment]
please enlighten me as to which quests require 1 and 2 planet systems

**Comment by Mermixer** [comment]
i can think of one (1) quest that requires a one planet system, that being the vodyani quest where you need to search a curiosity with lvl 5 hero to get the endless hero
and that is legally regulated u cant change that sry

**Comment by NoProblemWithThisAcc** [comment]
Is there a wiki article with all the prereqs listed somewhere? I'm not pointing fingers, but quests that assume 1-4 or even 5 planet systems don't sound like a good idea, unless there's a technical limitation for this that I'm ignorant of

**Comment by captaincobbs** [comment]
> Is there a wiki article with all the prereqs listed somewhere? I'm not pointing fingers, but quests that assume 1-4 or even 5 planet systems don't sound like a good idea, unless there's a technical limitation for this that I'm ignorant of

It's mostly technical limitations
