### ISSUE TITLE
Inconsistency in ship role icons

### ISSUE THREAD

**Issue by FluffiestPrincess** [captaincobbs/ESG-Mod#1182]
In some places, Coordinator hulls use the "support" icon, and in other places they use "plating". There are other inconsistencies too. I'm planning to fix this so:

- Colonizers always use [colonizer]
- Explorers always use [explorer]
- Attackers always use [attacker]
- Defenders always use [plating]
- Coordinators always use [support]
- Hunters always use [duel]
- Carriers always use [carrier]
- Leechers always use [lifeforce]
- Arks always use [mothership]
- Vine ships always use [unfallen]

**Comment by captaincobbs** [comment]
Looks correct to me

**Comment by wakystuf** [comment]
Agreed. That mapping sounds good

**Comment by FluffiestPrincess** [comment]
Is there a directory of those symbols (like [unfallen]) anywhere?

**Comment by captaincobbs** [comment]
What I use is this:
https://steamcommunity.com/sharedfiles/filedetails/?id=1413567299

Keep two things in mind when using this though, it was made when only the Vaulters DLC was out, and it excludes a lot of the colored versions of icons.
