### ISSUE TITLE
Add new "Enhanced Anomalies" to the XML

### ISSUE THREAD

**Issue by FluffiestPrincess** [captaincobbs/ESG-Mod#1184]
At this preliminary stage they should have effects from [the google doc](https://docs.google.com/document/d/1GsgUxXha4-4wWr_M5FiglITY5gUgCx-4-Q2X2qJ7TQU/edit?usp=sharing), but never spawn naturally. They can have generic flavour text.

_Child of [Anomaly Enhancement](https://github.com/wakystuf/ESG-Mod/issues/872)_

**Comment by Tat011** [comment]
Ok i went through it myself and there is one thing
Why is polar tempest not cold only? i mean as is it can even spawn on lava

**Comment by Tat011** [comment]
Only semi related but i have some anomalies fully coded in (though they're bugged for some reason), if you need/want some or all of them then just ask
They are:
Positive
Tame Fauna (counterpart to hostile fauna), Weak/Strong Magnetic field (the idea is to make strong field a positive anomaly and give it a negative counterpart), Extremophile lifeforms (only spawns on gas and barren/ice/ash/lava), Calm Weather (only for gas), Breathable Atmosphere (only spawns on gas/lava/ash/ice), Crystal lifeforms, Lava reefs (like coral reefs but lava only), Hot Springs, Abandoned Orbital Habitats, Oasis (only for harsh planets), Bioluminescent Life, Cryovolcanoes, Crystal Rain (gas only) 
Mixed
Rich Atmosphere, Montaneous Terrain, Thin Atmosphere (counterpart to rich atmosphere), Endless Defense System
Negative
Faraday Planet (like a Faraday cage but planet sized), Long nights (this is a high rotational tilt messing with the day/night cicle), Mineral poor (counterpart to mineral rich), Hostile Locals (counterpart to friendly locals), Hostile Flora.

**Comment by FluffiestPrincess** [comment]
@Tat011 please create a new Issue for the new anomalies so we can discuss,
accept/reject, and implement it separately.

**Comment by Tat011** [comment]
Err maybe i didnt communicate it properly, i doubt the esg devs are gonna implement new annomalies "just cuz", the idea here is i'm showing you the anomalies i already have and if there are any that would help with this particular project then i can just give you the code.

**Comment by FluffiestPrincess** [comment]
We're good, thanks.

**Comment by FluffiestPrincess** [comment]
Ok, the XML is set up, ready for us to start implementing anomaly enhancement.
