### ISSUE TITLE
Advanced Node Analyzer description incomplete

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1188]
Hello,

The details on the ANA for Behemoth on the research screen is incomplete, it doesn't show the Orichalcix/Quadrinix info and the card is also cramped.

I am using ESG 1.6.

![Screenshot_1](https://user-images.githubusercontent.com/105115857/168334954-5edc15f0-5f09-4bd1-803b-ad9161a3792f.png)

**Comment by captaincobbs** [comment]
Re-hover over the module and it should fix itself. Sometimes the game forgets to fit the text.
