### ISSUE TITLE
Several modules are missing their icon - ESG 1.6

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1189]
I've found three modules that don't have an icon anymore. They're in the screenshots below.
![Screenshot_2](https://user-images.githubusercontent.com/105115857/168340400-8b86a88c-a424-4cc0-9ad7-d9a2dee6a139.png)
![Screenshot_3](https://user-images.githubusercontent.com/105115857/168340403-aaca503d-ee37-4274-ba40-ecf6f6ecaada.png)
![Screenshot_4](https://user-images.githubusercontent.com/105115857/168340405-086edc12-8851-45ca-876b-d31358edbdda.png)
![Screenshot_5](https://user-images.githubusercontent.com/105115857/168340408-d3534f7c-dab5-43db-b92b-c1636e30b1cc.png)

**Comment by captaincobbs** [comment]
Try verifying your game files, all these icons are from vanilla and we do not modify them.
