### ISSUE TITLE
Implement anomaly reduction

### ISSUE THREAD

**Issue by FluffiestPrincess** [captaincobbs/ESG-Mod#1192]
- [x] Set up Waky's magical anomaly reduction so that the existing anomalies can be upgraded according to the google doc
- [x] Work out how to make anomaly enhancement Ecologist-only

_Child of [Anomaly Enhancement](https://github.com/wakystuf/ESG-Mod/issues/872)_

**Comment by wakystuf** [comment]
For step 2 of this, I'd say plan A would be to make the constructible have ecologists as a pre-req. However, plan A (probably?) won't work, so probably instead will need to do one of the following plan B's:
* Run the enhancements through a boolean for ecologist support (IE, it gives like 2 food x pop x [ecologists in power])
* Make the construction cost include a turn based component that's like 999 x (1- [ecologists in power])

**Comment by FluffiestPrincess** [comment]
From the discussions on the pull request, this is probably done, but I'm going to let someone else actually click the close button.
