### ISSUE TITLE
Update effects (and, if necessary, tooltips) for Enhanced Anomalies

### ISSUE THREAD

**Issue by FluffiestPrincess** [captaincobbs/ESG-Mod#1193]
According to [the google doc](https://docs.google.com/document/d/1GsgUxXha4-4wWr_M5FiglITY5gUgCx-4-Q2X2qJ7TQU/edit?usp=sharing)

_Child of [Anomaly Enhancement](https://github.com/wakystuf/ESG-Mod/issues/872)_

**Comment by wakystuf** [comment]
Is this portion still active? I will close if nobody claims it (IE, assigns themself) in a couple of days

**Comment by FluffiestPrincess** [comment]
It is; I can try to do it but no promises.

**Comment by Arpharnator** [comment]
I think provo and I needed to discuss anoms effects

**Comment by Arpharnator** [comment]
well not sure if that's thrown out of the window now, because I don't really believe there was a need to aggravate some anoms effects, and provolonage might feel the same way
