### ISSUE TITLE
Write Lore for Mutual Agreements 1 & 2

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1197]

**Comment by FluffiestPrincess** [comment]
Mutual Agreements 1: Allows you to sign Trade and Science Agreements. Enabled by Commercial Frameworks.

Mutual Agreements 2: Allows you to _force_ Trade and Science Agreements. Enabled by Galactic Security Charter.

**Comment by FluffiestPrincess** [comment]
Done and pushed.
