### ISSUE TITLE
Faction Pact Changes

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1198]
Give Hissho the Vaulter's effect: Garrison Capacity
Replace Vaulters old effect: Strategic Generation

**Comment by captaincobbs** [comment]
@Provolonage any ideas for numbers?

**Comment by Provolonage** [comment]
are we doing percent or flat? for percent 25-50 strat deposit value sounds good if its flat 1-2

**Comment by captaincobbs** [comment]
Probably percent

**Comment by wakystuf** [comment]
25% probably would be fine

**Comment by Tat011** [comment]
I guess ill do this one since no one seems to be interested

**Comment by Tat011** [comment]
were is this stored? i cant find it

**Comment by wakystuf** [comment]
Looks like this one has been sitting for a while. I'll add it to my list

**Comment by wakystuf** [comment]
Complete. Would be very helpful if someone could please test the Vaulter effect
