### ISSUE TITLE
Making Swamp good (and the go to for dust)

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1201]
Honestly idk how to make this happen other than nerfing the dust generation of fertile (cough Adaptative taxation cough)

**Comment by NoProblemWithThisAcc** [comment]
Making it work on sterile instead of fertile as mentioned before sounds like it would work.

**Comment by Tat011** [comment]
i'd be 100% for that but i'm not sure that'd fix the issue as a whole since we're talking about a single late game building

**Comment by wakystuf** [comment]
Probably less disruptive to simply allow the RB to terraform it into either Arctic or Desert. @captaincobbs how hard would that be to set up? Would we simply create new constructibles?
