### ISSUE TITLE
Increased Kei Cap

### ISSUE THREAD

**Issue by NoProblemWithThisAcc** [captaincobbs/ESG-Mod#1204]
We changed the happiness cap to at least show over 100 (and sometimes make use of it), but kei is still capped at 100. Completing 4 quests in one turn and losing 20 kei is frustrating rage-quit material.

I propose the kei cap should be doubled to 200, although just like happiness it won't have any happiness effects about 100. Running the entire game on a knife's edge of 15 kei (85-100) is just not fun.

**Comment by Provolonage** [comment]
This issue with this is kei is a resource, being able to pool kei and then spend it without losing anything is a massive buff and I don't think anyone thinks Hissho needs buffs. If it was just QOL I'd be fine with this but it isn't.

**Comment by NoProblemWithThisAcc** [comment]
Pooling kei from 0-100 (spending 100) in a turn isn't something that happens. In fact it's really really difficult to spend more than a few key in a turn. This isn't like essence where you can supposedly suddenly make a bunch of arks. In fact, if somehow spending a bunch of kei in one turn on anything useful were a thing, then that knife's edge of 85-100 would be a lot easier. But there's just nothing useful to spend it on besides the industry which is only 5 kei (meaning you can effectively manage a 20 kei window rather than 15)

Again, this isn't like essence where you could micro it by using Holy Proliferation in your planet's queue. This way more necessary, and we already did that for vody...

**Comment by Zingybird** [comment]
if i may, hatched at home is one keii per system 3 systems which is the average amount you will have as hissho is 3 per turn and that fine line of devoted to loyal is a small one/ if you increased the cap it would be far to easy to stay at devoted always because you could pool like 200 keii easily and sit on that all game

**Comment by Zingybird** [comment]
like keeping it capped is good, it makes it so you have think about what you spend it on  and if you need to use alot for a fealty centre alos it would be broken if hissho was always at devoted

**Comment by NoProblemWithThisAcc** [comment]
Fealty centers is a good point but that actually proves what I said more: -25 kei means you have to dip outside the 15 or 20 or 23 range mentioned. If you want an actual Hissho buff without changing the kei cap, then fine: change the fealty centers from -25 kei to -15. Then my previous arguments over kei loss wouldn't be valid anymore.

But again, not doing messing with the fealty centers and only removing the stressful balancing act isn't a real buff in my opinion.

**Comment by Provolonage** [comment]
who wants to buff hissho, zingy lost his home system on like turn 20 and 30 turns later he was taking the capital of the guy who took his capital.

**Comment by Zingybird** [comment]
My personal opinion they don't need buffs or anything, if you wanted to you could find a way to spend keii another way like a constructible or something that uses keii for extra food or manpower or some shit but that sounds like a fuck ton of work

**Comment by Arpharnator** [comment]
it's like not possible anyways, and if you compare kei to happiness, happiness was technically uncapped even prior to the rework.
