### ISSUE TITLE
Make a stronger chain gang

### ISSUE THREAD

**Issue by Provolonage** [captaincobbs/ESG-Mod#1205]
Make a stronger chain gang so its easier to remove pops after you make 75 food per turn on a system.

**Comment by wakystuf** [comment]
Closing this one since I think we concluded that murdering minors isn't actually optimal, rendering this unnecessary

**Comment by Provolonage** [comment]
uh no ive been waiting patiently for this, waky pls

**Comment by wakystuf** [comment]
Haha, OK, fine.
