### ISSUE TITLE
Suggestion: Unclustered Luxuries on World Generation

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1207]
Basically, title.

This is more of a single player suggestion, but the option for the luxuries to spawn un-clustered would be a nice thing before a game start.

Would open a lot of decision making and make choices when choosing which systems to colonize harder and more meaningful.

**Comment by FluffiestPrincess** [comment]
I strongly suspect that this would be an obscene amount of work, but will wait for Cobbs to comment.

**Comment by captaincobbs** [comment]
This is a @wakystuf problem

**Comment by wakystuf** [comment]
Yeah, this is almost impossible. The reason it's possible at all is due to my pre-existing galaxy gen code, but still a huge pain.

**Comment by FluffiestPrincess** [comment]
Closed because rejected.
