### ISSUE TITLE
Need real art for new Scrap Kings

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1208]
Current version looks terrible

![image](https://user-images.githubusercontent.com/79942510/169202149-e84c5549-e76a-4950-b143-35b1a54c2332.png)

**Comment by captaincobbs** [comment]
There isn't any unused art left

**Comment by wakystuf** [comment]
![image](https://user-images.githubusercontent.com/79942510/169211224-4cdf1991-4102-4df2-89e5-905c01a39768.png)
