### ISSUE TITLE
Buff trading dust again

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1216]

**Comment by Provolonage** [comment]
I also agree with this now that luxes are worth a lot less on the market and lux gen is a lot higher on fast trade comps should probably go back to making more dust and less luxes. I would also like if we nerfed dust improvements dust per pop yields but added bonus dust trade value to the system, currently it feels like every faction with pulvis productions, adaptive taxation systems and smart tax collection can make 15k dust without trying

**Comment by wakystuf** [comment]
I think this one should be addressed once I move trading to Astrofinance and make other related adjustments

**Comment by wakystuf** [comment]
OK, proposal:
* Move trade to Astrofinance
* [If I can figure out how to make the game cooperate] add a technology link from Astrofinance to trade
* Move upped trade to where trade is now (the +2 subs and the building)
* Make the Solar Security building much cheaper
* Add an empire improvement on the current upped trade for a much higher % food and indy from passing trade routes and/or cheaper freighters

**Comment by wakystuf** [comment]
Also, need to adjust in certain faction quests, like UC, Lumeris and RB. Maybe others?
Edit: Sounds like UE do too

**Comment by wakystuf** [comment]
Done, except still need to do the quest changes and need lore
![image](https://user-images.githubusercontent.com/79942510/169946654-0f429279-f93a-4d77-b4bb-ffb34ef66e8c.png)

**Comment by Arpharnator** [comment]
Since this is a significant change I put the testing label to see if we want to keep it that way

**Comment by Arpharnator** [comment]
can you elaborate what ships and efficiency is?

**Comment by wakystuf** [comment]
It's just dust vs lux freighters. That's actually how the game displayed it in the GUI automatically; I didn't force that tooltip
