### ISSUE TITLE
Buff Superspuds to +5 FIDSI from +4

### ISSUE THREAD

**Issue by Provolonage** [captaincobbs/ESG-Mod#1218]
I think they are pretty close to being good, however the spread of FIDSI makes it hard for them to really make a noticeable difference, only the influence is really noticeable, a small buff to +5 will make them almost something worth trying to get but probably not anyone's favorite.

**Comment by wakystuf** [comment]
Hmm...I think +4 is the right number, due to the small additional bonus to lux output. +5 would make them essentially equal to the others purely in terms of FIDSI (it would be +25 total, which is between Jadonyx at +20 and the others at +30, which is appropriate given that it provides a mix of them). Fully equal FIDSI is too strong, given that they also provide another secondary effect

**Comment by NoProblemWithThisAcc** [comment]
But also you can't concentrate on any one thing. So if you need that food and all you can do early is superspuds, you're "missing out" by not focusing, compared to redsang.

**Comment by wakystuf** [comment]
Meh, whatever. Everybody needs pretty much all of those things in the early game, except for a couple of races that don't need food.

**Comment by Provolonage** [comment]
im pretty sure jadonyx is 25, eden is 20 and the +.5 on lux is pretty weak since luxes dont sell for much

**Comment by Provolonage** [comment]
the fact thats its 4 of 5 yields is actually so bad it basically doesnt do anything

**Comment by wakystuf** [comment]
Provo, this is why you're not in charge of doing the math. Eden Incense is 15, not 20; Jadonyx is 20, not 25.

Also, early-game luxes start at around 30 dust each, meaning that it's worth ~15 per deposit. Then the value of the T1 luxes will usually crash , but the offset is that the +0.5 will also apply to higher tier luxes once they are unlocked.

**Comment by Provolonage** [comment]
they start at 1 actually, literally never once on fast have I gotten market fast enough for them to be worth more then 1 same with even t2 strats.

**Comment by Provolonage** [comment]
also you didn't have to be so mean

**Comment by FluffiestPrincess** [comment]
Closing this since it's been rejected; contact me on Discord if you have a compelling case for re-opening it.
