### ISSUE TITLE
Change description of "Anti-Expansionists" trait 

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1219]
![image](https://user-images.githubusercontent.com/49691625/169896328-145b9744-de20-483a-a318-43418d4aea0d.png)
Since we changed the colonisation cap to be fixed, there's no need to list it here as a fake percentage.

**Comment by captaincobbs** [comment]
I don't see a need to expand the tooltip, you know what it's always going to do even if the tooltip is mildly lying. Giving more detail in this case would, in my opinion, not be more helpful.
