### ISSUE TITLE
Political skill trees 2 electric boogaloo

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1220]
So  remember when i proposed replacing the generic tree with one based on the political ideology of the hero and you guys said no cuz it'd take to much work? well i ended up doing it myself and its mostly done now so i can make a branch with it if you think it should be an esg feature
some things tho one of them is that its not done yet and the other is that theres this stupid as bug with the gui that idk how to fix and has prevented me from being able to test it yet

**Comment by Arpharnator** [comment]
post the pictures and effects of the skills

**Comment by Tat011** [comment]
pictures? I don't have that idk how to make them. the whole mod is posted on general in the discord but heres an exel of the skills https://docs.google.com/spreadsheets/d/1M5rhoW_FucgERkjY2K6sUgc0DWknS2Yfdm75XUFa8PM/edit?usp=sharing

**Comment by Arpharnator** [comment]
nice

**Comment by NoProblemWithThisAcc** [comment]
I think this would be really cool in ESG. Normally hero selection is A) class, B) race C) starting ability. Having something interact with A) and B) is neat

And you can just copy paste pictures in here tat

**Comment by wakystuf** [comment]
My thoughts were shared previously here: https://github.com/wakystuf/ESG-Mod/issues/1071

**Comment by Tat011** [comment]
Most of that is in here

**Comment by Tat011** [comment]
I thought he meant a picture of the icons? If you mean a picture in game then i can't give you that unless you can tell me what the plugin for GUIElements[HeroSkills] and GUIElements[Categories] is cuz idk how that works

**Comment by Arpharnator** [comment]
well i don't either so no pictures i guess

**Comment by Tat011** [comment]
I'll go ahead and make a branch so people here can see it

**Comment by wakystuf** [comment]
Just make sure it conforms to what was previously discussed

**Comment by Tat011** [comment]
btw this is a good oportunity to change hero ideology if you guys want to, like changing ideologies to avoid repeats for mayors (like cravers having 2 indutrsialists) or when the lore contradicts it (amoeba/pacifist craver) or other reasons (like the starting unfallen hero being pacifist even tho we changed unfallen to ecologist)

**Comment by Arpharnator** [comment]
I don't think changing hero ideology is something that's gonna happen because they typically have quite a bit of lore detailng why they are like that.
For example the Craver pacifist I think has specific lore for being pacifist

**Comment by NoProblemWithThisAcc** [comment]
He means one of each political persuasion. I doubt the lore is that hardcore about why there can't be 2 industrialist cravers, but someone can correct me.

**Comment by Tat011** [comment]
it highly depends on the hero, some have a description that works off of their idelogy, some could be any ideology without issue some have ideology that maches scientist but is ecologist for no reason (cough amoeba cough), either way this hasnt stopped you guys in the past since the unfallen one had lore that worked off of it being a seeker and you changed that

**Comment by Tat011** [comment]
the pacifist craver not only has no explanation on why shes pacifist but it also contradicts it since she goes on a killing spree in her lore

**Comment by Tat011** [comment]
anyway i have no issue going through the lore descriptions of every single hero and changing their ideology if its warranted now that it matters
(most would remain the same of course, id only change it if theres a contradiction)

**Comment by Arpharnator** [comment]
Currently I don't think it's a good idea, i don't think touching "lore" to any extent is what we want to do in the mod, so if the hero s of a certain party i would rather not change it because it's lore

**Comment by Tat011** [comment]
but its not touching lore, none of the descriptions would change, its purely a gameplay change

**Comment by Arpharnator** [comment]
it's To me the heroes parties is like lore, which is why I'd rather not change it

**Comment by FluffiestPrincess** [comment]
I hate to be the bearer of bad news, but you accidentally created your new branch based on Main (i.e. 1.5) not [Development-1-5-1](https://github.com/wakystuf/ESG-Mod/tree/Development-1-5-1) (i.e. 1.6, the branch we're actually working on). You're going to need to sort this out before merging, because currently there are conflicts.

**Comment by Tat011** [comment]
which one is that? i dont see any 1,6

**Comment by FluffiestPrincess** [comment]
[Development-1-5-1](https://github.com/wakystuf/ESG-Mod/tree/Development-1-5-1) is 1.6. If you wish to complain about the name then please do so, just not at me.

**Comment by Tat011** [comment]
reeeeeeeeeeeeeeee fix your name ya dinguses!!

**Comment by Tat011** [comment]
done, you can delete the old branch now (and also the one with my name i made accidentaly)

**Comment by wakystuf** [comment]
Isn't there still a bunch of stuff in here that's inconsistent with what we previously discussed https://github.com/wakystuf/ESG-Mod/issues/1071? Maybe I'm missing something
