### ISSUE TITLE
stygma's graphics

### ISSUE THREAD

**Issue by stygmaskyzoo** [captaincobbs/ESG-Mod#1222]
to do list:

- fix the glow of all my modules to be similar to vanilla

- make icon for the mavros steam page and the major faction collection (and probably rework all 3 of them altogether)

- modules for the harmony mod

- fix vanilla inconsistency when using industrialist instead of industry icon

![ModuleMothershipIndustry2Small](https://user-images.githubusercontent.com/73248181/170098094-99f39cf9-dc28-410e-8943-08540d8c43c8.png)
![ModuleMothershipIndustry3Small](https://user-images.githubusercontent.com/73248181/170098101-519cf821-9a12-4efc-915f-875135180da4.png)
![ModuleMothershipIndustry4Small](https://user-images.githubusercontent.com/73248181/170098102-c42420d6-25b1-4fe7-a767-33f8612a2db9.png)
![ModuleMothershipIndustry1Small](https://user-images.githubusercontent.com/73248181/170098104-7f85ca4c-1e15-4713-8f75-28720a1039dd.png)
![EmpireImprovementQuestUniquePlanet04Large](https://user-images.githubusercontent.com/73248181/170098450-63791a9d-fa5d-4054-939c-e92f9099a1f3.png)
![EmpireImprovementQuestUniquePlanet04Small](https://user-images.githubusercontent.com/73248181/170098461-7fa703e3-3b46-48ef-9e58-b7a9fbf5210c.png)
![EmpireImprovementQuestUniquePlanet07Large](https://user-images.githubusercontent.com/73248181/170098463-b4359ef8-51ae-46de-bdfc-5167549d567b.png)
![EmpireImprovementQuestUniquePlanet07Small](https://user-images.githubusercontent.com/73248181/170098465-8af909ad-f827-4c02-bda4-79b9d1f3886e.png)
![EmpireImprovementQuestTimeLords10Large](https://user-images.githubusercontent.com/73248181/170098467-6c3faaf9-3897-4bb5-a54b-918d0ad0022e.png)
![EmpireImprovementQuestTimeLords10Small](https://user-images.githubusercontent.com/73248181/170098468-d797c2b6-b5c1-41dc-9e0f-6e238c2183a5.png)

**Comment by Arpharnator** [comment]
I can't see the images kek

**Comment by stygmaskyzoo** [comment]
fixed 

also added all icon images for further reference

if someone knows which tier is each module i'd appreciate the info

**Comment by wakystuf** [comment]
What is the latest on this item? Should I close it or leave it open?

**Comment by stygmaskyzoo** [comment]
> What is the latest on this item? Should I close it or leave it open?

im closing it, i know what has to be done and i'll keep track of this somewhere else
