### ISSUE TITLE
Spicing Costs

### ISSUE THREAD

**Issue by NoProblemWithThisAcc** [captaincobbs/ESG-Mod#1237]
Gene Splicing needs to a regularly usable mechanic, like any other gameplay affinity. The current problem is that it's too powerful. Current attempts to balance it just made it less usable overall. I propose we move in the other direction: make the splice costs smaller as well as the splice benefits.

0) The point buy costs of all minors and majors should be changed. All minors population (citizen) picks are worth 5 points except Tikanan, Z'vali, Illo, Epistis, Bhagaba, and Niris which are 10 points. All additional major population (citizen traits) are also 5 points except Bereaved, Horatio, Unfallen, Nakalim, Sophons, and Lumeris which are 10 points. Riftborn should be 0 but require another citizen pick (you can't make more, but it's a 'free' pop after you've already paid for another one). Cravers and Vodyani are worth -5 since they actively make your empire worse (you starve or your planets deplete) if allowed to grow.
Note that this does not affect balance unless you use customs. It is helpful to show players relative power for splices, though. Specifically this allows 5point minors to give a balanced 2 effective FIDS, 5point majors or 10 point minors to give 3 effective FIDS, and all other majors to give 4 effective FIDS, consistently.

1) All the splice costs can be reduced as follows.
![image](https://user-images.githubusercontent.com/77858116/171485933-2711cfed-e286-416e-80f1-d31ca8cede49.png)
This brings the average minor splice from 4.7 effective FIDS to 2.2 effective FIDS. Some 'rules' that should have been in vanilla is that splicing always gives less of a kind of bonus than the original race. So the mavros splice cannot give +4 industry because the base pop can only get +3. Also conditional bonuses count for half, so the mavros +1 industry, +2 industry on hot would total to 2 effective FIDS, not 3. These sorts of conditional bonuses are necessary to fully meet the FIDS thresholds already listed. Yes I am aware that this unavoidably makes Baryxo and Sefaloros slightly competing splices; too bad. I'm also counting each point of influence as worth 2 influence just to be brutal with this nerf.

2) Ease the splice cost from (number of splices)*2.5 down to (number of splices)*1. This introduces fewer 'gaps' where you have various minors on various stages of growth but none of them are the right total count to splice. There will still be gaps anytime the number isn't a static one, but at least this way a player can think "I've already spliced at splice count 4 so I can't splice again until getting a higher number of something." Getting to play the thing that's special about your race is fun.
Currently players think "Well I shouldn't splice at 4 and starport because then I'll have to splice at 5. But I don't have any at five. I guess I'll just wait to grow that 4 into a five and try to get an exact three..." which results in a seemingly infinite spiral of just never having the pop counts line up correctly. Again, this wouldn't be totally alleviated, but can be a lot better than it is currently or in vanilla.

Thoughts on these ideas?

**Comment by Arpharnator** [comment]
unplayable on smaller maps if that's the case
+ costs are only 2.5 atm compared to 2 vanilla and 4 before

**Comment by NoProblemWithThisAcc** [comment]
I agree that smaller maps make large pop splice cost are unplayable as ESG 1.6 stands currently despite thes change: "Horatio Splice cost reduced, from 3 + $(AssimilatedPopulationsCount) * 3 to Ceil(2.5 + $(AssimilatedPopulationsCount) * 2.5)."

You'll be glad to know that going from 2.5 atm down to 1 (but with the nerfed splice bonuses) would better approximate the power curve.

**Comment by Arpharnator** [comment]
First I was responding to your idea of reducing the slice cost while reducing the bonuses, and saying that it would make the affinity barely noticeable on smaller maps.

I think there has been some really significant discussion on this subject dating back to the era when it was first changed to 3, and clearly now isn't the time to change things.
While there has been some discontent with the usage of the horatio affinity, that's pretty much unavoidable due to the nature of the affinity.

**Comment by Provolonage** [comment]
I like the idea but I hate the idea of splices giving conditionals. I'd rather just get +1 indy and +1 science from pulsos, ratio is always going to go full fertile temperate for the pop slots synergy with the collection bonus, all sterile splices will be ignored basically and most conditionals will be pretty bad. Also I think Gene Hunter is actually weak you can't splice more then 4 things right now, you run out of pop slots, or its gets to be too late in the game to spread those remnants you got from the event on turn 32. I really do want to push the idea of small splice costs but smaller rewards however I think it is the best way forward and I don't really think map size matters that much, even on small I'm giving up on splices, its just rng, you basically get the same number of curios regardless of map size unless you get to poach some from bad players in larger games, which we shouldn't be balancing around.
