### ISSUE TITLE
Replace Rb's Signal with something else

### ISSUE THREAD

**Issue by Provolonage** [captaincobbs/ESG-Mod#1239]
It's too much rng, if we want Rb to start with 4 pop jsut give them a 3rd Rb.

**Comment by FluffiestPrincess** [comment]
For clarification, are you talking about the predetermined "Signal" type anomaly that appears in the Riftborn starting system on Balanced Starts mode?

**Comment by wakystuf** [comment]
@FluffiestPrincess Yes, that's correct. I told @Provolonage that I'd do this one, so I'm assigning myself now
