### ISSUE TITLE
Make academy quest start sooner

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1246]
Its an interesting quest and a real shame we never see it. make it start around the mid game

**Comment by Provolonage** [comment]
I'm 99% sure the quest start trigger is someone finding the academy because it happens on like turn 5 in most mp games.

**Comment by Tat011** [comment]
i mean the one about resurrecting the lost

**Comment by Provolonage** [comment]
oh no clue sorry

**Comment by NoProblemWithThisAcc** [comment]
It is an awfully late game quest.

**Comment by captaincobbs** [comment]
From what I understand it triggers after everyone has finished the unique planet quest. But no, we can't, it's triggered by something from the C#.

**Comment by captaincobbs** [comment]
I believe I'm right, it's manually triggered by something out of our control and I have no idea what the other trigger conditions may be.
