### ISSUE TITLE
Rework Population Political Affinities to more closely match their lore

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1248]
Will post a list here once we've worked one out

**Comment by Tat011** [comment]
There are some things we agreed which is
amoeba
ecologist, militarist to pacifist, religious to scientist
Remnant
pacifist, pacifist to industrialist, anti militarist
Horatio
Ecologist, pacifist to religious, ant scientist
Epystis
ecologist, ecologist to militarist and industrialist to pacifist

Pops we have yet to go through but should
Srheyedin and Mezari
Gnashast and Tikanan 
Sowers 
Harmony
