### ISSUE TITLE
UC Beacon for Special Node immunity

### ISSUE THREAD

**Issue by NoProblemWithThisAcc** [captaincobbs/ESG-Mod#1249]
This expected behavior
![image](https://user-images.githubusercontent.com/77858116/173273146-16823b7f-1a0c-4939-ba5d-54c9175f53bb.png)
can result in UC being auto-detected when neutron stars are next to your homeworld and the only wormhole out of the constellation such as:
![image](https://user-images.githubusercontent.com/77858116/173273256-915dbf21-c6a3-4ef4-be89-103e25c6aa40.png)
Issue made upon request

Edit: Cobbs found out it's either an 'everyone thing' or a nobody thing. So... looks like this isn't doable like the thought.

**Comment by wakystuf** [comment]
Closed due to inactivity
