### ISSUE TITLE
Upgraded attackers coming out of hanger with unupgraded mp cap 

### ISSUE THREAD

**Issue by Provolonage** [captaincobbs/ESG-Mod#1251]
Upgraded attackers were coming out of hanger with only base mp cap filled and would need to sit on a system for an extra turn to get the remains 50%.

**Comment by wakystuf** [comment]
I believe this is a vanilla bug with specifically the UE attacker, but let me know if it crops up again and I can take another look. I didn't see any other hulls that should have this issue
