### ISSUE TITLE
A lot of pops don't have the effects they claim they do

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1254]
Works fine:
Sowers, Tikannan, UC, Unfallen, Vaulters, Vodyani, Eyeder, Riftborn, Nakalim, Lumeris, Amblyr, Amoeba, Barsyxo, Bereaved, Xirmisala, Deuyivans, Epistis, Foundlings, Haroshems, Hissho, Horatio, Illo, Kalgeros, Kalmat, Mavros, Niris

Doesnt work:
Pilgrims has no anomaly boost
Bhagaba doesnt get more baseline influence when boosted
Galvrans makes +3 science on deposit instead of the advertised +2 unboosted and gains +1 on deposit when boosted which is correct but idk why they gain +1 on deposit rather than +2
Gnashasts increase luxuries by 0.4 rather than 0.2 and the boost is also doubled
Harmony also has the same issue and it also makes +3 science unboosted rather than 2 and only gains +1 on boost which also works as advertized but its weird its not doubled
Imperials make +2 industry unboosted rather than 1 but the boost works fine boosting +1. their influence isnt boosted tho 
Mezari also doesnt give more influence when boosted
kaltikma gives +4 baseline instead of +2 unboosted but booosting gives the right ammount
Pulsos give +2 industry unboosted rather than 1 but give the correct boosted ammount
Remnant dust boost doesnt work
ZVali boost doesnt increase science
Yuusho give +60 capacity on sterile instead of +100 (+100 would be the total ammount counting the base increase) and the boosting is weird idk what a "on martial tradition" is but it doesn seem to work as intended (why doesnt it double capacity like with other capacity pops?)
Sophons give +2 science base rather than 1
Shereyin give no additional influence when boosted
Sephaloros gives +2 indi rather than 1 unboosted

Idk how to test:
Craver, any bombardment trait

**Comment by wakystuf** [comment]
Thanks for finding all of these. To clarify, for the ones that don't work, does the pop lie and claim that it will provide a certain bonus, and then the calculation does not match the GUI? Or are they simply not doubling certain things when boosted?

**Comment by Tat011** [comment]
some pops dont give the ammount they say they do whithout boosts like all the +1 indi races actually giving +2 instead
For boosts the gui always says that it doubles the effect but it doesnt always work

**Comment by wakystuf** [comment]
Yeah this is actually not just one bug, unfortunately; I don't think there's any real unifying theme, which means I have to fix them one by one.

Fixed:
* Pilgrims
* Bhagaba, Mezari and Sheredyn (all the same bug)
* Z'Vali
* Remnant

Bugs that I cannot replicate (IE, these work fine in my testing):
* Pulsos
* Sophons
* Imperials
* Galvrans
* Gnashast
* Kal'Tik'Ma
* Yuusho (though there is a weird GUI bug with this one, the gameplay is fine)
* Sefaloros
* Harmony
