### ISSUE TITLE
Balance Pass on hero experience multiplier vs experience per turn

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1268]
I found some oddity while checking the code, some effects used experience per turn while others used experience multiplier.
I decided to change any percent increase of experience multiplier to be experience per turn.
This would also explain vodyani heroes levelling up 2 to 3 times faster than your average hero, and the endless hero being barely affected by it's malus to experience

**Comment by wakystuf** [comment]
Experience per turn is a flat # of XP; Experience multiplier is the % effect. Those are already working properly, I believe. In this version Vault of Governance would give 1 XP per turn, which is worthless

**Comment by wakystuf** [comment]
Here's an example where you can see both effects (the T2 religious law): 
`<Modifier TargetProperty="ExperienceMultiplier" Operation="Addition" Value="0.25" Path="../ClassEmpire//ClassHero"/>
<Modifier TargetProperty="ExperiencePerTurn" Operation="Addition" Value="4" Path="../ClassEmpire//ClassHero"/> `

**Comment by Arpharnator** [comment]
No, in this version Vault of Governance would give 100% extra experience per turn.
If you check the code you will find that there are other rewards that increase the experience per turn reward by a percentage as well.
Experience multiplier include everything, that means from battles and constructions as well.
that's why there were some very high leader level sometimes, when the tooltip shows the same effect (Experience Per turn)

**Comment by Arpharnator** [comment]
If you check other rewarsd you will find Experience per turn being multiplied by the Percent operation

**Comment by Arpharnator** [comment]
And we should change these to be only one type.
Having two effects that change hero xp radically with the same tooltip is certainly suspicious.

**Comment by wakystuf** [comment]
ExperiencePerTurn is a flat variable, so if VoG is adding 1 of that, then it is a flat +1 XP

Yes, experience multiplier affects everything; that is the whole point. The small amounts of XP provided from the flat "XP per turn" effects are indeed affected by experience multiplier, though that doesn't matter much.

Where are you seeing the tooltip showing the same effect? I'm on my laptop now, but the Admit & Improve law shows both effects and I think it's fairly clear that 1 of them is flat and 1 of them is %.

**Comment by Arpharnator** [comment]
My bad, it looks like I forgot to change the bonus to be Percent for the stuff I changed.

My point about Experience Multiplier is that only certain specific building/improvements grant it, while others are Experience Per Turn.

What I'm saying when I say that both tooltip show the same effect, is that it's not clear whether a bonus is Experience Multiplier or Experience Per Turn. 
Both effects say "Experience Per Turn" whether they are talking about adding a % bonus to the Experience per turn, or adding something to the Experience Multiplier.

**Comment by Arpharnator** [comment]
For example, in the case of admit and improve, the to
![image](https://user-images.githubusercontent.com/49691625/174836742-81bf2828-e761-4f07-9653-f85b080b15d0.png)
![image](https://user-images.githubusercontent.com/49691625/174836954-62b09492-13b4-4fee-9e7d-de7c2eecda3f.png)

the Sheredyn bonus has this code : 
TargetProperty="ExperiencePerTurn" Operation="Addition" Value="5" Path="ClassEmpire//ClassHero"/>
TargetProperty="ExperiencePerTurn" Operation="Percent" Value="0.30" Path="ClassEmpire//ClassHero"/>

the law has this code  :
TargetProperty="ExperienceMultiplier" Operation="Addition" Value="0.25" Path="../ClassEmpire//ClassHero"/>
TargetProperty="ExperiencePerTurn" Operation="Addition" Value="4" Path="../ClassEmpire//ClassHero"/>
TargetProperty="DemocracyLawsDiversityHasReligious" Operation="Addition" Value="1" Path="../ClassEmpire" TooltipHidden="true"/>

**Comment by Arpharnator** [comment]
Actually it looks like I can't read.

In that case we should instead review the effects and see if they make sense and are balanced.
I believe not many players are aware of what it means to have Experience Per Turn % and have Experience on Heroes

**Comment by wakystuf** [comment]
I think for the most part they are fine; I've looked at them before. Are there any specific ones that you are concerned are not balanced?

**Comment by Arpharnator** [comment]
well considering the meagers amount Experience per Turn gives, we should change all of them to be Experience Multipliers or Or vice-versa.

**Comment by wakystuf** [comment]
Like which ones? I think having some of both can be fine, since there is a fixed and a scaling portion. Like an effect that gives flat food and % food at the same time, it's fine to combine them. If there are specific ones that we need to look at, then we can, but I wouldn't eliminate all flat XP effects.

**Comment by Arpharnator** [comment]
I'll have to check for which ones to change.

I'm going to reopen this and change the title

**Comment by wakystuf** [comment]
OK, that's fine. I think most of them are fine as-is, but we can certainly discuss any that you think are a problem.

**Comment by Arpharnator** [comment]
I've looked into the passive xp reward, and it's definitely not very high.
The formula is : 
(1.15 ^ (SystemLevel - 1)) * (Pop / 2)

for example : 
SD = 1
Pop = 10
-> 5 passive xp

SD = 2
Pop = 10
-> 5.75 passive xp

SD = 3
Pop = 10
-> 6.61 passive xp

SD = 4
Pop = 10
-> 7.6 passive xp

**Comment by wakystuf** [comment]
Yes though remember that governor XP comes primarily from completed constructions

**Comment by Arpharnator** [comment]
I've put this there to illustrate that Experience Per Turn is really not a good bonus

**Comment by Arpharnator** [comment]
note that these numbers are for normal speed

**Comment by wakystuf** [comment]
Yeah Experience Per Turn is a small flat effect, that's it. Aside from that Sheredyn bonus (which we can adjust to be ExperienceMultiplier), is there anything that gives purely Experience Per Turn?

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/174879708-2b679e2e-4ed4-409d-881e-22201fd7f6f1.png)
i lied

**Comment by Arpharnator** [comment]
turns out a combination of Experience Multiplier and Experience Per Turn can yield high experience per turn

note that this is for fast speed, normal would be halved

**Comment by wakystuf** [comment]
Well yes but your previous point is still correct: the value of the bonus here is from the 2.5x Multiplier; the flat portion of +4 Experience Per Turn is still not very useful.

**Comment by Arpharnator** [comment]
The current formula is : 
(1 + 33.4 + 4 + 4) * 2.5 * 1.55 * 2 (gamespeed)

**Comment by wakystuf** [comment]
I think this one is now included in the various other XP-related issues, so I am closing for now. Feel free to reopen if there are others we should review.
