### ISSUE TITLE
Fix max value on senator skills multiplicator for dictatorship and religious law

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1275]
This fixes the issues where this law would not work with dictatorship.

**Comment by wakystuf** [comment]
Also agreed

**Comment by wakystuf** [comment]
Am I correct that this is not included in your PR? I'd probably just tweak it quickly so that it's all covered together

**Comment by Arpharnator** [comment]
I just opened the issue to remember it existed, I believe the PR already ahs been merged
