### ISSUE TITLE
Dictatorship experience change

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1278]
the 25% Experience per turn now becomes a 25% experience multiplier

**Comment by wakystuf** [comment]
Looks good; I'm linking the PR

**Comment by Zingybird** [comment]
May I ask if this can be applied to autocracy or whatever is the similar version of the law changes

**Comment by Arpharnator** [comment]
Autocracy doesn't have this bonus to begin with as far as im aware, so no goodies

**Comment by Zingybird** [comment]
Okay all good
