### ISSUE TITLE
Other Horatio Tweaks

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1283]
* Cut in half collection bonus 3
* Cut in half All Hands Dictum
* Reduce numbers on Cool Collections
* Reduce splice cost to 2, and cap at 10

@Arpharnator Thoughts?

**Comment by Arpharnator** [comment]
I agree with everything except for All Hands Dictum which is what is known as hot garbage.
No way im spending 4 inf per pop for 1% ind and science per splice

**Comment by wakystuf** [comment]
OK, I'll make it 1.5% instead. It's currently at 2%, so it will need to go down somewhat. The Republic version especially would be OP if we left as-is, since it'd be 30% indy and sci
