### ISSUE TITLE
Make carriers cost more indy

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1309]
Could also increase strat costs, though I'll hold off on that for now

**Comment by Provolonage** [comment]
no to both please omg I just made a huge post about how everyone cheats building ships by jsut making hulls and getting 33% off everything, also you might as well delete the ratio carrier if you actually increase it by any real amount

**Comment by wakystuf** [comment]
Doesn't increasing the hull cost help alleviate the empty-hull issue that you're describing? 

I will point out that you also responded directly to my Discord post about this to say that it sounded good...

**Comment by Provolonage** [comment]
ok this is mb for not reading point 4 properly so im sorry, but to clarify I was agreeing to points 1-3, my bad.

**Comment by wakystuf** [comment]
Well at least you're honest.

Doesn't increasing carrier hull cost help solve the rushing issue, and not worsen the empty hull/retrofit issue (since the cost increase hits the hull directly)?

**Comment by Zingybird** [comment]
I mean this would make medium hulls and small hulls used more
