### ISSUE TITLE
Cravers questline rework

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#132]
Name: Artificial Hive Minds

**Comment by Doruk-Coskun** [comment]
- Change Chapter 1 Industrialist path quest 2 (1.2) reward, Cyborg Stomachs. 20% -> +25 food on outposts, +1 depletion point on outpost planet per turn.
- Reduce the industry cost of Hive Hall to 560 industry on fast. The effect is underwhelming and will be discussed in the future.
- Synchronous Hive cost 50/50 -> 30/30 blue/yellow and 560 industry on fast.
- Accelerated Ovipositor effect +30% manpower capacity on systems and +150 Defensive manpower deployment limit.
- Change Chapter 3 Religious path quest 1 requirement to, max hero level + 2.
- Make religious path final quest reward to Artificial Hive Minds, +50 science per cp destroyed on the empire.

These changes are accepted.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103150800-a38d4180-4788-11eb-904a-673562dbaa14.png)

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103175591-10353880-487c-11eb-9247-4a4bc83a0ecd.png)

- Change Chapter 2 Industrialist quest religious path objective requirement to 35 Titanium and 35 Hyperium.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103175648-9a7d9c80-487c-11eb-9820-2a4533ac2489.png)

- Change Chapter 3-Religious quest religious path objective requirement to, search the curiosity with Reyarn Cious (Quest reward hero for Cravers, Endless).
- Accelerated Ovipositor effect +30% manpower capacity on systems and +150 Defensive manpower deployment limit on systems.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103175738-47f0b000-487d-11eb-81fa-a44b05e2f610.png)

- Change Chapter 3-Industrialist quest religious path objective requirement to, max hero level in the empire.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103175757-73739a80-487d-11eb-90e2-41dade585c39.png)

- Change Chapter 1 Industrialist path quest 2 (1.2) reward, Cyborg Stomachs. 20% -> +15 food on outposts, +1 depletion point on outpost planets per turn.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103175793-bc2b5380-487d-11eb-8d55-68860b4adc3a.png)

- Synchronous Hive effect +30 approval on the system, +10 influence on the system reworked to +10 approval on every system and +10 influence on every system.

Even though the GUI doesn't reflect it, both influence and approval work on every system as intended.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103175835-175d4600-487e-11eb-8103-2635ef39f043.png)

- Signal Seeker cost increased to 560 industry, effects reworked to give +10 -> +8 vision range on the system, +0 -> +2 vision range on all fleets, +50 -> +80 industry on the system.

**Comment by wakystuf** [comment]
Once you're feeling better, let's go through where all this landed, particularly given your comment that the Cravers overall got a rework (not just the quests)

**Comment by captaincobbs** [comment]
I asked Chaos to write down his changes whenever he's available, he was entirely in charge of this.

**Comment by wakystuf** [comment]
Sounds good.

**Comment by Doruk-Coskun** [comment]
Complete list of Cravers changes:
- Added "Voice of the Queen" faction trait. Voice of the Queen: 10 Influence per CP destroyed
- Changed started tech "N-Way Fusion" to "Ubiquitous Surveillance"
- Change Chapter 1 Industrialist path quest 2 (1.2) reward, Cyborg Stomachs. 20% -> +15 food on outposts, +1 depletion point on outpost planets per turn.
- Signal Seeker cost increased to 280 -> 560 industry, effects reworked to give +10 -> +8 vision range on the system, +0 -> +2 vision range on all fleets, +50 -> +80 industry on the system.
- Reduce the industry cost of Hive Hall to 1560 -> 280 industry on Fast. Additional effect added: +50% experience to Governor Hero on the system
- Infinity Shield quest module stats have been reworked according to the fleet combat balance changes.
- Synchronous Hive costs 50/50 -> 20/20 Titanium/Hyperium and 780 industry on Fast.
- Synchronous Hive effect +30 approval on the system, +10 influence on the system reworked to +10 Approval on every system and +10 Influence on every system.
- Accelerated Ovipositor effect +30% manpower capacity on systems and +150 Defensive manpower deployment limit on systems.
- Change Chapter 2-Industrialist quest religious path objective requirement to 50/50 -> 35/35 Titanium/Hyperium.
Change Chapter 3-Industrialist quest religious path objective requirement to, max hero level in the empire.
Change Chapter 3-Religious quest religious path objective requirement to, search the curiosity with Reyarn Cious (Quest reward hero for Cravers, Endless).
Make religious path final quest reward to Artificial Hive Minds, +50 science per CP destroyed on the empire.
- Infinite Factory system is changed to a 4 planet system with guaranteed Titanium, Hyperium and Adamantium spawn.

**Comment by wakystuf** [comment]
Thanks! I've included these
