### ISSUE TITLE
Fixing Gamespeed scaling

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1324]
Fixed:
-Hero XP bug
-Probe regen and stock 
-Minor diplo costs (will keep Fast as-is and adjust the others)
-Law charge time (ex: Trusted Broker, YIMBY)
-Minor stress
-Trade company XP

Maybe fix in the future:
-Colonizer move speed
-Scout move speed

Never fix:
-Military ship movement

**Comment by Provolonage** [comment]
please dont tell me we scaled probe gen speed with game speed, please tell me my browser is busted and the date is supposed to say 4/1/22

**Comment by wakystuf** [comment]
That happened a couple of weeks ago I think; generally it seemed like everyone liked it. It fixes a lot of other problems too
