### ISSUE TITLE
Horatio quest curio bugged

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1328]
Searchable with only 1k dust even though quest requires 10k. It will correctly deduct 10k dust...if you have that much. But it is searchable with less.

Now fixed.

**Comment by Provolonage** [comment]
uh im pretty sure i talked you and and arphar about this before i went on vacation and we all agreed to keep it at 1k since 10k is a horrible idea or maybe im trying to gaslight you.

**Comment by wakystuf** [comment]
I'm fine with reducing the number, as long as we do it in both. All I did was fix a straight up bug where the quest displays inaccurate information about what is required.

@Arpharnator can you and Provo figure out the right number and then we can adjust both parts?
