### ISSUE TITLE
Make RB scale properly with Gamespeed (and a few other minor RB tweaks)

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1330]
The main changes (complete):
* Make pop constructible build 2 pops on Fast gamespeed
* Double the base pop cost to offset buff from 2x faster throughput on Fast
* Reduce Chassis Optimization to -25% cost, and the hybrid effect to -12.5%
* Scale spaceport capacity with gamespeed (it works for up to 10; I tested)
* MP conversion constructibles should scale with gamespeed

Other random minor changes (all complete):
* Fix Cube of Viceroy being able to be put into multiple construction queues
* Monsoon should be only 160 to colonize, in-line with other non-Fertile planets
* Need a GUI element for OutpostActionStealGrowth2SelfTimeLordsEffect
* Need to replace the old tooltip from the food rework for "no organic growth"
* Look into minor bug with excess food stacking with no organic growth

**Comment by Provolonage** [comment]
how does the ui work for 10 pop spaceports?

**Comment by wakystuf** [comment]
It adds a second row below. That one is already live in Steam so you can see
