### ISSUE TITLE
Pop Collection 3's are wildly variable in quality

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1336]
Longer-term issue, but probably should get a balance pass at some point

**Comment by NoProblemWithThisAcc** [comment]
I'd be happy to run a comparison (discord PM me) for this and any other traits one, against one another, as if each noncustom is not an island unto itself. Note that this requires talking about evil foreign custom logic that makes certain go up in a ball of smoke.

**Comment by FluffiestPrincess** [comment]
I made a [google drive folder](https://drive.google.com/drive/folders/1f3NI2-1rAWdkHjUSDWon8LIfA5eofY0v?usp=sharing) with screenshots of all the existing Pop Collection boni, in case that helps. Unless someone wants to unilaterally decide what they should be changed to, I guess this has to be a discussion.

**Comment by wakystuf** [comment]
Thanks! Quite helpful. I'll post a spreadsheet with proposed changes probably later this week.

**Comment by wakystuf** [comment]
Chnages:

![image](https://user-images.githubusercontent.com/79942510/211725761-9513e81c-c0b1-44b4-a7f8-c6683fe2a58c.png)

**Comment by captaincobbs** [comment]
I have no problems with any of these from a design perspective, though I worry that the +5% influence is going to be a bit busted since that'll include pirate hulls.

**Comment by wakystuf** [comment]
Nah, it works fine. It's looking for Hull Types, not ship designs. Otherwise the CPs effect that is based on hulls would go crazy with mercenaries, and it does not.

**Comment by captaincobbs** [comment]
ah so ship classes?

**Comment by wakystuf** [comment]
Basically yes, although the variable is literally HullTypes

**Comment by wakystuf** [comment]
This was a huge pain (particularly the GUI with the setting), but it all works now except for one minor GUI bug: the lines that use SearchValueFromPath don't show up properly on the tooltip (though they do show up if you hover over collection III). @captaincobbs do you have any idea why that would happen?

**Comment by captaincobbs** [comment]
I believe they're just a special case, never quite figured out what exactly what was different about them, but they always seem to have tooltip or gui problems. I tend to hide them and make a fake tooltip for them.

**Comment by wakystuf** [comment]
Yeah, the problem is that if I use TooltipHidden=True, then I'll end up hiding the effects. For example, if there is a collection III that affects system science, then I don't want it to hide that number in the system view of science

**Comment by captaincobbs** [comment]
use TooltipHiddenIfPathInvalid, then set the conditional path, and use UselessForTooltip property, then override the tooltip with whatever

**Comment by wakystuf** [comment]
Nah that won't work since then it will hide they will show up twice on the tooltip
