### ISSUE TITLE
Predators trait does nothing

### ISSUE THREAD

**Issue by haydensj** [captaincobbs/ESG-Mod#1338]
When creating a custom faction with the Predators trait, I expected to be able to see enemy homeworlds when I started the game. Instead, I saw no noticable effect.

**Comment by Arpharnator** [comment]
i guess the solution is to remove the trait

**Comment by wakystuf** [comment]
I have no idea how to fix this, so I'm going to close unless anyone else has ideas

**Comment by wakystuf** [comment]
![Predators](https://user-images.githubusercontent.com/79942510/186527617-4afaf3af-db61-4754-9c20-c0d9b3725ddd.jpg)

This seems to be working as indended
