### ISSUE TITLE
Make starless system not insta bad

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1339]
Make it possible for it to have 4 and 5 planets and make the chances of planet ammount match other star types instead of being 75%+ chance of 1 planet
allow ice, barren, ash and lava to spawn on them cuz it makes sense and increases variety
Really im just tired of skipping every starless i see  (unless they have a minor or something) cuz amplitude decided to make them trash for no reason. 
i even already have the code for this cuz i made it for another mod so its not like any effort would be required to make it happen.

**Comment by wakystuf** [comment]
This seems mostly fine if you want to implement it as long as nobody objects
