### ISSUE TITLE
Fix Traits below "On Strategic" not having proper assimilation bonus (Population Modifiers)

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#134]

**Comment by captaincobbs** [comment]
Test this with Vaulters, make sure the pop bonus works at all.

**Comment by captaincobbs** [comment]
Assimilation works, Pop bonus does not

**Comment by captaincobbs** [comment]
Testing in luxury-rework

**Comment by Arpharnator** [comment]
Vaulter bonus works

**Comment by wakystuf** [comment]
What exactly was this issue? Is this a Horatio gene splicing thing?

**Comment by captaincobbs** [comment]
Basically, in previous versions NOTHING about traits that required a specific object to be on a planet worked. Luxury Resources, Anomalies, Temples, etc.

**Comment by wakystuf** [comment]
Ah, got it. This is only for the newly-created custom traits?

**Comment by captaincobbs** [comment]
yes

**Comment by wakystuf** [comment]
OK, got it
