### ISSUE TITLE
Visual Bug - Planets don't change visual size when terraformed

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1342]
Title.

Here are two screenshots. As you can see, both planets have been terraformed to huge, but they keep their older visual.
![Screenshot_1](https://user-images.githubusercontent.com/105115857/184496787-1ecfd191-6c2b-4508-a173-93c5ce729ead.png)
![Screenshot_2](https://user-images.githubusercontent.com/105115857/184496789-cd3f4343-1a0b-4c91-a979-ce40a4824b29.png)

**Comment by wakystuf** [comment]
I don't think this is fixable, particularly without Cobbs
