### ISSUE TITLE
Possible Bug - Population Cloning Not Working Properly?

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1343]
So basically, I have 8.2k food in excess and a clone required 700, I have a bit of trouble understanding why I can't clone more?
![Screenshot_3](https://user-images.githubusercontent.com/105115857/184497354-cd2cce3b-e704-4926-81ea-0e683838f24f.png)

**Comment by wakystuf** [comment]
How much excess food does it say you have?

**Comment by Arpharnator** [comment]
the stock is too low, it's now recovering the stock that has been spent in excess.
if you check the stock you will see that it is negative and that you don't have enough food to make the stock go higher than 1 pop more next turn .
