### ISSUE TITLE
If you can't see the UC nexus when they Stay Ahead Law suicide, you cannot detect the uncolonized system later.

### ISSUE THREAD

**Issue by Eighth-of-Third** [captaincobbs/ESG-Mod#1346]
![20220813183148_1](https://user-images.githubusercontent.com/4412171/184560708-1a4b43f1-a396-4ce4-bd92-0ec809fa1424.jpg)
![20220813183200_1](https://user-images.githubusercontent.com/4412171/184560710-f4be5a58-9d54-42b3-9c10-c4a2e30a100a.jpg)

**Comment by wakystuf** [comment]
I can't test this by myself; does anyone else want to give it a shot and let me know if it works?

**Comment by wakystuf** [comment]
I am marking this as finished pending another bug report of this issue
