### ISSUE TITLE
Horatio carrier has a small weapon slot that counts as a large

### ISSUE THREAD

**Issue by Eighth-of-Third** [captaincobbs/ESG-Mod#1347]
![20220814055804_1](https://user-images.githubusercontent.com/4412171/184560787-82c85754-bc2f-4514-8f4e-3e84e62aefd9.jpg)
![20220814055810_1](https://user-images.githubusercontent.com/4412171/184560790-d180d0a9-01fd-452a-b157-626581cbd6bd.jpg)

**Comment by wakystuf** [comment]
@Arpharnator Horatio Prime, do you know anything about this?

**Comment by wakystuf** [comment]
Years later we're still finding vanilla bugs

**Comment by Provolonage** [comment]
Does it have the multipliers for damage and cost or no?

**Comment by Arpharnator** [comment]
yes i do know about it watchu gonna do
also the left heavy mount costs half as much to put a gun on
