### ISSUE TITLE
More Outpost fixes

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1350]
* Adjusted calculation priority of MP stealing growth so that the + and - parts stack in the same way (IE, cancel out if you have both)
* Tweaked Lumeris growth to target the correct variable so that it stacks with the dust one, like all other food boosts
* Made Lumeris outposts flat 300 dust, so that they are still FAR more expensive than most factions' colonization, but no longer become crazy expensive mid/late

**Comment by Provolonage** [comment]
Please see my other post before you ruin the game with this change.

**Comment by Kil10naire** [comment]
There seems to be contention regarding this Issue, so I feel the need to ask "What, if anything, ended up being changed?"

**Comment by wakystuf** [comment]
I think only the 3rd bullet was controversial, so for that one I ended up making Lumeris col cost the same as before, but a) capped at 600 dust and b) scaled with gamespeed

**Comment by Kil10naire** [comment]
Rojer.
