### ISSUE TITLE
RB Quest Tweak

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1354]
Goal to pass an ecologist law is probably bad. Maybe replace with "build 10 food buildings" instead

**Comment by wakystuf** [comment]
Update: the code requires it to be new buildings, so I made it only 8 instead

**Comment by Kil10naire** [comment]
I assume you would want the quest picture to be updated as well?

**Comment by wakystuf** [comment]
Good point

![image](https://user-images.githubusercontent.com/79942510/184732513-80b881c6-f497-4df4-aa1b-c52b55e53fca.png)
