### ISSUE TITLE
More Gamespeed Scaling

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1355]
* Law enactment doesn't scale at all currently
* Initial resource endowments (dust and infl) also don't scale, but the Fast amounts are fine. I'll leave those alone and rebalance the other gamespeeds accordingly

**Comment by Kil10naire** [comment]
Is the Law Enactment cost one of the changes that is going to stay the same on Fast, but getting rebalanced for other speeds? Or did that one get changed for Fast as well?

**Comment by wakystuf** [comment]
No, law enactment got changed (lowered) for Fast. Initial resources are the same as before on Fast, but 2x on Normal, 3x on Slow and 4x on Endless

**Comment by Kil10naire** [comment]
Got it.
