### ISSUE TITLE
Sophon quest tweaks

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1356]
![image](https://user-images.githubusercontent.com/79942510/185042550-201925be-ffa5-48ec-873a-dc94bcbe8103.png)

**Comment by wakystuf** [comment]
#1345 is the PR, but I'm capped on issues linked

**Comment by wakystuf** [comment]
Updates, also fixed 3 vanilla bugs:
* The scientist chapter 4 objective to research 5 science techs no longer counts techs from all empires
* Illumination and Radiance will no longer start out with no ownership
* Illumination now starts with a colony base

**Comment by Kil10naire** [comment]
Did you end up swapping the Empire Tech Cost Reduction to Economy Tech Cost Reduction from the pacifist line's final step? If so the picture is going to need to be updated, unfortunately.

**Comment by wakystuf** [comment]
Not yet, since fixing the Illumination bug took vastly longer than I'd expected. I'll probably do that as a separate issue in a future update

**Comment by Kil10naire** [comment]
Alright, no worries.
