### ISSUE TITLE
Some non gameplay related things i'd like to see

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1362]
people for some reason ree at the idea of making non gameplay related changes but i guess ill give it a shot (i'm willing to do all these myself btw, i'm not asking anyone else to do anything)
More empire colors since there's a rather small ammount currently which means not much choice
More system and special node names since there are a lot but youll constantly see the same ones over and over
More, better tips and if possible make faction specific tips only play when loading that specific faction
on the partially gameply related changes
Take a page from my better planet gen mod and allow any planet to spawn in any star for varietys sake (tho of course hot planets on cold stars would be rather rare) + make gas giant temp chance be affected by star temp
also allow minors to have more than 1 planet in their pool also for variety's sake

**Comment by wakystuf** [comment]
These all seem fine to me. A few thoughts and questions:
* I think Cobbs worked on the colors at some point, though I'm not certain. Maybe see if he has any suggestions there; if he's willing to help, the guy is a gold mine of info about what has and hasn't worked in the past.
* I'm fine adding more tips, but I think Cobbs did a great job already with the ESG ones. Feel free to post any that you think should be changed and/or added.
* What do you mean regarding the minors? I'm not sure I understand what exactly you would change, but I'm probably fine with it?

**Comment by Tat011** [comment]
minors have a home, in vanilla there is only one in their pool so for example baghabas always spawn with an atoll home, but with my thing they could spawn with fertiles that fit besides just atoll

**Comment by Arpharnator** [comment]
colors i agree
names i agree
tips i agree
not sure if it's necessary to start changing weights for stuff to appear, we already have balanced galaxy gen changing things anyways

**Comment by Arpharnator** [comment]
also @wakystuf some tips are outdated

**Comment by Tat011** [comment]
also can specific special node types be given specific name pools?
like is that a thing possible to do?

**Comment by Arpharnator** [comment]
don't think so
if it's possible you're gonna have to dig i think into the Mapping

**Comment by Provolonage** [comment]
I think almost all of these are real tat, minor do have set home planets, they always spawn on the same planet, theres a colors option that changes the colors alot in settings, new node names are fine go for it, the problem with tips is they will be outdated every month but go for it, and outside of hot and cold im p sure every planet can spawn on basically any star, ive gotten gas cold on all hot systems and stuff like that, but im not opposed if it isnt actually like this.

**Comment by Tat011** [comment]
> minor do have set home planets, they always spawn on the same planet, 

Yeah that's what i wanted to change

> theres a colors option that changes the colors alot in settings

Doesn't change how many options you have at any given time

> outside of hot and cold im p sure every planet can spawn on basically any star, ive gotten gas cold on all hot systems and stuff like that, but im not opposed if it isnt actually like this.

I've looked at the code, Gas giants dont care about star temperature (even though they should)

**Comment by wakystuf** [comment]
Hmm, interesting. I'm not sure where the minor homes thing lives in the code, but if you've found it and want to give them more variety then go for it.

**Comment by wakystuf** [comment]
@Tat011 I'm closing this for now given your departure from the server, but feel free to reopen if you resume working on it. I'm generally fine with these changes.
