### ISSUE TITLE
AI changes

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1367]
The AI is now unable to access anomaly enhancement, reduction and moon discovery. The reason for that is that AI would get stuck in a loop trying to build these every turn for no good reason. Disabling and discarding was necessay.
Slightly improved ratio AI bonus on higher difficulties.
Greatly reduced rooting bonus, the AI would otherwise finish rooting in 1 turn with a single root ship.
Removed any sort of AI damage reduction when fighting pirates, as that completely removed the point of pirates against AI.
Greatly reduced vaulter colonisation bonus, that made them extremely cancer to play against with the 0 turn argosy.
Removed all bonus colonisation cap bonuses from AI except on endless where the AI gets +2.
Higher AI difficulties are now capped at 1 behemoth max. The AI cannot use them properly and will waste a very large amount of industry building these when it could be doing something else.
Reduced the flat bonus AI get on Impossible and Endless.

**Comment by Kil10naire** [comment]
praise be no more 1 turn unfallen entwining
