### ISSUE TITLE
Trade Tweaks

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1369]

**Comment by wakystuf** [comment]
* Tripled base dust yields from population and system level
* Reduced by 60% the benefit from trade route length
* Increased Trade Agreement upkeep from flat 50 to the following formula:
50 + 35 x (# Trade Co's) + (Empire Pop)

OLD formula
System Trade Value = ([System Level] x [System Pop] x 10% + 5) x [System Trade Income Modifier]
Trade Route Value = ([HQ System Trade Value] + [Subsidiary System Trade Value]) x (1 + 10% x [Route Length]) x (1 + 10% x [# Freighters])
Trade Co Value = 150 + [SUM of all Trade Route Value] x (0.75 + ([Trade Co Level] / 35) ^ 0.75)

NEW formula
System Trade Value = ([System Level] x [System Pop] x 30% + 5) x [System Trade Income Modifier]
Trade Route Value = ([HQ System Trade Value] + [Subsidiary System Trade Value]) x (1 + 4% x [Route Length]) x (1 + 10% x [# Freighters])
Trade Co Value = 150 + [SUM of all Trade Route Value] x (0.75 + ([Trade Co Level] / 35) ^ 0.75)

**Comment by wakystuf** [comment]
Note that those formulae aren't perfect, since a) they don't account for the flat dust and science from resource deposits and b) there are some other minor things going on in the code that I can't directly observe and therefore can't precisely quantify.

**Comment by Kil10naire** [comment]
I'll make sure to mention the things brought up in your final comment in the changelog
