### ISSUE TITLE
Change growth formula to scale with pop

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#137]
(300 + (Population * 5)) * Game Speed, for Vodyani (1200 + (Population * 10)) * Game Speed

**Comment by captaincobbs** [comment]
(180+ (Population * 40)) * Game Speed, for Vodyani (1000 + (Population * 60)) * Game Speed

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/103411806-3b68a200-4b72-11eb-95e8-7ced3ae766fc.png)

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/103411952-4112b780-4b73-11eb-8999-841207b932f2.png)

**Comment by Arpharnator** [comment]
don't mind the fact that is it full, I'm just showing that base value is 110 with this
![image](https://user-images.githubusercontent.com/49691625/103426077-0e8aae00-4bb7-11eb-8ec1-d630fb5fed14.png)

**Comment by Arpharnator** [comment]
I think the new foodline is necessary to play with +40 per pop, becaue otherwise big systems can never grow by themselves, and seeding becomes necessary.

**Comment by Arpharnator** [comment]
works, but you can get wonky numbers at game start

**Comment by wakystuf** [comment]
It looks like the formula was settled on (305+ (Population * 10)) * Game Speed; is that correct? I looked at it on Normal speed; not sure if that messes anything up

**Comment by wakystuf** [comment]
Oh, and for Vodyani it looks like  (1220+ (Population * 40)) * Game Speed

**Comment by captaincobbs** [comment]
Normal: 300 + (5 * Population) * Game Speed
Vodyani: 1200 (20 * Population) * Game Speed

**Comment by wakystuf** [comment]
Did we ever figure out why the formulae don't match what is actually displayed in the game?

**Comment by captaincobbs** [comment]
It's something to do with rounding

**Comment by wakystuf** [comment]
Hmm...but the numbers I was seeing were different by more than +/-1. On Normal I was seeing 335 with 3 pop, or 305 with 3 pop, which would suggest a formula in which both the slope and intercept are different than what you'd listed (IE, it implies 305+pop*10 on Normal).

Maybe I'm missing something (totally possible), but I find it hard to understand how rounding could create a different of 335 vs 315 with 3 pop?

**Comment by captaincobbs** [comment]
I agree but it's not big enough for me to want to stress about it. I've already spent a few weeks trying to search for the problem and given up.

**Comment by wakystuf** [comment]
Haha, OK. 

In that case I'd propose simply documenting on the wiki the way the game interprets it? Presumably there's code somewhere that modifies the formula you input such that the (unobserved/hidden) "final" formula is the following:
(305 + 10 * Population) * GameSpeed

**Comment by captaincobbs** [comment]
That'd work. I think something is up with how it's using the $Population variable now that I look at it more, but I have no way to check and see if this is true,

**Comment by wakystuf** [comment]
Great. If you ever figure it out, I'd be curious to know the answer, but for now I've updated the wiki and will mark as Documented.
