### ISSUE TITLE
Pass laws from 5 parties Deed still requires 6

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1387]
Likely needs the quest objective to be adjusted

**Comment by captaincobbs** [comment]
QuestDefinitions[Deeds].xml, change $LawObjective on Ln 501 from 5 to 4?

**Comment by wakystuf** [comment]
No, that's just the localization (which is how I also thought it worked originally). The problem is that in lines 532 through 561 it's checking with a Parallel CompletionPolicy="All" that each party's path is satisfied. So I need to rebuild that somehow to be a numerical evaluation (may require adding a variable into ClassSenate or something for the # of parties; I'm not quite sure).

**Comment by captaincobbs** [comment]
My best idea then is to make the simdescs "LawPolitics0x" give +1 to an empire property of how many different party's laws are passed, then make an interpreter expression and replace the parallel tag with just something that checks for that expression

**Comment by wakystuf** [comment]
I figured out how to dupe the parallels and make this work. Should now be fixed
