### ISSUE TITLE
Law changes

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1388]
Roughing It: 
- [x] Loses -10% Anomaly Reduction industry cost per turn up to 50% (15% up to 60% for republic)

All Hands Dictum:
- [x] Gains -10% Anomaly Reduction industry cost per turn up to 50% (15% up to 60% for republic)
- [x] Loses +2% Industry & +2% Science per Population Types
- [x] Gains +10% Industry / Dust / Science on System per Terraformed Hot / Temperate / Science planet respectively
- [x] Horatio variant is no longer needed

Blood From Stones:
- [x] Gains x5 Ownership Bonus from Special Nodes on Systems
- [x] New Unfallen Variant: 2x Ownership from Special Nodes on Systems
- [x] New Umbral Choir Variant: 2x Ownrship from Special Nodes on Beacons
- [x] Vodyani Variant: 5x Ownership Bonus from Special Nodes on Systems

**Comment by Arpharnator** [comment]
Does this mean that roughing it increases the cost of anomaly enhancement?

also doesn't vodo want to still get the bonus essence

**Comment by FluffiestPrincess** [comment]
> 10% Anomaly Reduction industry cost per turn up to 50% (15% up to 60% for republic)

This is bugged. #1398
