### ISSUE TITLE
Geothermic Activity and Strange Fossils anomalies do not make sense lore-wise

### ISSUE THREAD

**Issue by FluffiestPrincess** [captaincobbs/ESG-Mod#1395]
Currently, Geothermic Activity is +1 industry/pop, -1 science/pop. As a lore writer, there's no reasonable way I can explain why geothermal activity should reduce a planet's scientific output. Change it to -happiness or -food or something, please.

Strange Fossils is +2 industry/pop, +1 dust/pop. I can probably come up with SOMETHING such as fossils containing nanomaterials that are used in robot construction, if you can't think of anything to change it to.

**Comment by captaincobbs** [comment]
The volcanic and seismic activity could be affecting sensors and telescopes

Strange fossils uhhh, I think it'd make more sense to change the industry to influence.

**Comment by wakystuf** [comment]
Geothermic activity I think is playing on the overall theme of hot --> indy, but less science. I've always kind of wondered why a lava planet is incapable of producing any science (surely there are some experiments that can be conducted), but I think that one is fine--the "erratically messing with sensors" concept seems fine.

For Strange Fossils, I'd prefer to avoid influence; probably could shift the industry to science instead (fairly easy to explain how unusual fossils could be scientifically useful)
