### ISSUE TITLE
Unable to see Space Battle

### ISSUE THREAD

**Issue by ghost** [captaincobbs/ESG-Mod#1410]
Hello,

With this mod activated, all space battle pass direct to the resultat independantly to the trigger to see or not the battle.
It's intended or not ?

**Comment by captaincobbs** [comment]
Can you elaborate? Sorry for the late reply. Screenshots, video recordings, and saves would be appreciated.

**Comment by NoProblemWithThisAcc** [comment]
He's got the battle watching setting off?

**Comment by wakystuf** [comment]
That was my guess as well. If we don't receive some kind of update/evidence in the next couple of days then I'll close this issue.
