### ISSUE TITLE
Pop Migration Minor Action Badly Bugged (Vanilla bug)

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1418]
The pop migration action does not remove pop from the minor civ so can be spammed infinitely
In the code there is already a value for PopulationCount, but upon experimentation this only controls the # of pop sent (it will send >1 pop on the civilian ship if the value is set >1). It still does not reduce the minor civ pop

Fix is to convert everyone to the MP action so they get 300 MP instead of a unit of pop. This action properly reduces the pop of the minor civ.

**Comment by NoProblemWithThisAcc** [comment]
This is better than free pop. But what about 'ratio? Can we give Gene Splicers the ability to clone any minor civ's pop that they are friends with? It means you don't get the free 300 food (you have to clone them from your own), but it saves some travel time.

Is that unlock easy enough to check for and do?
