### ISSUE TITLE
"Forced Trade Agreement" doesn't attempt to create trade routes, while still consuming influence

### ISSUE THREAD

**Issue by X3n0n3x** [captaincobbs/ESG-Mod#1431]
I'm not yet sure what the possible factors are for this, but I've had a game where anytime I used "Force Trade Agreement", no trade routes are attempted to be connected between my Trade HQs and the other empire's trade Subsidiaries. In fact no new "External trading subsidiaries" show up at all in the trade window when doing this.

It's not related to blockades / lack of access as I have full visibility of the potential trade routes, and if I instead reload the same turn to get the empire to agree to a "normal" Trade Agreement, the trade routes connect as normal and get displayed in the trade window.

It doesn't appear to be just due to the other empire not being able to afford the influence cost, as I can replay the same set of turns where the other empire was able to afford having a "normal" trade agreement with me, and if I reload and instead enact a "forced trade agreement", no new trade routes are created/displayed in the trade window, while the "forced trade agreement" remains in effect (and continues to cost me influence). In fact on one occasion where I let a non-functional "forced trade agreement" stay enacted for many turns, at one point it automatically got canceled due to the other empire not having enough influence to afford it, meaning they were able to afford it all the other turns it was enacted but not working.

Briefly mentioned on the discord here:
https://discord.com/channels/667851020583305239/766177008936812566/1167332315756769280

I also have some relevant save files if it's useful.

**Comment by captaincobbs** [comment]
fixed in [#42c3376](https://github.com/wakystuf/ESG-Mod/pull/1433/commits/42c3376799f0dc0fec5dd82b87de9314bb080933)
