### ISSUE TITLE
Patch Preview -- Pop FIDSI bonuses do not apply to planets in spite of showing that they do

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1434]
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/90c44f34-83d5-40b2-8695-862f9eb81e74)
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/c52a36b3-9bd4-4b2d-ad8d-1a89bed67a52)

**Comment by wakystuf** [comment]
Fixed, I believe. That said, the graphic where shows the icon of each pop is now simply "Population" which is less cool, but at least the calculation now works
