### ISSUE TITLE
Patch Preview -- Class Innate skills for heroes don't display properly

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1436]
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/e66aa784-7cea-4acb-9e7f-fa7e2eb78b89)
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/479e425a-e1c5-445b-8fb0-2c4db70fad5d)

**Comment by wakystuf** [comment]
Fixed
