### ISSUE TITLE
Patch Preview -- Ships have 0 hp max, entering battle causes freeze

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1437]
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/9993c263-225c-45cc-a0b2-03eab03a05da)
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/87476e5d-2566-4f05-9680-eaab228eea43)

**Comment by wakystuf** [comment]
Good catch; I believe I just fixed this one. When Cobbs did the initial merge, he added ClassSection, which we don't need, and somehow included certain random properties from ClassShip (related to trade value) but left out others (like health).

Why, @captaincobbs why??

**Comment by Arpharnator** [comment]
this works

**Comment by captaincobbs** [comment]
> Good catch; I believe I just fixed this one. When Cobbs did the initial merge, he added ClassSection, which we don't need, and somehow included certain random properties from ClassShip (related to trade value) but left out others (like health).
> 
> Why, @captaincobbs why??

Kill yourself

**Comment by Arpharnator** [comment]
Not very professional innit

**Comment by wakystuf** [comment]
Indeed.
Step 1: Break things
Step 2: Make me fix the broken things
Step 3: Grump at me for successfully fixing the broken things
Step 4: Profit?
