### ISSUE TITLE
Patch Preview -- Techs with duplicate unlocks

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1438]
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/a2d7ea5f-ce90-49fe-89e8-ec60bc92bc9b)
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/3f79b78e-fb51-4f6f-bd93-91f06630c5cd)

**Comment by wakystuf** [comment]
Yes, @captaincobbs knows that he needs to fix this one--I think the patch eliminated Vacuum Protection, but we are keeping it due to the cloaking improvement that we added. I think it should be as simple as adding the old vanilla version of Adamantian Alloys into ESG

**Comment by wakystuf** [comment]
Fixed
