### ISSUE TITLE
Double check Craver partial depletion mechanics

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1440]

**Comment by wakystuf** [comment]
This was broken and is now fixed. However, the Cravers are terrible in the patch, which is a separate issue that will be harder to fix. I will create a new Issue for that

**Comment by Arpharnator** [comment]
wdym cravers are terrible
is there some unseen thing i am not aware of

**Comment by wakystuf** [comment]
See this:
#1454
