### ISSUE TITLE
Patch Preview -- Behemoth not displaying Special Node effect when orbiting but applying properly

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1446]
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/dbdc9d19-0612-4f7d-9896-95d87299d526)
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/251ccc3a-8739-4039-9dfd-7f1fd1c6c9f4)
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/04712b70-050e-4117-8106-ecb3f6d857ba)

**Comment by wakystuf** [comment]
Is the problem that it's not actually giving the strats? It looks like that's showing up in the GUI in the 2nd picture

**Comment by Arpharnator** [comment]
the problem is that it's not showing by how much it's increasing the FIDSI yield of the special node

**Comment by wakystuf** [comment]
Oh, got it. So the 843.8 includes both, but it isn't breaking them down?

**Comment by Arpharnator** [comment]
I mean on this photo, before it would display there iirc, like +125%
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/56063692-460a-460b-8ddb-763b6e68518d)

**Comment by captaincobbs** [comment]
This has been an issue for a long while, there's not really an easy way to fix it

**Comment by captaincobbs** [comment]
wtf I'm not fixing it, I'd have to decompile the game, we're just going to have to live with it

**Comment by wakystuf** [comment]
Haha I'll just close it then
