### ISSUE TITLE
Patch Preview -- Neutron Star system influence bonus not working

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1447]
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/7cecde57-8086-45fa-bd55-868ba6316d71)
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/13376a92-dcb0-4848-b4cb-08f8b0463abe)

**Comment by wakystuf** [comment]
Ah yeah this is the sort of random per pop bonus I was worried about. @captaincobbs ?

**Comment by captaincobbs** [comment]
This is a system-added bonus not a a planet one

**Comment by captaincobbs** [comment]
Confirmed working
![image](https://github.com/wakystuf/ESG-Mod/assets/16710532/fbaf78e9-9048-4db0-b048-876a943d4f21)

All the special node effects are intentionally targeting ClassSystem instead of ClassPlanet
