### ISSUE TITLE
Patch Preview -- New Imperious personality trait lacking loc

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#1449]
![image](https://github.com/wakystuf/ESG-Mod/assets/49691625/4ea19071-2654-4882-8735-fd199dfdd548)

**Comment by wakystuf** [comment]
Can you make sure you were using the latest version when you tested this? It looks like Cobbs added it earlier today

**Comment by captaincobbs** [comment]
Someone accidentally deleted it so I had to add it back
