### ISSUE TITLE
Influence Conversion is in T4 instead of T2 like the patch

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1459]
Do we want to have parity with vanilla, or keep it where it is?

**Comment by Arpharnator** [comment]
can you even afford influence conversion at T2

**Comment by wakystuf** [comment]
Yeah, I think @Arpharnator makes a good point.
I'd probably leave it at T4, but it's also a mostly-not-real mechanic, so I don't care very much.

**Comment by Tat011** [comment]
Can't it be moved to T3? that way it's not an early game tech but also not a late game one.

**Comment by captaincobbs** [comment]
> Yeah, I think @Arpharnator makes a good point. I'd probably leave it at T4, but it's also a mostly-not-real mechanic, so I don't care very much.

Darn if only there was a way to.. affect the cost somehow.. make it.. cheaper...

**Comment by wakystuf** [comment]
The cost isn't why it's non-real; it's because people will simply declare war (and it's a bad idea to make it almost impossible to declare war, etc)

**Comment by captaincobbs** [comment]
> The cost isn't why it's non-real; it's because people will simply declare war (and it's a bad idea to make it almost impossible to declare war, etc)

That's the point of the mechanic, to make you debate whether it's worth it to just let them take your system or go to war over it
