### ISSUE TITLE
Buff Riftborn population collection 3: 50% current movement point cost and -50% Terraformation Cost

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#146]
Riftborn can now infinitely travel through wormholes, make it so that wormhole travel consumes %25 of max movement point rather than the remaining. Riftborn terraformation cost reduction doesnt work either. Unlocking the final pop collection trait doesnt change the terraformation cost.

**Comment by Arpharnator** [comment]
Works.
