### ISSUE TITLE
Some bug related to relics and approval

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#1462]
![image](https://github.com/wakystuf/ESG-Mod/assets/79942510/c7ce0b29-0c10-4f0d-a553-8a85664666a6)

**Comment by captaincobbs** [comment]
Not interested in fixing this

**Comment by captaincobbs** [comment]
This is a vanilla bug related to not updating the UI when toggling the relic, you should still have the appropriate approval bonuses despite how it looks.
