### ISSUE TITLE
Sophons Quest Chapter 2.3-Science "A Probe Alone" does not conclude if the ENFER ship is dragged and dropped into Garrison

### ISSUE THREAD

**Issue by 107g** [captaincobbs/ESG-Mod#1469]
In the Sophon's main quest line, Chapter 2.3 of the Science variant know as 'A Probe Alone', a bug occurs if the ENFER ship, that needs to be placed into any of the player's hangar, is drag-and-dropped into the garrison (How ESG calls the Hangar) instead of selecting the fleet and clicking the GARRISON button.

When that bug occurs, the quest does not conclude and can no longer be concluded for the rest of the playthrough, blocking the Sophons player in the quest storyline.

As shown below, I am about to drop the ship into the Hangar of the Omdor system:
![image](https://github.com/wakystuf/ESG-Mod/assets/51477716/13c42a3a-7d27-4338-9acf-c08f5fb36c86)

When I do, the quest does not conclude:
![image](https://github.com/wakystuf/ESG-Mod/assets/51477716/073b01bd-00ca-4abb-ae7e-b78568200f9b)

If I launch the ship and try to "garrison" it back right away (using the GARRISON button, which would work if I did that in the first place), it will still not work. This effectively 'breaks' the campaign unless I load a previous save file.

I tested this bug on vanilla ES2, dragging and dropping does work on the un-modded version.

**Comment by 107g** [comment]
Did some digging in the `QuestDefinitions[Sophons].xml` file. Turns out, in vanilla, the quest completion trigger is done by garrisoning any ship with the `ModuleExplorationQuestSophons` Module, which is meant to be unique and specifically created for the ENFER ship. However, in ESG, this module is buildable in player made ships (it's the Sophon FreeMove!). 

As a result the quest completion trigger had to be modified to prevent players accidentally completing the quest by garrisoning any ship using the Sophon FreeMove. Instead, the quest completion trigger is done by identifying the Fleet ID that is disbanded. If the disbanded fleet ID matches the Fleed ID of the ENFER ship, the quest is completed. 

However, if the ENFER ship _itself_ is disbanded (and not the fleet), via drag and drop, the trigger does not occur (you disbanded a ship, not a fleet). If the player launches the ENFER ship again, it will do so under a brand new fleetID, thus locking the questline.

**Comment by captaincobbs** [comment]
Could apply a unique tag to the ship instead, doesn't seem too hard. I'll look into it

**Comment by captaincobbs** [comment]
Further investigation reveals this is also a problem with CraversQuest-Chapter1.2, I'm working on a fix for it now
