### ISSUE TITLE
Slugs & Laser cannons are mounted backwards on Pirate/Scavenger Minor ships

### ISSUE THREAD

**Issue by 107g** [captaincobbs/ESG-Mod#1473]
In ESG, slugs and laser cannons (non-beam) are mounted backwards on the Pirate/Scavenger family of Minors' ships:

![BackwardsTopTurret](https://github.com/wakystuf/ESG-Mod/assets/51477716/6d33efc7-e209-4c88-b02f-b94a7a7f0d28)

![BackwardsSideTurret](https://github.com/wakystuf/ESG-Mod/assets/51477716/43c29719-0c45-4b63-9de0-2c63ad82dfea)

Also applies to the Medium-sized Hull:
![BackwardsTopTurretHunter](https://github.com/wakystuf/ESG-Mod/assets/51477716/f2343c56-95f2-477c-ac35-c02f1179114a)

![BackwardsSideTurretHunter](https://github.com/wakystuf/ESG-Mod/assets/51477716/3fbbc2c7-664d-4b83-b3ec-64cd3cf2a485)

~~I can confirm this bug does not occur in Vanilla.~~ Edit: This issue is a Vanilla bug for the higher-grade turrets

**Comment by 107g** [comment]
After some more research, I realize this is actually a Vanilla bug. The bug occurs on higher-grade turrets (grade 3 and up).

**Comment by captaincobbs** [comment]
Can you describe the issue in more detail?

**Comment by 107g** [comment]
It's fairly small on the screenshots unfortunately. 

When designing a new ship with the Raider or Pillager Hulls (i.e. the Pirate/Scavenger family of Minor ships), slug and laser cannons turrets' models are inverted on the ship. You should see the gun sticking outwards just like the beam turrets do, but instead they point inward (for the side guns) or backwards (for the top mounted guns).

**Comment by captaincobbs** [comment]
Looked at this a bit and it appears to be a C# issue and not an XML one, so I'll note it down in case I get rehired by Amplitude but either way this isn't something ESG can fix.
