### ISSUE TITLE
CTDs, Errors & Exceptions on "Maximum" modifier on Development-1-5-1 version

### ISSUE THREAD

**Issue by GitKopfkino** [captaincobbs/ESG-Mod#1489]
I know it's in development, so I'm just trying to help. The mod has always been awesome!
Notes: I've reset the game and all the settings, and I am only loading ESG mod.

The game doesn't seem to recognize or accept any "Maximum" modifier.

Affected files:
- SimulationDescriptors[Academy].xml
- SimulationDescriptors[Planet]

**LOG 01:**
17:48:35:523 -- Default -- STACK -- Loading plugin files for database of type 'Amplitude.Unity.Simulation.SimulationDescriptor'...

17:48:35:523 -- Data -- STACK -- The database of type 'Amplitude.Unity.Simulation.SimulationDescriptor' failed to load the file '*\Simulation\SimulationDescriptors[Academy].xml'. The following exception was raised: System.InvalidOperationException: There is an error in XML document. ---> System.InvalidOperationException: 'Maximum' is not a valid value for Amplitude.Unity.Simulation.SimulationModifierDescriptor+ModifierOperation. at System.Xml.Serialization.XmlSerializationReaderInterpreter.GetEnumValue (System.Xml.Serialization.XmlTypeMapping typeMap, System.String val) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.GetValueFromXmlString (System.String value, System.Xml.Serialization.TypeData typeData, System.Xml.Serialization.XmlTypeMapping typeMap) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadAttributeMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement (System.Xml.Serialization.XmlTypeMapElementInfo elem) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement (System.Xml.Serialization.XmlTypeMapElementInfo elem) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadListElement (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, System.Object list, Boolean canCreateInstance) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot (System.Xml.Serialization.XmlTypeMapping rootMap) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot () [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in :0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.Stream stream) [0x00000] in :0 at Amplitude.Unity.Framework.Datatable`1[Amplitude.Unity.Simulation.SimulationDescriptor].LoadFromFile (System.String path, Amplitude.Xml.Serialization.XmlAttributeOverride[] overrides, Amplitude.Xml.Serialization.XmlExtraType[] extraTypes) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.Stream stream) [0x00000] in :0 at Amplitude.Unity.Framework.Datatable`1[Amplitude.Unity.Simulation.SimulationDescriptor].LoadFromFile (System.String path, Amplitude.Xml.Serialization.XmlAttributeOverride[] overrides, Amplitude.Xml.Serialization.XmlExtraType[] extraTypes) [0x00000] in :0

17:48:35:523 -- Default -- STACK -- The database of type 'Amplitude.Unity.Simulation.SimulationDescriptor' has failed to load the file '*\Simulation\SimulationDescriptors[Academy].xml'.

(erased lines with "Maximum", reload mod)
**LOG 02:**
18:07:40:732  -- Default  -- STACK  -- Loading plugin files for database of type 'Amplitude.Unity.Simulation.SimulationDescriptor'...

18:07:40:732  -- Default  -- STACK  -- The database of type 'Amplitude.Unity.Simulation.SimulationDescriptor' failed to load the file '*\Simulation\SimulationDescriptors[Planet].xml'. The following exception was raised: System.InvalidOperationException: There is an error in XML document. ---> System.InvalidOperationException: 'Maximum' is not a valid value for Amplitude.Unity.Simulation.SimulationModifierDescriptor+ModifierOperation. at System.Xml.Serialization.XmlSerializationReaderInterpreter.GetEnumValue (System.Xml.Serialization.XmlTypeMapping typeMap, System.String val) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.GetValueFromXmlString (System.String value, System.Xml.Serialization.TypeData typeData, System.Xml.Serialization.XmlTypeMapping typeMap) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadAttributeMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement (System.Xml.Serialization.XmlTypeMapElementInfo elem) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement (System.Xml.Serialization.XmlTypeMapElementInfo elem) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadListElement (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, System.Object list, Boolean canCreateInstance) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot (System.Xml.Serialization.XmlTypeMapping rootMap) [0x00000] in :0 at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot () [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in :0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.Stream stream) [0x00000] in :0 at Amplitude.Unity.Framework.Datatable`1[Amplitude.Unity.Simulation.SimulationDescriptor].LoadFromFile (System.String path, Amplitude.Xml.Serialization.XmlAttributeOverride[] overrides, Amplitude.Xml.Serialization.XmlExtraType[] extraTypes) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader) [0x00000] in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.Stream stream) [0x00000] in :0 at Amplitude.Unity.Framework.Datatable`1[Amplitude.Unity.Simulation.SimulationDescriptor].LoadFromFile (System.String path, Amplitude.Xml.Serialization.XmlAttributeOverride[] overrides, Amplitude.Xml.Serialization.XmlExtraType[] extraTypes) [0x00000] in :0

18:07:40:732 -- Default -- STACK -- The database of type 'Amplitude.Unity.Simulation.SimulationDescriptor' has failed to load the file '*\Simulation\SimulationDescriptors[Planet].xml'.

(erased lines with "Maximum", reload mod)
-> Loads Successfully without crashing

**Comment by captaincobbs** [comment]
Question, you're using the most recent version of the game yes? The Operation="Maximum" lines you are referring to are just carry-overs from the base game.

**Comment by captaincobbs** [comment]
Also, your help is very much so appreciated :)

**Comment by captaincobbs** [comment]
This issue is only present with old versions of the game, I've just confirmed. Unfortunately not relevant and not a whole lot we can do about it. You'll have to use 1.5 if you wish to play no Pre-ReAwakening builds.
