### ISSUE TITLE
T3 Luxuries remain undiscoverable even with the correct technology unlocked

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1494]
Link to report [here](https://discord.com/channels/227126593754103810/230330494120755200/1254501998779301919)

**Comment by wakystuf** [comment]
I believe this was confirmed to be a false alarm based on incorrect galaxy settings, but feel free to post a screenshot (for some reason the Discord link didn't work for me)

**Comment by captaincobbs** [comment]
Ah phew
