### ISSUE TITLE
Craver Ships causing save corruption

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#1495]
If you have any ideas on how to fix I would greatly appreciate that.

I first got this report on May 10th or so of 2024, meaning it is likely a bug that is either incredibly rare or was introduced by the April 30th or May 1st updates.

This includes:
- Craver Depletion Fix
- Planet Breakdown Tooltip Fixes
- A whole bunch of other minor stuff

However, none of these were explicitly related what I believe is the most likely cause so I'm genuinely not sure what the issue might be.

All diagnostics I have found of sessions before this issue occurs have this exact set of errors:
![image](https://github.com/wakystuf/ESG-Mod/assets/16710532/d227d0f2-b4db-42e9-965c-d6033f1a3903)

Next, comes a report from @Tat011 saying it only occurred in games he's played where Cravers are present, and then a separate report from a random user on Discord that mentions it occurred the turn after he fought the Craver quest fleet, with "my own quest fleet", user could not provide save to verify the claims though as it had been overwritten by autosave.

Next, comes this report on steam:
![image](https://github.com/wakystuf/ESG-Mod/assets/16710532/b269a612-aceb-43d1-8e51-e96469dc72f3)

If anyone is willing to look into this, or has additional information about it, I would greatly appreciate it. I've done my best to collect information and look into what may be causing the issue but I genuinely can't tell.

Lastly, here is the error that occurs when loading a broken save game, not helpful but potentially relevant.
![image](https://github.com/wakystuf/ESG-Mod/assets/16710532/1cc65ae3-749c-4367-8c55-fa42ddd3e3cc)

**Comment by wakystuf** [comment]
Hmm...is it possibly related to the tweak to the Craver quest ship? I believe that was included in the May 1st update, right?

The only other thing I can think of is that it's somehow related to the big merge update to ship ranks; don't the Cravers have some slight innate differences in their ships (less health, cheaper, maybe more XP)? That could be part of it too.

**Comment by Tat011** [comment]
The quest ship for sure breaks the game, both an MP and SP game i've played this ship was seemingly the source of an error. Now if its also causing the save errors idk.

**Comment by captaincobbs** [comment]
> Hmm...is it possibly related to the tweak to the Craver quest ship? I believe that was included in the May 1st update, right?
> 
> The only other thing I can think of is that it's somehow related to the big merge update to ship ranks; don't the Cravers have some slight innate differences in their ships (less health, cheaper, maybe more XP)? That could be part of it too.

What was this tweak?

**Comment by captaincobbs** [comment]
Oh, I remember, I think I know what the issue is. Can someone test whether https://github.com/wakystuf/ESG-Mod/commit/81a1d16dd309fc31e9fc463cc2a471753555140d works? At the very least, it won't make anything worse and should be good to immediately merge.

**Comment by Zingybird** [comment]
i tested both questlines and  reloaded the saves it works or its fixed if thats cool with yall

**Comment by captaincobbs** [comment]
Thanks Zingy, appreciate it. I'm gonna consider this finished then as people who had previous corrupted saves say they are now working.
