### ISSUE TITLE
Game crashed while loading the mod

### ISSUE THREAD

**Issue by tuan1515** [captaincobbs/ESG-Mod#1543]
I have downloaded from the  [Development-1-5-1] branch. 
[Diagnostics - 2024'07'25 @1343'19''.txt](https://github.com/user-attachments/files/16371697/Diagnostics.-.2024.07.25.%401343.19.txt)

**Comment by captaincobbs** [comment]
Hello, use version 1.5 instead of 1.5.1 (1.6), as you are using an older version of the game and the newest version of the mod does not support that.
