### ISSUE TITLE
I demand Frenny gets demoted from moderator.

### ISSUE THREAD

**Issue by Tat011** [captaincobbs/ESG-Mod#1550]
The reason i'm posting here is cuz it’s the only place were can delete my comments (which he just did) and i wasn't gonna msg everyone relevant 1 on 1.
Frenny is consistently rude to people, especially me who he treats like trash for no reason.
By his own admission he doesn't even play the mod and he doesn't moderate at all.
He barely even talks on the server and when he does it's to argue about how ESG is bad.
I am NOT going to tolerate any more insults from this guy, i don't deserve to be demeened and treated like i'm a stupid bad faith liar.
Freny being mod also means he can do whatever he wants and no one can tell him shit, a fact he abuses.
I stopped working on more polititcal traits specifically because he kept getting aggressive whenever i brought it up, how is this acceptable?
Being demoted is the bare minimum btw, he should be suspended.

**Comment by captaincobbs** [comment]
Resolved

**Comment by Provolonage** [comment]
based
