### ISSUE TITLE
Horatio/United Empire/Umbral Choir faction quests not triggering

### ISSUE THREAD

**Issue by mdelah** [captaincobbs/ESG-Mod#1562]
As of the latest published Steam release (8 Sep, which appears to correspond to commit [84ee499](https://github.com/wakystuf/ESG-Mod/commit/84ee499c74c694298872451f87c5b3cf546ad7dc)), the main questlines for the Horatio and United Empire factions do not trigger. There are a pair of errors being regularly logged that seem related:

````
Exception caught while executing query (type: Amplitude.Query.Xml.XmlQueryAny, expression: 'Amplitude.Query.Xml.XmlQueryAny') for variable (name: '$RebelPlanet') of quest UE_Quest-Chapter1.1. 
Object reference not set to an instance of an object 
at CheckVariables in :line 0
at IQuestManagementService.TryTriggerQuest in :line 0
at IQuestManagementService.TryTriggerQuests in :line 0
at GameServer_StateChange in :line 0
at FiniteStateMachine_StateChange in :line 0
at FiniteStateMachine_StateChange in :line 0
at OnStateChange in :line 0
at RefreshState in :line 0
at Update in :line 0
at Update in :line 0
at Update in :line 0
at Update in :line 0
at LateUpdate in :line 0

Exception caught while executing query (type: Amplitude.Query.Xml.XmlQueryAny, expression: 'Amplitude.Query.Xml.XmlQueryAny') for variable (name: '$QuestPlanet') of quest HoratioQuest-Chapter1.Part1-Summary. 
at CheckVariables in :line 0
at IQuestManagementService.TryTriggerQuest in :line 0
at IQuestManagementService.TryTriggerQuests in :line 0
at GameServer_StateChange in :line 0
at FiniteStateMachine_StateChange in :line 0
at FiniteStateMachine_StateChange in :line 0
at OnStateChange in :line 0
at RefreshState in :line 0
at Update in :line 0
at Update in :line 0
at Update in :line 0
at Update in :line 0
at LateUpdate in :line 0
````

From what I can tell the issue seems to have started with a set of commits from Jul 28 (in particular the preceding commit [ae08fc6](https://github.com/wakystuf/ESG-Mod/commit/ae08fc6dc3b17a84bba943a490da49f26d5c840d) seems fine).

Hope this helps track down the problem.

**Comment by Tat011** [comment]
Acording to Merm it also happens with UC.
Someone should take the time to solve this cuz it's a pretty serious problem.

**Comment by mdelah** [comment]
@Tat011 After a little more digging today I'm fairly sure this is connected to [f60cf67](https://github.com/wakystuf/ESG-Mod/commit/f60cf67f2e80bccfdc174f95896749108523f0de), which somehow interferes with the engine's ability to spawn quest-related systems (Traitor's Reach for UE, the one you need to raise approval in as Horatio, I don't play with the Umbral Choir DLC but judging by the game files there's a special quest-related system in there too).

Backing out the `WorldSettingDefinitions.xml` updates fixes it.

**Comment by Tat011** [comment]
Ok after a bunch of testing it seems that it's a double whammy of:
-QuestNodesQuantity/QuestNodesPerMajorFaction need IsolatedNodesQuantity to be at least matching in number cuz they dont actually spawn quest nodes and instead rely on IsolatedNodesQuantity because of course.
-Quest nodes can be converted into special nodes by the generator because we live in a society.
