### ISSUE TITLE
T4 Craver Skill "Endless Consumption" does nothing.

### ISSUE THREAD

**Issue by Reithan** [captaincobbs/ESG-Mod#1564]
Tried moving governor, no dice.
No fids bonus on any planet shown, and no additional depletion seems to be applied. Skill seems entirely non-functional.

**Comment by Reithan** [comment]
Actually it does appear to be adding the +8 depletion, but it just doesn't add the +12 FIDS. :(
![image](https://github.com/user-attachments/assets/7e99a9e5-6d6a-41fb-ba33-a97d6dface32)
![image](https://github.com/user-attachments/assets/21e29dec-bc06-490f-8268-ffba517ce511)
![image](https://github.com/user-attachments/assets/73e83c41-d460-4008-9e29-736a88011177)
I see the timer to depletion is shortened, which tracks with 1+8 depletion with 1 craver on the planet.
But I don't see +12 FIDS on the planet or the system output.

**Comment by Reithan** [comment]
![image](https://github.com/user-attachments/assets/fb2e9778-b9cd-437f-b088-99ba4d951f41)
![image](https://github.com/user-attachments/assets/6f9049c6-4b60-4b23-8bab-4e723202c868)

**Comment by wakystuf** [comment]
I just tested this one and it seems to work. It will show up as part of the FIDSI of each planet (should be part of the 92 in the first image, if you hover)
