### ISSUE TITLE
Chain Gang and Mass Chain Gang often don't convert a pop

### ISSUE THREAD

**Issue by Reithan** [captaincobbs/ESG-Mod#1567]
For some reason, possibly related to Fast Game Speed, the food costs of both Chain Gang builds are halved, and often result in not losing a pop.
This could be good for many races, but when trying to use this for population shaping with Cravers, it means often spend 2+ turns to get rid of a new Craver pop, rather than just 1. The extra manpower is at least a boon, though.
![image](https://github.com/user-attachments/assets/13a7d37c-e404-412b-9208-dbcf4891cb19)
![image](https://github.com/user-attachments/assets/ca2d0333-9119-4d47-bbbd-042edc4023d6)

**Comment by wakystuf** [comment]
This isn't really a bug; it's just charging a cost in food
