### ISSUE TITLE
Removed hidden bonuses from specific factions, and added those bonuses to be publically visible via traits

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#162]
Horatio, Riftborn, and Cravers are the factions in question, no, their ships did not change.

**Comment by wakystuf** [comment]
What exactly was this change? Was this in the portion where one designs custom factions, or something else?

**Comment by captaincobbs** [comment]
Horatio ships (innately) have 10% more health
Riftborn and Cravers ships have 10% less health
Craver ships hold 10% more troops
Craver ships are 10% cheaper

I added all of these to traits

**Comment by wakystuf** [comment]
Thanks!

**Comment by captaincobbs** [comment]
Hm, this may have accidentally been skipped

**Comment by wakystuf** [comment]
Haha, OK. Well I'll just leave it under "Needs Documentation" for now

**Comment by captaincobbs** [comment]
Oops, meant to post that on the Capstone skill

**Comment by wakystuf** [comment]
All set
