### ISSUE TITLE
Add helpful formulas into related tooltips

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#166]
Food Consumption, Industry Stockpiling, Influence Radius, Trade HQ Income, Technology Cost, and Law Initial Cost

**Comment by wakystuf** [comment]
I don't think I saw the tooltips changed for industry stockpiling, Trade HQ income or law initial cost. I did see them for technology cost, influence radius and food consumption. Maybe I was looking in the wrong place?

**Comment by captaincobbs** [comment]
Industry stockpiling appears when you hover over the industry and see your system industry breakdown
Trade HQ appears when you hover over the big title word in the economy screen
Initial Law cost I don't remember though, I do remember confirming at one point that it did show up though

**Comment by wakystuf** [comment]
Oh, I see them now, except for the law one. Sounds good.
