### ISSUE TITLE
Give sensitive systems +1 movement on fleet per level

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#193]

**Comment by wakystuf** [comment]
What does this one mean? Is this the name of a hero skill, or something else?

**Comment by captaincobbs** [comment]
Counselors have a t3 admiral skill that gives +8 vision range and -40% fleet upkeep at max level, not very good for a t3 2 level skill

**Comment by wakystuf** [comment]
OK, got it.
