### ISSUE TITLE
Buffed Vodyani minor faction essence tribute, pacific conversion, alms for essence, behemoths modules, and essence per destroyed in battle leeching modules

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#2]

**Comment by wakystuf** [comment]
Alms for Essence and behemoths modules do not appear to be buffed from what I can tell. Were those changes reverted in a subsequent update?

**Comment by captaincobbs** [comment]
Alms for essence ended up not being buffed

**Comment by wakystuf** [comment]
OK, I'll clarify. 

Alms for Essence is a weird case...it's so bad now that it would require a really large buff in order to be worth blocking the production queue.

**Comment by Eighth-of-Third** [comment]
Alms for Essence blocks the production queue, but industry stockpiles for a single turn. If you AfE for a single turn then cancel it the next, you don't lose any industry. It's quite a bit of micro but doing that micro makes AfE useful.

**Comment by wakystuf** [comment]
I thought AfE didn't trigger on the first turn you put it in the queue though? I'm probably just missing something; that sounds quite clever.

**Comment by Eighth-of-Third** [comment]
It does. It won't display properly unless you put something in front of it in the queue and then cancel said thing, but it works.

**Comment by wakystuf** [comment]
Oh wow; I see what you mean now. That is the coolest trick I've learned in a while. Thanks!
