### ISSUE TITLE
Nerf Umbral Choir Trade to 25% efficiency

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#235]
PieLinux made a grave error

**Comment by Arpharnator** [comment]
No way to verify, even tho this image says only 50%
![image](https://user-images.githubusercontent.com/49691625/103134369-04e1e180-46b1-11eb-9ebc-2dddee2329ed.png)

**Comment by captaincobbs** [comment]
Oops, we decided not to do this.
