### ISSUE TITLE
Increase cost of trading systems, with lumeris getting a heavy discount

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#237]
Change base to 200, lumeris get 100 for systems, 50 for outposts. -50 on systems if in alliance, -12.5 for outposts

**Comment by Arpharnator** [comment]
Does not work
![image](https://user-images.githubusercontent.com/49691625/103135235-365dab80-46b7-11eb-8195-34898ab45ac2.png)
![image](https://user-images.githubusercontent.com/49691625/103135259-5ab98800-46b7-11eb-8bff-bf2c85c78362.png)
![image](https://user-images.githubusercontent.com/49691625/103135278-7ae94700-46b7-11eb-9319-022fefbbed5b.png)

**Comment by Arpharnator** [comment]
Cost is based on the amount of systems owned by the player that does the proposal

**Comment by wakystuf** [comment]
2 questions about this:
1) It looks from the code like there is an additional 12.5 reduction if there IsAlliance, right?
2) For the Lumeris outposts, shouldn't the base cost at peace be 87.5 (100 typical cost -12.5) instead of 50?

**Comment by captaincobbs** [comment]
OH, um yes

**Comment by wakystuf** [comment]
OK, sounds good. I'll keep an eye out and once the Lumeris outpost thing gets updated in the code I'll take a look and then post to the wiki a simplified description

**Comment by captaincobbs** [comment]
I'll fix it in a bit

**Comment by wakystuf** [comment]
OK, I fixed it and will now document
