### ISSUE TITLE
Add a game option for Free Terraforming

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#239]
Test both switches work for both riftborn and a vanlla faction

**Comment by captaincobbs** [comment]
FIX
DESERT to ASH : LACKS A LINK
DESERT TO LAVA : LACKS A LINK
ARCTIC to ICE : LACKS A LINK
ARCTIC to BARREN : LACKS A LINK

**Comment by Arpharnator** [comment]
Don't forget Arctic and Desert terraform into Barren/Ice, Lava/Ash, and that these terraforms are not done through Snow and Arid. Check here https://endless-space-2.fandom.com/wiki/Terraforming if you need a reminder. The interaction with Jovian terraforming is working, even tho you can't terraform from Arctic or Desert to gas and inversely.

**Comment by captaincobbs** [comment]
Note to self so I stop stressing: No new localization is needed

**Comment by captaincobbs** [comment]
In Luxury Rework branch

**Comment by Arpharnator** [comment]
Arid and cold terraformation to T3 planet other than Desert / Arctic is not possible. You need to change it

**Comment by Arpharnator** [comment]
Planet size reduction is not tied to T5 tech, but to T3 wormhole one.

Everything works otherwise

**Comment by captaincobbs** [comment]
> Arid and cold terraformation to T3 planet other than Desert / Arctic is not possible. You need to change it

Yes it is, it's a riftborn thing. Asked 3 people, they all said it is.


> Planet size reduction is not tied to T5 tech, but to T3 wormhole one.

Fixed
