### ISSUE TITLE
Shield capacity provided by Flotilla shielding do not scale with the ship level

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#243]

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/102700943-f46dd900-4262-11eb-9cc7-ba8aff649e6a.png)
 Flotilla shielding still does not scale with the ship level. 
Shield defense modules do.

**Comment by captaincobbs** [comment]
Is this the test branch, or the officially released mod? Because I swear I've fixed it. If not, look at the bottom of SimulationDescriptors[Ship].xml

**Comment by Arpharnator** [comment]
shields are good, but not flotilla shields.

**Comment by Arpharnator** [comment]
Flotilla shields do not scale with lv, but shields do
