### ISSUE TITLE
Balance UE, Riftborn and Sophons early quest requirements

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#249]
Riftborn first quest requirements are too easy, Increase their difficulty slightly. 
- Increase relations with a minor civ to 50 -> 75.

United Empire's first quest requirements are adjusted to be in alignment with other factions' quests.
- Search 10 -> 7 curiosities. (Scientist path)
- Stockpile 300 -> 225 dust. (Industrialist path)

Enable Sophons alternative first quest and determine the quest by random.

Sophons first quest pacifist path quest requirements are not on par with Riftborn quest. Reduce the pacifist path difficulty slightly.
- Increase relations with a minor civ to 90 -> 75. (Pacifist path)
- Discover 2 systems outside of your constellation (Scientist path, is disabled if the galaxy is a single const.)
- Search 50% -> 25% of the galaxy. (Alternative Scientist path)

Sophons Chapter 2 Militarist quests line requirements progress as: enable militarist law for 5 turns ->research x amount of military techs ->  build 4 ships. Ordering doesn't make sense and is changed to: research x amount of military techs -> build 4 ships -> enable militarist law for 5 turns. Quest rewards are not changed.

**Comment by captaincobbs** [comment]
Were these changes accepted?

**Comment by Eighth-of-Third** [comment]
I think 10 curiosities is too high for a first quest. 7 is more feasible. The Empire first quest about curiosity searching should also probably be changed to 7 explored curiosities
Changing the relations requirements for a minor civ to 75 is a good change, 50 is too easy and 90 is too high.
Reducing the Sophons exploration requirement for scientist path to 25% is a good change. 50% will take forever.

**Comment by Doruk-Coskun** [comment]
Updated according to discussions, currently listed changes are accepted.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/102763316-8b818080-438a-11eb-9a27-be7e11175c88.png)


![image](https://user-images.githubusercontent.com/25507419/102763378-9e945080-438a-11eb-8210-0805f8cc1290.png)

**Comment by Doruk-Coskun** [comment]
![Uploading image.png…]()

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103092093-2c7c6f80-4607-11eb-8b1c-fe3fd0b60510.png)

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103092103-3900c800-4607-11eb-9669-1cdbfcef95ed.png)

**Comment by wakystuf** [comment]
I don't think I knew about most of these changes; is this an accurate summary?
-Riftborn first pacifist quest requirement increased from 50 to 75 points with a minor civilization
-UE first scientist quest requirement lowered from 10 curiosities to 7
-Reordered Sophon chapter 2 militarist quests: 
  Vanilla: enable militarist law for 5 turns ->research x amount of military techs -> build 4 ships. 
  New: research x amount of military techs -> build 4 ships -> enable militarist law for 5 turns.

I saw discussion also of the following; were they incorporated (there was no screenshot):
-Sophon first quest: Search 50% -> 25% of the galaxy. (Alternative Scientist path)
-Sophon first quest: Increase relations with a minor civ to 90 -> 75. (Pacifist path)
-UE first quest: Stockpile 300 -> 225 dust. (Industrialist path)

Also, I have the following currently listed for 1.3.1 currently: "Replaced previous "raise militarist support to 30% in 3 systems" quest with "maintain 1 militarist law for 8 turns". Was that actually completed in 1.3.0 and then simply nerfed from 5 to 8 in 1.3.1? Or is that separate from the chapter 2 part?

**Comment by Doruk-Coskun** [comment]
> -UE first quest: Stockpile 300 -> 225 dust. (Industrialist path)
in 1.3.1 this is reverted back to 300 dust cause the traitors reach (reward of that quest path) is buffed.

> as that actually completed in 1.3.0 and then simply nerfed from 5 to 8 in 1.3.1? Or is that separate from the chapter 2 part?
I believe that was the case yes.

The rest of the changes you listed in your comment are completely accurate. @wakystuf

**Comment by wakystuf** [comment]
Great. Documented.
