### ISSUE TITLE
Buffed Antimatter Lock-On to 6% per CP for 2nd tier, 10% per cp for 3rd tier

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#25]

**Comment by wakystuf** [comment]
There were also damage boosts that apply only to the ship with the module (which don't show up in the tooltip, only the code) which were increased, correct?

It would be ideal to clarify how the various bonuses are applied as well. The main "per CP" bonus is applied to [the entire friendly flotilla] based on the current # of CPs in [the entire enemy flotilla], or something else?

**Comment by captaincobbs** [comment]
We had originally buffed this, but we found out that the damage buff affected the whole flotilla, so we made it so you could only have one per ship, and it was only equippable on Coordinators.

**Comment by wakystuf** [comment]
OK, thanks. A few things on that one:
1) The damage buff that affects the whole flotilla is the "per CP" bonus, correct? (Not the hidden damage boosts that aren't included in the tooltip)
2) I tested this and was able to apply the module to both a Coordinator and Protector hull (which I think is fine, but just wanted to make sure I wasn't missing something)
3) I was able to build ships with multiple of those modules per ship (again, maybe I'm just doing it wrong)

**Comment by captaincobbs** [comment]
1. the Per CP bonus is on the whole flotilla, but it only applies to whatever that specific ship is targeting
2. Are you using 1.3.1?

**Comment by wakystuf** [comment]
OK, got it, thanks. 

Oh, no; I'm on 1.3.0. I didn't realize you meant that those changes were still experimental (which is what 1.3.1 mod is, right?)

**Comment by captaincobbs** [comment]
Yup, I'll dm you a link
