### ISSUE TITLE
Make Unique Planet Quest toggle with Academy Quest Setting

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#255]

**Comment by captaincobbs** [comment]
Included on luxury rework branch

**Comment by Arpharnator** [comment]
ramscoop is finally deleted from the game

**Comment by Doruk-Coskun** [comment]
This makes it so that ramscoop quest is only enabled with academy quest. We hid it so other engines actually have a chance

**Comment by wakystuf** [comment]
OK, got it. Documented
