### ISSUE TITLE
[IMPORTANT] Quest rewards are not given when using modding tools to complete quests...

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#256]
bruh, for UE the first one is given correctly, but then it doesn't.
At chapter 1.2 completing the quest using modding tools does not allow you to proceed in the quest and gain the heroes
After further investigation it seems to be linked to UE more, as to prevent switching pop too often.

**Comment by captaincobbs** [comment]
I can't hack the game to fix this
