### ISSUE TITLE
Mezari last population Collection not applying

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#257]

**Comment by captaincobbs** [comment]
You fix it

**Comment by captaincobbs** [comment]
I think I've incidentally found the solution remove "Net" from both variable names in `PopulationCollectionBonusMezari3`

**Comment by Arpharnator** [comment]
Were the changes put inside cobbs-test or another branch? Because it does not work in this branch and the code is the bugged one.

**Comment by Arpharnator** [comment]
it's fine actually
