### ISSUE TITLE
Mezari +10% bonus Science empire wide not applying

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#258]

**Comment by captaincobbs** [comment]
You fix it

**Comment by Arpharnator** [comment]
Does apply, amount of science gotten per turn is correct, however there is no description that you get a +10%.
![image](https://user-images.githubusercontent.com/49691625/102996224-fe256400-4522-11eb-842c-bce7f4bbbf52.png)

**Comment by Arpharnator** [comment]
After further investigation, it would seem the bonus applies after ALL bonuses.
For example here you can see thata I make 385 science base +115 from devoted. that means I should get 38 more science from mezari right? That is not the case, as the bonus is 50.
![image](https://user-images.githubusercontent.com/49691625/102999355-21531200-4529-11eb-929e-958b797d6257.png)

**Comment by captaincobbs** [comment]
I'm pretty sure it only applies to Raw Science, Devoted Science does not count.

**Comment by captaincobbs** [comment]
Works properly
