### ISSUE TITLE
Shield regen does not affect Flotilla Shielding

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#260]
![image](https://user-images.githubusercontent.com/49691625/102905836-04103c00-4474-11eb-99f8-a33f5f44dc96.png)
My protectors are equipped each with a 1% shield regen on fleet, and 3 hyperium flotilla shield, making each give 1650 shield to flotilla.

**Comment by captaincobbs** [comment]
Intended.
