### ISSUE TITLE
Behemoth terraforming is bugged

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#261]
![image](https://user-images.githubusercontent.com/49691625/102913377-f6ac7f00-447e-11eb-9f6b-1bc5362f4b26.png)
![image](https://user-images.githubusercontent.com/49691625/102913389-f9a76f80-447e-11eb-9b51-4c62bdda4bec.png)
![image](https://user-images.githubusercontent.com/49691625/102913397-fca26000-447e-11eb-8268-72cf5875b549.png)

**Comment by Arpharnator** [comment]
I can furthermore terraform backward with a terraforming behemoth

**Comment by Arpharnator** [comment]
Colonized planets are not terraformable, do not know if it intended or not but seems like a bad thing

**Comment by captaincobbs** [comment]
I'm fairly certain I've found a solution, but it'll be time intensive, so I'll just assign this to myself so that no one else has to worry.

**Comment by captaincobbs** [comment]
In luxury rework branch

**Comment by Arpharnator** [comment]
disabled as intended
