### ISSUE TITLE
Ecologist last laws to 3% each for each spliced pop, 5% in republic

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#264]

**Comment by captaincobbs** [comment]
Ecologist Law 3 (Power to the People) was changed to +3% (+5% on Republic, from 2% and 4% respectively) Research per Assimilated (Spliced for Horatio) Population Types on Systems

Ecologist Law 4 (All Hands Dictum) was changed to +3% (+5% on Republic, from 2% and 4% respectively) Industry per Assimilated (Spliced for Horatio) Population Types on Systems

**Comment by wakystuf** [comment]
That's super-helpful; thanks! This is why you're in charge of the project and Arphar is in charge of complaining. Documented.

**Comment by captaincobbs** [comment]
Arphar is great at his job
