### ISSUE TITLE
Horatio carriers do not focus fire

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#275]

**Comment by Arpharnator** [comment]
![Uploading image.png…]()

**Comment by Arpharnator** [comment]
can confirm
![image](https://user-images.githubusercontent.com/49691625/103107144-cc53f080-463b-11eb-99ed-5f57a50e994e.png)

**Comment by captaincobbs** [comment]
Carriers don't focus fire.

**Comment by wakystuf** [comment]
This sounds like it was rejected, given that it is normal behavior?

**Comment by captaincobbs** [comment]
Yes
