### ISSUE TITLE
Cravers Pillage and Raze Action Rework

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#289]
- Cravers Pillage action: Additionally kidnaps the population like the Horatio special action.
```<PopulationLoot>Min(5, $(MovablePopulationCount) / 5)</PopulationLoot>```

- Cravers Raze action: +100 dust, +25 influence, +25 science and +2 depletion point, all of them are per turn and modified by game speed multiplier.

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/103309635-a5743080-4a26-11eb-9305-fe3c231ab6fb.png)

**Comment by Doruk-Coskun** [comment]
Raze action depletion point per turn and pillage action pop steal could not be implemented. Help needed. Delayed for future patches.

**Comment by captaincobbs** [comment]
Did you make a new cravers ground battle outcome?

**Comment by Doruk-Coskun** [comment]
Cravers Pillage action steals pop, UI will be updated on the following patches. 

Cravers raze generating depletion point on planets is scraped. There is no obvious implementation and generally is not necessary.
