### ISSUE TITLE
1.3 Fleet Balance Changes

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#290]
- Bombers targeting change: Depending on Ship size Small -> Medium -> Large
- Carriers targeting change: Carriers -> Hunters/Attackers -> Protectors/Coordinators
- Protectors/Coordinators targeting change: Hunters/Attackers -> Protectors/Coordinators -> Carriers
- Hunters/Attackers targeting change: Protectors -> Coordinators -> Carriers -> Hunters/Attackers
- Revert changes to Kinetic and Energy weapons penetration values to Vanilla values.
- Defensive trait gets buffed to: +10% Health and +10% Shield Capacity in addition to Defence value.
- Protector trait is created, given to Coordinators and effects: +20% Health and +20% Shield Capacity in addition to Defence value.
- Bombers damage against Small ships are reduced to 50% -> 25%
- Kinetic bombers hull plating penetration reduced to 50% -> 10%
- Buff Slugs effective ranges 10-50-85 -> 25-50-100
- Reduce the strategic cost of Antimatter Lenser and Adamantian Jammer (targeting priority changing modules) to 1 Antimatter and 1 Adamantian respectively.
- Battle Morale Effect changed to +5% accuracy, +10% damage -> +10% accuracy, +5% damage, +10% evasion per flotilla count higher than opponent.
- Team Spirit Battle Tactic effect increased to 50% -> 100% Morale Effect

**Comment by captaincobbs** [comment]
These changes have already been accepted, for anyone worried.
