### ISSUE TITLE
Temporarily disable planet terraformation on terraformation modules

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#297]

**Comment by Arpharnator** [comment]
works

**Comment by wakystuf** [comment]
What does this mean?

**Comment by captaincobbs** [comment]
You can't terraform via behemoth because for some reason, it specifically has a game crashing bug, but terraformation via system does not.

**Comment by wakystuf** [comment]
So behemoth terraforming was causing some kind of bug, and the solution was to remove it?

**Comment by Doruk-Coskun** [comment]
Yes

**Comment by wakystuf** [comment]
OK, got it. Documented
