### ISSUE TITLE
Sophons Minor Questline Changes

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#300]

**Comment by wakystuf** [comment]
What exactly was this change?

**Comment by captaincobbs** [comment]
I've asked chaos to respond to this

**Comment by wakystuf** [comment]
I think this one is still open

**Comment by wakystuf** [comment]
I'm guessing that this is related to the fact that the fast/slow move traits are now impacting free movement speed?

**Comment by Doruk-Coskun** [comment]
@wakystuf yes there is that, Sophons explorers one of the attack slots changed with Attack/Support slot. Sophons Juggernaut module is reworked too. Its a Carrier/Behemoth module which gives shield to every ship on the flotilla and provides +15% EMP defense to the flotilla

**Comment by wakystuf** [comment]
OK, great; I'll add these to the wiki:
* Buffed Juggernaut module to provide +15% EMP defense to the flotilla in addition to flotilla shielding
* Buffed Fast Travelers II to also provide +30% free movement speed (and correspondingly updated Fast Travelers I)
* Converted explorer attack slot to attack/support slot

However, from the code it looks like there was other stuff too, correct?
* Buffed ENFER system to always spawn with the following 4 planets:
  * Medium Boreal with abundant titanium deposit and Humeris Insidentes
  * Huge Steppes with Antonov Ring
  * Medium Arctic with average antimatter deposit, Hollow Planet and Long Season
  * Medium Ash with poor adamantian deposit, Aurora Waves and Strong Magnetic Field
* Propaganda constructible provides +5 happiness
* A change to the sophon defensive building, but which appears to have the vanilla stats for Tractable Armaments? Is this a quest reward building? I couldn't find it on the tech tree
* Reduced militarist quest from researching 5 military technologies to 4
* Replace previous "raise militarist support to 30% in 3 systems" quest with "maintain 1 militarist law for 8 turns"

**Comment by Doruk-Coskun** [comment]
@wakystuf yup they are all accurate. Fast Travelers I also has 10% free movement speed too now which effects the Vodyani

**Comment by wakystuf** [comment]
Great, thanks. What about my question on the defensive building:
A change to the sophon defensive building, but which appears to have the vanilla stats for Tractable Armaments? Is this a quest reward building? I couldn't find it on the tech tree

**Comment by wakystuf** [comment]
Oh and one other question on this: didn't 1.1 already contain the following change? If so, what is the incremental portion of the change to that quest in this update?
Replaced Sophon "Raise Military Support" quest with "Maintain 1 Militarist law for X Turns"

**Comment by Doruk-Coskun** [comment]
Yes it is a quest building "Sophonic Ramparts" iirc and it has similar or maybe same effect as Tractable Armaments

**Comment by wakystuf** [comment]
OK, I've added the following to the wiki:
* Buffed Sophonic Ramparts (quest reward from militarist line)
  * Maximum system manpower increased from 175 to 250
  * Manpower deployment limit increased from 100 to 150
  * Added incremental damage to attacker of 750
 
What about my question above about the quest change?

**Comment by captaincobbs** [comment]
Yes, Sophon Quest "Seeding the Cloud - Part 3" was changed to maintain 1 (or your current number of militarist laws +1) militarist law for 8 * game speed turns in 1.1

**Comment by wakystuf** [comment]
Great; thanks! Documented.
