### ISSUE TITLE
Battle Tactics Effects Rework - Part 1

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#301]

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/104128591-9459e680-5379-11eb-89be-ecf99920f925.png)

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/104133409-7d74bd80-5394-11eb-9113-7b8055f5ab90.png)

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/104629264-5676fe00-56aa-11eb-88d7-ff8eb5730882.png)

![image](https://user-images.githubusercontent.com/25507419/104629339-6c84be80-56aa-11eb-9f14-9e5a0e8a216c.png)

![image](https://user-images.githubusercontent.com/25507419/104629372-773f5380-56aa-11eb-8f1d-4724db374429.png)

**Comment by wakystuf** [comment]
First, this whole concept is great; it should make a bunch of the previously useless battle tactics way more relevant. 

Several questions:
1) Team Spirit: this is doubling whatever morale bonuses (ex: hero, flotilla flanking, etc) already exist, correct? If there are no morale bonuses, it doesn't do anything?
2) Needs of the Many: Without this, the damage bonus is basically 20% * [Current Ship MP]/[Max Ship MP], and then it's becoming 70% * [Current Ship MP]/[Max Ship MP], correct?
3) Anti-Shrapnel Hull and Radiation Shield: Do these apply the Hull/Shield Absorption to crew defense from both types of weapons? For example, if ship Hull Absorption is 50%, and the attacker has beams that kill 10 crew per hit, would it then be only 5 crew killed per hit (even though normally beams have high Hull Penetration)?
4) Temporal Drag: What effect, if any, does this have on BEB? How (if at all) does it stack with EMP modules?
5) Diplomatic Immunity: I assume "Damage Absorption" means that it doubles both Hull Absorption and Shield Absorption?
6) Collateral damage: How does the collateral damage part of the calculation work? Is it only a buff to weapons (ex: quadrinix lasers, BEB) that already inflict collateral damage? Is it correct that the "breakeven" point is basically 4 enemy ships in the flotilla (0.7 x (1+15%x3)) = 101.5%?
7) Hard Target and Shield Wall: are these defense bonuses applied to Evasion, Absorption, or something else?
8) Soft Targets: How is "least dangerous" evaluated? Is it based on attack power? Also, does this enable non-Focus ships to focus fire on the "least dangerous" target(s)?
9) For the Cause: Is this calculated ship-by-ship or for the fleet as a whole? For example, if there are 3 carriers, each with 16 squadrons, then does each squadron get 66% defense (1-0.5+0.16) or 98% defense (1-0.5+0.48)?
10) Hopeless: Does this mean that all morale bonuses are effectively multiplied by -0.5? (But if there are no morale bonuses, then no penalty)?

**Comment by wakystuf** [comment]
Oh, and one other one: what happens if one side plays Team Spirit and the other plays Hopeless? Does that mean that the one playing Team Spirit effectively gets Morale x 2 x -0.5 = -1 x Morale?

**Comment by wakystuf** [comment]
I think this one is still open

**Comment by Doruk-Coskun** [comment]
1) Yes exactly.

**Comment by Doruk-Coskun** [comment]
@wakystuf Also keep in mind the screenshots you see here are the vanilla tactics. Reworked versions of them are not listed here, you can check them in game

**Comment by wakystuf** [comment]
OK, this is now documented, for the most part. A couple clarifications:
1) These tactics also changed, even though they are not screenshotted above, right?
* Emergency Battery: From +500 shield reloading per phase to +4% regeneration per second, but -15% damage, accuracy and evasion
  * Prudent Positions: For both fleets, from -50% damage to -35%
  * Evasive Maneuvers: From evasion bonus of +30% at long range and +15% medium to opponent accuracy penalty of -40% at long range and -20% at medium range
2) How does Power to shields doubling of Shield Absorption work? Does that mean a ship can get over 100% (ex: if a ship has 300 shield absorption and 100 hull weakness, for 75% absorption, does that make it 150% absorption?)

**Comment by Doruk-Coskun** [comment]
@wakystuf 
1. Yes exactly.
2. Shield absorption is capped at 100% then there is shield penetration value of the weapon. Power to Shields just makes it so that penetration is calculated based on 100% shield absorption rather than 50 70 or 80% you would get from shield defense modules absorption value

**Comment by wakystuf** [comment]
Great, thanks. Documented.
