### ISSUE TITLE
1.3.1 Fleet Balance Changes

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#302]
- (DONE) Minor Changes on Targeting to make targeting increasing modules more impactful (Test targeting modules to make sure they work as intended)
- (DONE) Increase shield capacity of every shield module depending on its tier (Consider Providing Strategic shields innate shield regen)
- (DELAYED) Balance Coilgun
- (DONE) Balance Flak DPS vs. Missile/Swarm Missiles (Provide Strategic weapons better Flak/Health stats)
- (DONE) Balance Flak DPS vs. Drop Pods
- (REJECTED) Consider separating Flak damage from slug modules and create a separate module dedicated for that purpose.
- (DONE) Balance Flak DPS vs. Squadrons (REJECTED) (Create a new coordinator/protector specific anti Squadron weapon)
- (DONE) Rescale ship health and shield capacity increase per ship level
- (DONE) Rescale Ship EXP rewards of Military Technology Tier unlocks and Ship EXP system improvements
- (DONE) Balance Flotilla Shielding, (DONE) Shield Regen and (DONE) Health Regen module values
- (DONE) Rework EMP weapons and EMP defense modules 
- (DONE) Rework unlock of new Battle Tactic slots to be T3, T4 and T5 Military Stage unlocks totaling 6)

**Comment by captaincobbs** [comment]
Request: Include coilguns in your balancing

**Comment by wakystuf** [comment]
I'm tagging this as "Needs Documentation", but I don't yet have an intelligent question. I need to go through the code a bit and then I'll circle back.

**Comment by captaincobbs** [comment]
kk

**Comment by Doruk-Coskun** [comment]
Influence per CP killed and Dust per CP Killed module effects are buffed.
EMP Modules are moved to different T4 techs.
Blast Effect Battery Cost reworked.
Bomber Small Ship Damage % increased, Large ship Damage reduced, bomber DPS adjusted accordingly.
Production Cost of every module is reworked.

**Comment by Doruk-Coskun** [comment]
- Buff EMP defense modules
- Limit EMP to medium sized ships only (Not Determined Yet)

**Comment by wakystuf** [comment]
@Doruk-Coskun Now that almost everything else is done, I'm getting started on these. I went ahead and listed the general ideas on the wiki, but I'm trying to also add more detail. I'll look at some of it myself as well, but for the first batch of questions (I'm sure there will be many more as I dig into this), let's start with the Flak rebalancing:
1) How does the calculation of flak dps vs missile salvo health typically work? Is it just applying flak DPS vs salvo health, or is there a miss chance? Does the flak get to shoot only once at each incoming missile, or can it shoot multiple times?
2) Did the rebalancing make it easier or harder for flak to shoot down a) missiles, b) swarm missiles, c) boarding pods and d) squadrons?

**Comment by wakystuf** [comment]
@Doruk-Coskun OK, some other questions I had based on reading that design document you sent me and then comparing vs the code (I made it through around 3/4 of that document, so there are still some that I need to look at):

It looks like the following changes from the design document WERE made already, correct?
* Carriers had hull weakness increased to 600, from 400
* Change targeting priority of Carriers to:
  * Carriers
  * Hunters/Attackers
  * Protectors/Coordinators
* Fix Hunter and Attacker targeting priority:
  * Protectors
  * Coordinators
  * Carriers
  * Attackers/Hunters
*  Coordinators and Protectors received +10% and +20%, respectively, to Health, Shield Capacity, Hull Absorption and Shield Absorption, correct? Note that I believe the commentary that is in the code (in SimulationDescriptors[Ship].xml) has this backwards; I had to trace the variable to the other file to figure that out.
* All ships' targeting priorities now treat heroes as Attackers, except for Coordinators, which now treat heroes as Hunters
* Heroes now target medium hulls, then large hulls, then small hulls
* Ship level up bonus changed to +5% Ship Health, +5% Shield Capacity, +5% Flotilla Shield Capacity from Flotilla Shield modules (vs +25% health in vanilla)
* Morale effect buffed to provide: +5% Damage, +10% Accuracy and +10% Evasion
* Every defense module provides an innate Crew defense against weapons of 5% per module (does this scale with module multiplier?), except adamantian plating, which is 15%
* Weapon accuracy is reworked to 95/50/25 for missiles and swarm missiles, 25/50/95 for slugs, 50/95/50 for lasers and 90/90/90 for beams
* Strategic weapons are reworked
  *  Strategic resource cost of every weapon module is reduced to 1 respective strategic resource (still scales with module multiplier)
  * Strategic weapons unlocked by technologies provide higher DPS than white modules of one tier higher, and provide additional effects. 
  * Strategic weapons found by curiosities provide the same additional effect as their counterparts on the tech tree, but their DPS is one tier lower

It looks like these changes were NOT implemented, correct?
* Targeting priority changes for protectors and coordinators
* Medium ships hull weakness increased to 250 -> 300 and Large ships hull weakness increased to 600 -> 700

**Comment by captaincobbs** [comment]
Ship level up is correct, but the vanilla value isn't. It increases health inconsistently per level in vanilla.

**Comment by captaincobbs** [comment]
Also, any targeting changes you might want to confirm are located in Simulation/Battles/ShipRoleDefinitions[blah].xml

**Comment by wakystuf** [comment]
> Ship level up is correct, but the vanilla value isn't. It increases health inconsistently per level in vanilla.

Yeah, fair enough. I've edited my comment to be more specific; let me know if that looks incorrect.


> Also, any targeting changes you might want to confirm are located in Simulation/Battles/ShipRoleDefinitions[blah].xml

Yes, for the targeting changes, those are where I checked. I validated all of these in the code, but just wanted to make sure there weren't any that I'd misunderstood, or were effectively being calculated differently due to some other part of the code.

**Comment by Doruk-Coskun** [comment]
>1. How does the calculation of flak dps vs missile salvo health typically work? Is it just applying flak DPS vs salvo health, or is there a miss chance? Does the flak get to shoot only once at each incoming missile, or can it shoot multiple times?
2. Did the rebalancing make it easier or harder for flak to shoot down a) missiles, b) swarm missiles, c) boarding pods and d) squadrons?

1. I don't know how they are calculated exactly. We know that flak actually has 80/0/0 short medium and long range damage modifier. Manipulating these modifiers is how Coordinated Flak module works.
2. Balancing made it so that the tier of the flak and missile and also whether the module is a strategic weapon or not translates accurately to the values on the module. Higher tiers have more salvo health or flak damage, strategic better then their white counter parts and some strategics are better compared to other strategics in terms of values.

**Comment by Doruk-Coskun** [comment]
> Carriers had hull weakness increased to 600, from 400

as you have listed at the end of your message the correct change is this:
>Medium ships hull weakness increased to 250 -> 300 and Large ships hull weakness increased to 600 -> 700

> Coordinators and Protectors received +10% and +20%, respectively, to Health, Shield Capacity, Hull Absorption and Shield Absorption, correct? Note that I believe the commentary that is in the code (in SimulationDescriptors[Ship].xml) has this backwards; I had to trace the variable to the other file to figure that out.

The comment was outdated. We initially made coordinators have the +20% but we decided that protectors having +20% is the better way.

>Every defense module provides an innate Crew defense against weapons of 5% per module (does this scale with module multiplier?), except adamantian plating, which is 15%

It does not scale with module multiplier no. It simply makes it so that using more defense modules is more beneficial. A small detail to lift the value of defense modules to the level of attack and support.

>It looks like these changes were NOT implemented, correct? Targeting priority changes for protectors and coordinators

That is not correct. Updated targeting order for Coordinators and Protectors is this: Attacker -> Hunter -> Protector/Coordinator -> Carrier

@wakystuf

**Comment by wakystuf** [comment]
@Doruk-Coskun Great; thanks. That's helpful. I'll post most of that to the wiki. A couple other questions though:

> Balancing made it so that the tier of the flak and missile and also whether the module is a strategic weapon or not translates accurately to the values on the module. Higher tiers have more salvo health or flak damage, strategic better then their white counter parts and some strategics are better compared to other strategics in terms of values.

So before the UI was displaying inaccurate information, you are saying, and that is now corrected?
Also, does this make it easier for flak to shoot down missiles, swarms, squadrons, and boarding pods, or harder?

> as you have listed at the end of your message the correct change is this:
> Medium ships hull weakness increased to 250 -> 300 and Large ships hull weakness increased to 600 -> 700

Can you point me to which file contains this? I thought I checked the hull weaknesses and it was 600 but maybe I was looking in the wrong place.

**Comment by wakystuf** [comment]
Also, @Doruk-Coskun here are a few others as I continue to go through the code:
* Blast Effect Battery cost reworked from 300 to 250, but added strategic resource cost of 2 antimatter and 2 adamantian
* Moved EMP weapon modules from Tensor Algorithms and Advanced Game Theory to Adamantian Alloys and Structured Antimatter
* EMP Missile’s EMP duration and cooldown is reworked to be in synchronization with Swarm Missiles (was this one implemented? The cooldowns look like they are different for EMP vs swarm)
* Reworked support modules
  * Strategic resource costs reduced for almost all support modules
  * Added +3 movement speed effect to Adamantian Jammers 
  * Added 20 HP repair per second effect to Antimatter Lensers
  * Added new Flotilla Wide EMP defense module ("EMP Disruption Field") in addition to already existing ship EMP defense modules to counter EMP heavy fleets
  * Added new Flotilla Flak boosting module ("Coordinated Flak") which increases the effective range of the Flak and Flak DPS
* Made the following modules Coordinator-specific: Antimatter Lock-on, Coordinated Flak, EMP Disruption Field, Antimatter Reshield, Adamantian Repairbots, Ori-Bot Swarm
* Restricted the following support modules to be only 1 per ship: Antimatter Lock-on, Antimatter Reshield, Adamantian Repairbots, Ori-Bot Swarm, Strike Multiplier, and Squadron Shifter
* Ambush Effect of T3 Cloaking is removed (it was broken and caused unintended effects)
* Fleet Accelerators now increase distance traveled per movement point by +10%/20%/30% for tiers 1/2/3 (Ramscoop Effect)

Also, related to your comment above, does the Coordinated Flak "-5% flak range penalty on flotilla" enable flak to work at long and medium ranges? Does that mean it can begin shooting at missiles way before they enter the normal "flak zone"?

**Comment by wakystuf** [comment]
OK, here are some more as well for @Doruk-Coskun to confirm; I'm working my way through the various modules (still need to do beams, lasers, swarms, boarding pods and EMP):
* MISSILES
  * White modules' DPS unchanged from vanilla
  * Hull and shield penetration values unchanged from vanilla
  * Salvo health for era 4 and 5 white modules buffed by 5 so that each era now adds +15 health (60 at E1 to 120 at E5)
  * Preparation duration increased from 0.5 to 1 (Chaos, is this the delay before first shot is fired?)
  * Preparation duration factor min and max range forced to 1x (vs 0.8x to 1.2x) (Chaos, what does this mean/do?)
  * Shooting duration increased from 2 to 3 (Chaos, what does this mean/do?)
  * Titanium and Orichalcix missiles have 5% critical chance
  * Titanium missiles have added effect to kill 20 manpower per hit (vs 5 for white missiles)
  * Adamantian missiles have higher DPS than typical for their era and 20% critical chance
  * Orichalcix missiles cause 20% longer cooldowns in targets' weapons
* SLUGS
  * White modules' DPS unchanged from vanilla
  * Hull and shield penetration, preparation duration, preparation duration min/max, and shooting duration all unchanged from vanilla
  * All strategic modules have 10% faster cooldown (as in vanilla)
  * Titanium and Orichalcix slugs have 5% critical chance
  * Titanium slugs have added effect to kill 2 manpower per hit (vs 1 for white slugs)
  * Adamantian slugs have higher DPS than typical for their era and 20% critical chance
  * Orichalcix slugs cause 20% longer cooldowns in targets' weapons
* FLAK (attached to Slugs, but calculated separately)
  * Efficiency vs squadrons increased from 2.5% to 6.5%
  * Preparation duration, preparation duration min/max, and shooting duration all unchanged from vanilla
  *  [See questions below regarding DPS of titanium slugs]
  * Adamantian modules' damage buffed from 150 to 165
  * Orichalcix curiosity module's damage buffed from 150 to 210 (no change to 210 for tech tree module)
  
For flak, a few questions also:
* Is "ModuleWeaponFlack1Strategic1" a new module and/or some kind of error? I didn't see it in vanilla (and wouldn't expect there to be a strategic module that is only era1).
* Does ModuleWeaponFlack2Strategic1 (165 and 210 Damage) overwrite the flak damage in ModuleWeaponKinetic2Strategic1 and ModuleWeaponKinetic3Strategic1 (both 180)? What is the difference between those 2 numbers?
* Was there really no change to the DPS of white flak modules? I had thought there were a bunch of changes to flak balancing, but it sounds like all of it was from boarding pod health + SquadronEfficiency (plus that one minor change to missile salvo health)?

**Comment by Doruk-Coskun** [comment]
> EMP Missile’s EMP duration and cooldown is reworked to be in synchronization with Swarm Missiles (was this one implemented? The cooldowns look like they are different for EMP vs swarm)

Yes it is implemented. Swarm cooldowns work in a different way, EMP missiles cooldown is aligned with normal missiles which are in sync with swarm missiles.

> Related to your comment above, does the Coordinated Flak "-5% flak range penalty on flotilla" enable flak to work at long and medium ranges? Does that mean it can begin shooting at missiles way before they enter the normal "flak zone"?

In theory yes. That is also one of the purposes of the Coordinated Flak module. Further testing to show how impactful it is would be appreciated tho.

> What is the new custom module that provides -75 MP? Is that just for testing, or does it actually show up in the game someplace?

I believe it is a special module used while spawning quest ship in one of the major faction questlines. It is not available for the players and does not need documentation.

>For the repair modules, what is HealthRegenerationRatio?

I believe it is repair per phase or sth. The effect of repair modules are correctly displayed in module UI. You can check that instead of the code.

> Is "ModuleWeaponFlack1Strategic1" a new module and/or some kind of error? I didn't see it in vanilla (and wouldn't expect there to be a strategic module that is only era1).

Modding wise, every flak weapon is also tied to an invisible flak weapon module. Flak weapon module only works for flak. Manipulating flak damage value for specific slug modules sometimes required creating new flak weapon modules in code because the developers just tied them to white modules. This is also not a documentation issue, it is a modding issue. Game UI correctly displays the new Flak values.

> Does ModuleWeaponFlack2Strategic1 (165 and 210 Damage) overwrite the flak damage in ModuleWeaponKinetic2Strategic1 and ModuleWeaponKinetic3Strategic1 (both 180)? What is the difference between those 2 numbers?

Flak damage value listed on the Slug weapon module is for UI only. The real flak damage is tied to Flak weapon module. There shouldn't be any discrepancies in the UI element value of a weapon module and actual flak damage of the Flak module tied to that weapon module. If you have noticed any differences, it might be my mistake and you can let me know.

> Was there no change to the DPS of white flak modules? I had thought there were a bunch of changes to flak balancing, but it sounds like all of it was from boarding pod health + SquadronEfficiency (plus that one minor change to missile salvo health)?

Testing showed that the balance of the game worked good enough. Same tier Flak countered same tier Missiles almost always. But as the tier of the missiles increase it started to fall short. All I did was the make the Flak and missile salvo values of every white and strategic module is aligned.

> Where do I find this in the code, so that I can find the exact numbers? "Increased bomber damage % to small ships, reduced damage % to large ships; no change to bomber base DPS"

You can just search for "bomber" and see what comes up. It should be in one of the DLC definitions file. Basically the bomber percentages became 125% for large - 90% for medium and 70% for smalls. In game UI displayed it correctly. Also due to this change energy bomber damage values are reverted to vanilla since we halved them the previous patch.

> I know in vanilla there is an issue with bombers benefiting 2x or 4x from any damage bonus; is that now fixed?

yes.

> Does this imply that squadrons deal double damage vs carriers? I suspect it means something different, since that would be a lot
<Modifier TargetProperty="SizeDamageMultiplierForSquadron" Operation="Addition" Value="1" Path="ClassShip" TooltipHidden="true"/>

I actually am not sure. I'll double check that but that's not sth I messed with.

> So before the UI was displaying inaccurate information, you are saying, and that is now corrected?
Also, does this make it easier for flak to shoot down missiles, swarms, squadrons, and boarding pods, or harder?

No the values was different for some of the modules too now they are more coherent. This means if you have a higher tier or same tier but strategic flak it will be more effective at killing missiles. The same goes the other way around if you have higher tier or strategic missiles.

> Can you point me to which file contains this? I thought I checked the hull weaknesses and it was 600 but maybe I was looking in the wrong place.

Ill check and update the comment

@wakystuf

**Comment by Doruk-Coskun** [comment]
> Salvo health for era 4 and 5 white modules buffed by 5 so that each era now adds +15 health (60 at E1 to 120 at E5)

Rather than "era" use stage or tier.

> Preparation duration increased from 0.5 to 1 (Chaos, is this the delay before first shot is fired?)

When the weapon is cooled down the time it takes for the weapon to shoot. It also affects the very first shot of the weapon since you start the battle with no cooldowns. But do not affect the DPS of the weapon.

> Preparation duration factor min and max range forced to 1x (vs 0.8x to 1.2x) (Chaos, what does this mean/do?)

There is no randomness in determining when the missile shoots when its cooldown is completed. The randomness is removed to make sure Missiles and Swarms align correctly.

> Shooting duration increased from 2 to 3 (Chaos, what does this mean/do?)

Its also for alignment with the swarms, its not important for the player and doesn't effect the DPS of the weapon. We also removed both preparation and shooting duration from the weapons UI because it didn't give any useful information to the player but caused them to be confused.

>DPS reworked from 17/28/38 to 15/29/44 (Chaos, is this accurate? I am calculating as Damage x Shot Count / Cooldown)

Seems accurate yes.

> Cooldown reworked from flat 7.2 to 8/6.9/5.8 (Chaos, is this accurate? I am adding Cooldown + Cooldown Variation, but it's kind of a weird way that the devs set it up)

Base cooldown is reduced as the tiers increase but since more missiles are shot the overall firing rate remains the same across tiers. Since the overall cooldown is the same all 3 tiers of swarms always aligns with the other missile modules so that swarm goes in first.

The rest of the changelog seems very accurate @wakystuf really well done.

**Comment by wakystuf** [comment]
@Doruk-Coskun Thanks! I updated my comment to include all your feedback and deleted all the questions except for the 2 that you said you're looking into. I'll read it again and then post later today, so that it isn't held up by those last 2 minor things

**Comment by wakystuf** [comment]
@Doruk-Coskun Just a reminder

**Comment by wakystuf** [comment]
@Doruk-Coskun Another reminder :)

**Comment by wakystuf** [comment]
@Doruk-Coskun
