### ISSUE TITLE
Investigate: Dual 2 Spiral Galaxy

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#318]

**Comment by Arpharnator** [comment]
what is this for?

**Comment by captaincobbs** [comment]
Mind your business

**Comment by Arpharnator** [comment]
I suppose you are the guy who kept changing my name

**Comment by captaincobbs** [comment]
No, I'm asleep, it couldn't be me

**Comment by Arpharnator** [comment]
who is on your account then

**Comment by captaincobbs** [comment]
Deemed impossible.

**Comment by wakystuf** [comment]
I assume this one was supposed to be tagged as Rejected? For now I will not plan to put on the wiki.

**Comment by captaincobbs** [comment]
Oops, yes it was rejected.
