### ISSUE TITLE
Pop collection buff

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#319]
Vaulters : 0.1 Science  per 1 ManpowerCapacity  -> 0.15 Science  per 1 ManpowerCapacity 
Lumeris : Untouched
Unfallen : +50% ownership recovery rate -> Bonus per Forest on Empire
Horatio : 5% Food  to Influence  -> 0.1% FIDSI  per Horatio on Empire

**Comment by Arpharnator** [comment]
Need to decide on Unfallen and Lumeris (to chaos' discretion)

**Comment by Arpharnator** [comment]
Unfallen : +50% ownership recovery rate -> +1% Empire Science per Fertile

**Comment by wakystuf** [comment]
It looks like the Lumeris are still open from the above; were the rest of these completed?

**Comment by captaincobbs** [comment]
Yes, Lumeris was ultimately left untouched, unfallen ended up with +1% science per fertile planet (which I don't agree with whatsoever but 🤷‍♀️)

**Comment by captaincobbs** [comment]
Got permission to change Unfallen to +1% Industry on Systems per Fertile Planet in Empire

**Comment by wakystuf** [comment]
Great; this one is now documented. From a balance perspective, it seems like the Lumeris still need some kind of help, but I don't have a specific suggestion.

**Comment by captaincobbs** [comment]
Lumeris definitely need help, though we're all at a loss as well.
