### ISSUE TITLE
Buff T2 luxuries

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#323]
They are in an wierd place because while you are supposed to run those for your T2 system development they don't give anything remotely interesting. Their numbers per pop are extremelly weak compared to most of the improvements that give per pop, and furthermore it requires you to ditch a slot from a potential T3 luxury.

**Comment by wakystuf** [comment]
My suspicion is that this one was supposed to be tagged as Rejected, but wanted to confirm?

For what it's worth, I think this is a good point, but not a huge problem. T2s have 3 things going for them:
1) They require fewer to upgrade than a T1 luxury, but are significantly more available than T3 luxuries
2) They stack multiplicatively with percentage bonuses (ex: F-Reality Institute, T3 luxuries), and get the benefit of "raw" multipliers (ex: Sophon Thermatech law, Craver Endless Consumption hero ability)
3) Diversification: they are another thing that one can use to avoid putting too much strain on supplies of T1 or T3 luxuries

**Comment by captaincobbs** [comment]
I'm not sure what ended up happening, let me ask

**Comment by captaincobbs** [comment]
This ended up being rejected.
