### ISSUE TITLE
Make Luxury/Strategic deposits inherently give a trade bonus

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#328]
Luxuries: +10 Trade Dust per Tier
Strategics: +10 Trade Science per Tier

**Comment by wakystuf** [comment]
What is the status of this one?

**Comment by captaincobbs** [comment]
Luxuries: +3 Trade Dust per Tier
Strategics: +10 Trade Science per Tier

**Comment by wakystuf** [comment]
"per Tier" in this case referring to the tier of the resource, the system, or the level of the trade company?

**Comment by captaincobbs** [comment]
Tier as in tier of the resource

**Comment by wakystuf** [comment]
Great; thanks. Documented

**Comment by wakystuf** [comment]
I just realized this comment had been updated; no fair! I updated the wiki though.
