### ISSUE TITLE
Making UI more descriptive of the game mechanics

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#332]
UI can be extended as we did for the Module Multiplier and Ship Level. Things need to be more descriptive:

Morale (What does it do, when does it apply)
Cross-lane accuracy
Flotilla-specific effects vs fleet-specific effects
Ship manpower (the bonuses at full/the detriments at none)
Battles with special node effects (indicate when they apply)
Which support modules stack with themselves

**Comment by captaincobbs** [comment]
What's the status with this?

**Comment by Arpharnator** [comment]
I think it's finished or smth, cuz I remember back in combat rework when chaos added descriptions to modules and their mechanics

**Comment by captaincobbs** [comment]
Lets be honest, this doesn't need to be open
