### ISSUE TITLE
Buffing Useless Minor Traits

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#339]
I would be glad if you can list the bad ones with screenshots as you did for the OP ones -Chaos

**Comment by Arpharnator** [comment]
die -kindly, arphar

**Comment by Arpharnator** [comment]
Haroshems : -10% pop food consumption

Amoeba : +10 inf per peace, +20 per alliance

Pilgrims : +5 science per anomaly (so if you have 5 it will give you 25, utter garbage)

Zvali : -25% diplomatic pressure on your empire

Tikanan : +100 manpower per turn

Eyder : 25 dust per hero

Baghaba : -10% peaceful treaty cost reduction per peace

Remnants : -20% ind wonder cost

Basryxo : -5% building cost reduction per peace

Illo : 40 inf per behemoth

Harmony : -20% dust upkeep of system per strategic deposit

**Comment by Down2Feed** [comment]
I beg to differ on that Tikanan benefit. It's amazing for the mp starved choir.

**Comment by Arpharnator** [comment]
the game ain't balanced around uc

**Comment by captaincobbs** [comment]
Suggestion, make the "per peace" and "per alliance" traits be "when in an alliance" or "when at peace"

Give it a strong bonus that doesn't scale, because that gives players on a bigger galaxy size more bonuses

**Comment by NoProblemWithThisAcc** [comment]
that's true arphar but having 'Ooo I want this' for 1 race in particular leads to maor fights, if that's our goal.

I'm fine with have a minor or two that each major might really want to eat

**Comment by Doruk-Coskun** [comment]
Haroshems : -10% -> -20% food consumption

Amoeba : +10 inf per peace, +20 per alliance

Pilgrims : +5 -> +20 science per anomaly (so if you have 5 it will give you 25, utter garbage)

Zvali : -25% diplomatic pressure on your empire

Tikanan : +100 manpower per turn -> +30 manpower per system per turn

Eyder : 25 dust per hero -> 80 dust per hero assigned as governor

Baghaba : -10% peaceful treaty cost reduction per peace

Remnants : -20% ind wonder cost -> -25% industry wonder and unique sys improvement cost

Basryxo : -5% building cost reduction per peace -> +10% production on systems

Illo : 40 inf per behemoth -> 40 influence and +5 approval per behemoth

Harmony : -20% dust upkeep of system per strategic deposit -> -25% upkeep cost on every system

**Comment by wakystuf** [comment]
My thoughts (I skipped a bunch where I simply agree with Chaos):
Haroshems' food consumption trait will matter more once 1.3.1 rolls out with higher food consumption requirements for everybody. Not sure quite how that will affect it, but worth considering.
Amoeba: Maybe +15 influence per system? That way at least you get the influence bubble benefit
Z'Vali: What about extra (double? Not sure if that's too much) pressure on other factions instead. That way you can use it eventually to make demands, so you can get something out of it
Tikanan: Isn't +30 MP/system/turn worse, since then not even the UC wants them? Or alternately, you could make it apply partially to sanctuaries? Not sure if that's doable
Illo: +5 approval per behemoth is a lot; it'll be like +30-40 by lategame, right? Maybe like +2 approval instead?

**Comment by Doruk-Coskun** [comment]
@Arpharnator is this done? This is done right?

**Comment by Doruk-Coskun** [comment]
> Tikanan: Isn't +30 MP/system/turn worse, since then not even the UC wants them? Or alternately, you could make it apply partially to sanctuaries? Not sure if that's doable
Illo: +5 approval per behemoth is a lot; it'll be like +30-40 by lategame, right? Maybe like +2 approval instead?

Game is not balanced around UC. Game is balanced and UC is adjusted accordingly. 
It is not that easy to get that many behemoths in an actual game. Most reasonable amount is 3-4 and its pretty late too.

**Comment by wakystuf** [comment]
That's all fair.

Maybe for the Tikanan, make them apply to sanctuaries, but only partially (like half credit or something)? I'm not sure if that's a pain to code though.

**Comment by captaincobbs** [comment]
Not a pain, just do ClassEmpire//ClassColonizedStarSystem

**Comment by Arpharnator** [comment]
should be done
