### ISSUE TITLE
Increased Pirate Node Spawn Range to 1-4 systems to prevent lag in games where systems are mostly controlled

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#34]

**Comment by wakystuf** [comment]
What exactly was this bug? And what were the prior values of node spawn?

**Comment by captaincobbs** [comment]
It was 2-3 systems, the bug was that the game wouldn't be able to find a system to spawn pirates within that range and it would cause slowdowns.

**Comment by wakystuf** [comment]
Got it. Does this mean then that the pirates can now spawn directly next to colonized systems? (I assume that node spawn is in reference to the # of star lanes to the closest major faction colonized system). Not necessarily a bad thing; just want to make sure I understand.

**Comment by captaincobbs** [comment]
Yes
