### ISSUE TITLE
Change Craver Unique Ground Pillage

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#350]
Rename Enslave
Description to be about Enslaving
Image to be craver loading screen

**Comment by Doruk-Coskun** [comment]
Pop steal action may be bugged and required to be checked

**Comment by Doruk-Coskun** [comment]
![image](https://user-images.githubusercontent.com/25507419/107146622-7670a900-695a-11eb-9f2f-9735a5ab954f.png)
 Works as intended

**Comment by wakystuf** [comment]
To avoid creating (even more) spam for you guys, I'll only ask this question once, but it applies to several other Issues as well: should this be tagged as Finished, or no? So far I've been filtering for Finished for what I put on the wiki, so I just want to make sure I'm not accidentally overlooking stuff that is simply missing the tag.

**Comment by captaincobbs** [comment]
Oops, if it's closed and not explicitly rejected, it's finished.

**Comment by wakystuf** [comment]
Sounds good. I'll add this one to my list to put on the wiki. For now tagging as Needs Documentation so that I know to come back to it.
