### ISSUE TITLE
Scale some turn dependent events

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#352]
(DONE) Hero injured duration
(DONE) System ownership change duration
(Can not be done) Vine kill duration
(DONE) Tree cutting duration

**Comment by wakystuf** [comment]
Does this scaling refer to scaling with respect to Gamespeed?

**Comment by Doruk-Coskun** [comment]
No, Guardian killing for non UF factions have been changed to 3 turns. Hero recovery on fast speed is reduced to 10 -> 8 and scales with gamespeed. System ownership change duration is 5 turns on Fast speed now.

**Comment by wakystuf** [comment]
OK, that's helpful. So to clarify:
-Sacred Harvest: 3 turns on all Gamespeeds
-Hero recovery: 8 turns on Fast, 16 on Normal, and so forth
-System ownership: 5 turns on fast, 10 on Normal, and so forth

**Comment by wakystuf** [comment]
I think this one is still open

**Comment by Doruk-Coskun** [comment]
> OK, that's helpful. So to clarify:
> -Sacred Harvest: 3 turns on all Gamespeeds
> -Hero recovery: 8 turns on Fast, 16 on Normal, and so forth
> -System ownership: 5 turns on fast, 10 on Normal, and so forth

That should be the case, yes

**Comment by wakystuf** [comment]
Great. Documented.
