### ISSUE TITLE
Planets are unable to have negative FIDSI or FIDS

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#358]
Planet FIDSI and FIDS are capped at 0, but Planet Food, Industry, Dust, Science, and Influence are able to be negative.

**Comment by wakystuf** [comment]
Can you clarify which of these is current vs prior state?

**Comment by captaincobbs** [comment]
Before this, if you had an anomaly that gave -1 FIDSI on the planet, it wouldn't do anything until you get a later effect that adds +1 FIDSI, because planet fidsi couldn't go lower than 0, meaning the fidsi couldn't be subtracted from each resource individually. With this, now they can.

**Comment by wakystuf** [comment]
OK, thanks. It sounds like this is an order of operations change; below is my proposed wording for the wiki:

Corrected order of operations for calculation of anomalies providing negative FIDS and FIDSI. Previously, FIDS and FIDSI effects were floored at 0 (separately from base Food, Industry, Dust, Science and Influence being floored at 0). Now FIDSI and FIDS effects will correctly apply to each subcomponent before testing relative to the floor of 0.

**Comment by captaincobbs** [comment]
yes, exactly

**Comment by wakystuf** [comment]
Great. Documented
