### ISSUE TITLE
Fix Manifest Destiny not working

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#388]
Doesn't allow colonization

**Comment by captaincobbs** [comment]
Fix: Delete manifest destiny

**Comment by wakystuf** [comment]
What exactly was this issue? Sounds like a bug fix of some sort

**Comment by captaincobbs** [comment]
It was a custom faction trait that never worked properly (lets you colonize with a turn requirement rather than industry requirement, unfallen use this)

**Comment by wakystuf** [comment]
Got it. I've added to the wiki and noted that the fix was to delete it.
