### ISSUE TITLE
Fix Riftborn Quest Reward Population Creation from consuming industry Surplus

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#391]

**Comment by wakystuf** [comment]
What does this mean? I remember previously there was a change to avoid Riftborn pop construction from blocking the queue (IE, it allowed overflow); was the completion of the -50% population cost quest causing an issue with that, or is this referring to something else?

**Comment by captaincobbs** [comment]
This is referring to the same things, but the quest variations of the constructible (-75% cost and -25% cost)

**Comment by wakystuf** [comment]
OK, I added to the wiki, but to clarify I had thought the quest reward (Chassis Optimization) was -50% cost? Was that changed in a separate part of the mod? If so I should probably add that to the wiki someplace as well.

**Comment by captaincobbs** [comment]
It wasn't changed, I just don't remember

**Comment by wakystuf** [comment]
OK, sounds good. I'll label as Documented.
