### ISSUE TITLE
Penalties from 'in others influence zone

### ISSUE THREAD

**Issue by Mermixer** [captaincobbs/ESG-Mod#401]
reduce the amount of dust/science lost when at peace/diplo pressure
no diplo pressure/loss of dust/science from allied influence zone
does the one doing the pressuring get the resources the other guy loses btw, maybe make that a thing

**Comment by Arpharnator** [comment]
Do you mean in alliance or in general

**Comment by Mermixer** [comment]
if im allied with someone i dont want to lose 200 science because im not an influence faction and he is
if im at peace with someone i dont want him to be able to make demand every 3 turns because hes an influence faction and i am not

**Comment by captaincobbs** [comment]
That's kind of the only real advantage of an influence faction though

**Comment by Arpharnator** [comment]
Well for alliance I think it should be removed yea

**Comment by Mermixer** [comment]
but then whats the point of cold war

**Comment by Mermixer** [comment]
also how does that interacti with unfallen vines
since theyre using their influence for force peacing, they already get their extra dmg no
they generate a lot of pressure with vines, which you can usually only stop with warring since he can afford force peace very easely no

**Comment by Arpharnator** [comment]
unfallen can't put vines on someones elses system in cold war

**Comment by Mermixer** [comment]
true, but i still regard them as an influence faction, and ulike ue they have nothing to really spend it on so they just force peace every couple turns, so no cold war for you, which will still cost you influence early on which some factions cant afford

**Comment by wakystuf** [comment]
In alliances it seems fine to remove it, but otherwise I'd leave it. Peace already applies a 50% reduction to pressure. 

The true remedy is simply to burn (or conquer) the system(s) causing the issue. In general, the UE and Unfallen aren't very threatening (though Chaos' rework seems like it will help a lot for the UE, it's taking them from terrible to respectable).

**Comment by wakystuf** [comment]
I have no idea how to fix this, but in the case of alliances it does seem like it should be fixed. Does anyone know how to fix this?

**Comment by captaincobbs** [comment]
I've completely removed the penalty, but it's easy to change that if you want it to be like -10% (It's base -25% Money, Influence, Science). Also, there's no distinction between peace and alliance.
