### ISSUE TITLE
RB nerf + Horatio Quest changes

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#402]
Creating a new issue for this, since I didn't see one; this way I can keep track to make sure it gets documented.

Apologies in advance if this is duplicative with an Issue someplace else.

**Comment by wakystuf** [comment]
These are documented:
RB Nerfs:
-Pop: 5 to 2 dust per pop
-Biophobic: +10/-2 on Sterile/Fertile to +8/-3 (no change to pop slots)
-Ind law 1: From 10/15 ind per outpost to 5/10
-Final quest reward (Backlash/crush chapter) from +4 ind per pop to +3
-Final quest reward (Backlash/appease chapter) from +3 strat per deposit to +2

Horatio changes:
-Price of perfection II colony ship cost increase cut in half from +20% to +10%
-Price of perfection I colony ship cost increase grown from +10% to +50% (I suspect this is an error and was intended to be reduced to 5%?)

This is the open part:
-Some other Horatio-specific thing that I don't understand, since I never play them. Something to do with cloning or pop conversion?

**Comment by wakystuf** [comment]
OK, I think this one looks like the following:
Lowered cost of Genetic Alteration Lab to 200 on all Gamespeeds

Does that sound correct?

**Comment by wakystuf** [comment]
@Arpharnator I think this one is still open for you

**Comment by Arpharnator** [comment]
aaaaaaaaaa
yes should be 200 on all gamespeed

**Comment by wakystuf** [comment]
OK, thanks. Documented
