### ISSUE TITLE
Buffed Curiosity Star System Improvements

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#403]
I didn't see an Issue for the buffs to the curiosity-buildings either. It looks like they are the following; can someone please confirm?
Analytical Engine: From +1 dust per curiosity to +3
Rejuvenation Maze: From +20% healing to +30%
Vault of Governance: From +50% to +100% hero XP
Lunar Surveillance Station: From +15 to +100 science per moon

**Comment by Doruk-Coskun** [comment]
That sounds right yes. Lunar is actually 125 science

**Comment by wakystuf** [comment]
OK, thanks. I'm guessing I'll find that in a later part of the code as I continue to go through it :)

Related to the curiosity buildings question I had before, it looks like this now makes further changes:
-Rejuvenation Maze: buffed again from 30% to 50% healing
-Vault of Governance is no longer a unique building? IE, it can be built on multiple systems? (That's really good if so; maybe should be moved to the tech tree instead of a curiosity if it's going to be that good)

**Comment by Doruk-Coskun** [comment]
@wakystuf I might have buffed Rejuvenation Maze to 50% that's possible. Vault of Governance is not a unique improvement anymore and it's pretty good ye. Moving it is an interesting idea actually maybe we can think about it for the future

**Comment by wakystuf** [comment]
Great. Documented. I'll add the Vault topic as a proposal then, so that I can label this as Documented
