### ISSUE TITLE
Horatio ind quest fix

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#409]
I couldn't tell what this one was.

Not sure if this linked correctly but this is my attempt to link to the commit:
 #392

**Comment by Doruk-Coskun** [comment]
Horatio industry questline at one point requires you to spend 100 adamantium on a curio search to progress which is insane. Arphar made it more sensible by making the requirement 20 adamantium

**Comment by wakystuf** [comment]
I believe Arpharnator mentioned it was antimatter, not adamantian (and the code seems to refer to Strategic4, which I believe is antimatter), but let me know if that is incorrect and I can update on the wiki. For now I'm relabeling this as Documented to take it off my list.
