### ISSUE TITLE
Make Ship Upkeep scale with Level

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#416]
Make dust more important as a resource for militarist factions, so militarists can't ignore dust

**Comment by Arpharnator** [comment]
why

**Comment by captaincobbs** [comment]
Upkeep of Fleets will probably be increased

**Comment by wakystuf** [comment]
I'll take care of this

**Comment by wakystuf** [comment]
This is done. +10% upkeep per level.
Also fixed vanilla bug where squadron modules don't have any upkeep.
