### ISSUE TITLE
Reduce T5 vodyani Ark FIDSI module strat cost

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#424]
From 5 base to 2 T4
Arks have a 4 multiplier, as such that 5 turns into 20 for a single module.
Reducing it to 2 makes it far more affordable and usable.

**Comment by captaincobbs** [comment]
Proposal was accepted by Angry and I

**Comment by captaincobbs** [comment]
It should be noted that Vodyani buffs aren't usually a good idea, but this is one of the few cases where it is acceptable

**Comment by Eighth-of-Third** [comment]
These specific modules once didn't cost any strats and they were really OP. The current cost of 5 each might be a bit much, but these modules are extremely powerful if you can get a lot of them.

**Comment by wakystuf** [comment]
Yeah, I agree with all of that. Vodyani are one of my favorite factions, and I usually don't even bother to research these techs because I can't afford the strats. Those costs are unreal.

**Comment by wakystuf** [comment]
I should note that my metagame with my friends is more or less a mostly-peaceful FIDS-race, and I *still* can't afford the strategics (this is why my knowledge of combat things is fairly poor).

**Comment by captaincobbs** [comment]
I think these were overnerfed

**Comment by Arpharnator** [comment]
3 T3 strat per module
