### ISSUE TITLE
Move Sim Camp to a technology

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#435]
It's essential for multiple factions, and just generally too good to be on a curiosity.

**Comment by wakystuf** [comment]
I agree with this

**Comment by Neiwun** [comment]
Sounds good to me :)

**Comment by captaincobbs** [comment]
Which technology is it getting moved to?

**Comment by wakystuf** [comment]
N-Way Fusion

**Comment by captaincobbs** [comment]
Gonna keep this open for a bit to confirm it works in testing

**Comment by wakystuf** [comment]
Oh, sure, no problem

**Comment by Arpharnator** [comment]
works ofc
