### ISSUE TITLE
Lumeris Rework

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#438]
These come from the suggestion of Koxsos:
### Ideas:
* ES1 Sheredyn Style building that imposes a sharp penalty on the system during construction, but give a strong bonus (such as 150 dust)
* Add a way to purchase permanent buffs to all ships
* Specialize Trade Company HQs into also providing Science, Manpower, Industry, and Influence
* Vastly increase Lumeris's ability to create Trade Value
* Quest Rework (specifically to make the Military route worth using)
* Increase the availability of subsidiaries, to ideally make every system a subsidiary (+1 Subsidiaries per level 2 systems or +1 per tech researched?)

**Comment by wakystuf** [comment]
These seem like good ideas. However, the Lumeris are so bad now that I think they need more if they are going to compete with the Hissho, Vodo, Riftborn, etc.

To that end, a few other ideas as well:
* Pop collection bonus could provide additional passive trade-to-FIDS
* Give them some version of UC-style trade, where all colonies are automatically trade subsidiaries. So all colonies automatically build one, or maybe they just have the ability to spam them for 0 production (and there's no cap on # of subs for them). If that becomes too OP, then we can nerf their trade yields, similar to the UC.
* Additional buyout cost reductions that scale with either quest progress, pop collection bonuses, or system levels.

**Comment by captaincobbs** [comment]
I like your collection bonus idea, I'll note that down

UC style trade isn't possible from what I can see.

They can already get 95% Buyout Reduction fairly easily, I don't think that's an area they need help in.

**Comment by wakystuf** [comment]
Well, UC-style trade might be possible to implement through workarounds:
1) Remove the cap on the # of subsidiaries (there's already a tech for +2, so I would think that could be converted into a faction trait for +999 or something).
2) Make their subsidiaries cost only like 1 production

**Comment by captaincobbs** [comment]
Oo, removing their subsidiary cap would be a great idea. I don't think reducing the cost of subsidiaries would be a good idea since the "Specialize Trade Company HQs into also providing Science, Manpower, Industry, and Influence" would probably extend to also providing subsidiaries with a lesser version of this bonus, but letting them put a subsidiary on every system would be a great way to increase their trade value without doing any complicated math.

How about +1 Trade Subsidiary per Level 2 system? It would encourage trading to get luxuries, and would tie in nicely.

**Comment by wakystuf** [comment]
Yeah, that's a good idea; I agree with that one. Is there a way to also exempt them from the trade route cannibalization thing? I forget how that works.

**Comment by captaincobbs** [comment]
No but it's not really an issue, the highest amount of dust or science I've seen is like 8

**Comment by captaincobbs** [comment]
I've seen nothing about the code relating to this so it might be hard coded anyways

**Comment by Arpharnator** [comment]
Making every system a subsidiary would result in an absolutely decadent amount of money, remember UC can't develop systems and yet their yields are very high, despite the -50%. At the end of the day tho, if it actually helps the Families wins their actual win condition then yea sure.

**Comment by wakystuf** [comment]
Yeah, I agree; they might then also need some nerf to the yields. But if we end up needing to nerf them, then I think that's a sign of a job well-done, since they are so bad in vanilla.

**Comment by captaincobbs** [comment]
Lol they'd need it

**Comment by NingaublesEyes** [comment]
From the discord a user, CourierSix, had the following suggestion, which may be implausible: I don't know if this is possible, but it'd be cool if Lumeris could spend dust to bribe invading fleets/ground forces to piss off - It'd help their pacifistic mercantile nature if invasion plans had to account for lumeris just spending dust to "confuse fleets" and "disorientate soldiers"

**Comment by NingaublesEyes** [comment]
Maybe an affiliation bonus that they get (X) or (%X) influence whenever they buyout things?

**Comment by NingaublesEyes** [comment]
Personally I feel like they need a gambling mechanic. But I have no specific ideas. 

Has anyone had luck making them primarily industrialist? Or is the pacifism too good a safety net/fall back.

**Comment by NingaublesEyes** [comment]
Wildly spit balling here I wonder if - rewriting their fluff just a little bit like, "They have an almost religious devotion to commerce." and instead of pacifism ... making their output religious? Make them a faction that may prefer being in a cold war / neutral?

**Comment by Mermixer** [comment]
i dont think religious is good for a faction that wants to trade with everything that moves
honestly paying pirates to fk off of a system sounds like an interesting idea for all, but those pirate lairs die fast if you want them to die

**Comment by NingaublesEyes** [comment]
Yeah if anything they seem like a faction that should be able to gain a trading relationship with them.

**Comment by wakystuf** [comment]
My thoughts:
1a) "Bribing" invading fleets and/or ground forces might actually semi-doable through adding a unique ground and/or space battle tactic.  We could set it up to require X dust per enemy CP, and  then triggering some effect (ex: force damage to 0 on both fleets). That could be cool, though we'd have to be careful to make sure it didn't become OP (probably by making the dust cost very high).
1b) I suspect that killing a pirate lair with dust won't be possible, but I'm not sure. I also agree with Merm that they usually aren't that hard to kill anyway.
2) I'm not sure if happiness from buyouts is doable, but if so then it seems like it'd be fine. Doesn't help solve their fundamental problem, but could be a thematically appropriate random bonus to give them.
3) The gambling seems likely to just make turns take longer, but if you wanted you might be able to spawn a bunch of lumeris-only (quest) curiosities which consume dust to explore and provide random rewards (some of which will be lower than the dust cost to explore, thereby losing money).
4) I agree with Merm on the political output; I'd leave it alone. Also, most of the trade-related buildings are pacifist, so it'd be weird for the Lumeris to not respond disproportionately to those constructions.

**Comment by NingaublesEyes** [comment]
2) Yeah. I tend to try to lean into the theming/experience a bit more. I don't mind if a faction isn't the beez knees but if it could be more fun. 

3) Maybe as a final reward for completing their quest. Again, it's not going to fix anything but it might be something fun at least. Hah. Uhm. Hmm. 

4) Oh yea! Dur.

**Comment by Mermixer** [comment]
if i get approval from buyouts i will buy out 0 module scouts whenever i need it
dont add that ever itd be busted

**Comment by NingaublesEyes** [comment]
Hahaha I was just coming back to say that it wouldn't be balanced. Haha.

**Comment by NingaublesEyes** [comment]
So I know the focus is on balance and I think this is a weird idea but ... what if you could sell a Minor Faction to the Academy. Like the way the Nakalem can 'influence/gift' a major faction to the Academy? I really don't see it adding a lot to the game. But I guess I'm still wondering if there's something out side of the box that they could get to give them a unique gameplay. 

Maybe ... being in an alliance with the Families grants everyone in that alliance the option to use Corsairs? Like. Uhm. Like their they could be the Endless Universe interpretation of the Orion Syndicate from Star Trek? A loose confederation of criminals that are just powerful enough and well connected enough to afford the political clout to hire privateers from.

Oh or maybe they could gain ... vision from any recruited mercenary ships. Or do you play with those turned off in multiplayer?

**Comment by NingaublesEyes** [comment]
Hmm. Maybe if they get into a non-aggression alliance they gain vision of all the pirate systems. They have that kind of lame quest where they are trying to gain vision of 50% of the universe. Does it have a particullary good quest chain reward?

**Comment by Arpharnator** [comment]
> So I know the focus is on balance and I think this is a weird idea but ... what if you could sell a Minor Faction to the Academy. Like the way the Nakalem can 'influence/gift' a major faction to the Academy? I really don't see it adding a lot to the game. But I guess I'm still wondering if there's something out side of the box that they could get to give them a unique gameplay.
> 
> Maybe ... being in an alliance with the Families grants everyone in that alliance the option to use Corsairs? Like. Uhm. Like their they could be the Endless Universe interpretation of the Orion Syndicate from Star Trek? A loose confederation of criminals that are just powerful enough and well connected enough to afford the political clout to hire privateers from.
> 
> Oh or maybe they could gain ... vision from any recruited mercenary ships. Or do you play with those turned off in multiplayer?

nakalim style conversion is not really doable in the modding.

Merc ships do not matter in mp, they are too badly outfitted to be of any use, and then you have the problem of vaulters already doing just that.

**Comment by captaincobbs** [comment]
> I don't know if this is possible, but it'd be cool if Lumeris could spend dust to bribe invading fleets/ground forces to piss off - It'd help their pacifistic mercantile nature if invasion plans had to account for lumeris just spending dust to "confuse fleets" and "disorientate soldiers"

I like this, but I can't add new mechanics. I agree they should rely on manipulation rather than brute force though, I just can't really give them any way to do that.

> Maybe they could get a unique bonus of just +5 system happiness for 5 turns, anytime you buy something out on the system. Or instead of a cumulative bonus a one time bonus of +15.

I can't make events that trigger from buyouts, I can only make events that trigger while the item is in queue.

> Yeah if anything they seem like a faction that should be able to gain a trading relationship with them. Like they might with a minor faction. Is increased gains from Pirate Marks a thing?

I can only make the pirate marks benefit the pirates, and there is a concept being thrown around to give them "Trade Agreements during War"

> We could set it up to require X dust per enemy CP

We've found that any battle tactic that uses "x cost per CP" or any cost whatsoever will not work, because you are not locked out of using the battle tactic if you can't meet the resource demand.

> So I know the focus is on balance and I think this is a weird idea but ... what if you could sell a Minor Faction to the Academy. Like the way the Nakalem can 'influence/gift' a major faction to the Academy? I really don't see it adding a lot to the game. But I guess I'm still wondering if there's something out side of the box that they could get to give them a unique gameplay.

Not possible, and I'd prefer to not make trans-DLC mechanics like that even if I could.


My main problem in the Lumeris rework is that they don't really have anything interesting that I could make cooler haha

**Comment by Arpharnator** [comment]
> Add a way to purchase permanent buffs to all ships

How about making their ships have buffs based on % to eco victory?

**Comment by captaincobbs** [comment]
Hm, I'd prefer to make the choice active so that Lumeris are more interesting.

**Comment by Arpharnator** [comment]
Btw what would be the scale of the ships buffs? like 10% or something more

**Comment by captaincobbs** [comment]
Probably like, spend 1000^(2+number of upgrades purchase) and get +x health on all ships (permanent bonus)
It's repeatable, gets expensive very very fast, and is interesting

**Comment by captaincobbs** [comment]
Lumeris can pump out lots of terrible ships, so this would make them able to at least compete militarily in most situations, and it's an interesting and unique way to spend dust that encourages them to actually want dust.

**Comment by NingaublesEyes** [comment]
Yeah I don't know I've only played them a bit but have to agree. They don't exactly ... do anything. 

Allowing them to basically always trade comes close to giving them a unique ability. It's still passive. 
They have very little to do early on. It seems all built around making a passive system work better. 

The ability to pay off an invading fleet comes closest to a unique ability but I don't know if that could be added. 

Spinning off Arpharnator's idea ... maybe a unique passive for their troops - "Paid Protection." which grants them some kind of buff based on percent of econ victory. This is still pretty passive - with more mid to late game bonuses again. 

I think that idea of a permanent buff you could buy. "Big Fish" 1000 dust - gain the bonus (on all built ships) might be good. It might also be a pain to balance but again, this is, something to build towards and might as a way to give you gains for building an earlier econ.

**Comment by Mermixer** [comment]
how about lumeris gets to trade with EVERYONES trading comp without getting blockaded but they only have like 50% efficiency, you know for the whole black market vibe

**Comment by NingaublesEyes** [comment]
An ability to grant loans to players? Eh. Probably not possible. Sigh. What could have been.

**Comment by NingaublesEyes** [comment]
Okay I couldn't help it. I'll be mucking around with a customized version. Ecologist / Biologist / Anti-military. Same collection bonus. Tweaked traits (gluttonous is -10 for point balance and I'm sorry it's totally appropriate). The big change is just FIDSI per system level and -.5 depletion (again for balance and their fluff makes me think of human excesses as well, profit and comforts). Their ecologists less as preservationists and more as opportunists and to reflect their ethos of adaptability. Their minor race I changed to the Sefalos but I think the Amblyr might be more fitting. I noticed that blockade busters is costs 20 points, but maybe that'd be something you could give them as an inherent trait - it's still passive but it seems somewhat appropriate to all their fluff.

**Comment by NingaublesEyes** [comment]
I think makes for a better faction. I'll double check I have the details right after I regain consciousness. I might try streaming for a bit around 1 am. It won't have the changed starting anomalies. They have a more industrial slant both to reflect the "Epicurean" principles which I think are meant to reflect ... "Work hard, play hard, market efficiencies will out once the Families take their cut." 

![20210421113137_1](https://user-images.githubusercontent.com/52173864/115603649-449e8b80-a295-11eb-8394-dcedbf329774.jpg)  In some ways I think might now better reflect a sort of "Modern (20th / 21st century) Human" civilization if it managed to make it into space. I really liked the idea of them slowly depleting planets from capitalist excess but I think these population traits are both strong / balanced (cost 50% more to get +2 FIDS) and appropriate - developing systems gives you a double whammy and by having them gain dust from this lets you get a lot more bang for your buck so to speak. I feel like it gives them an adequate growth curve.

**Comment by NingaublesEyes** [comment]
Population is 1 FIDS & +2 or 3 dust per system level. I'll double check later.

**Comment by wakystuf** [comment]
One other thought based the conversation earlier today about buyouts: If we make the normal buyout reduction threshold higher (maybe 75%, or whatever) then we can give the Lumeris a higher cap (ex: 90% or something). Just another idea for their rework

**Comment by NingaublesEyes** [comment]
Cool.

**Comment by captaincobbs** [comment]
This is planned for 1.4

**Comment by wakystuf** [comment]
@Arpharnator already completed this. And by "completed" I mean indicated that it may not be necessary with the overall economy rework.

**Comment by NingaublesEyes** [comment]
Played some of 1.4 with Lumeris. Their just ... boring, and, seem weaker. Even with a rebalanced economy it's just unfortunate that they don't do anything. If they'd had a more complete redesign maybe - like starting with a HQ and subsidiaries in all the enemy factions ... and spreading influence through trade instead of a bubble. Even that ... is just passive. Except that you'd have "more" knowledge like the Draken do in EL. I'd almost go so far as to suggest skipping any work to rebalance them.
