### ISSUE TITLE
Double Base Trade HQ Output (both Luxury and Dust)

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#44]
Doubled the multiplier for both, hopefully it works

**Comment by wakystuf** [comment]
Is there any way to tell whether this is working or not? Currently I'm not even sure what the formula is for Star System Trade Value.

**Comment by wakystuf** [comment]
I think this one is still open

**Comment by captaincobbs** [comment]
Trade Value is just a multiplier to raw income. I have no idea what the full formula is either since it's scattered across large chunks of code.

**Comment by wakystuf** [comment]
So basically this change is vanilla drift buds everywhere, all the time?
AKA, [Black box of Star System Trade Value] x 2?

**Comment by captaincobbs** [comment]
Yes, basically, but this was removed in 1.3.1 because trade companies scaled too quickly.

**Comment by wakystuf** [comment]
Good to know. I'll note that on the wiki.

Does that mean that Drift Buds are being restored to their +100% trade value in the luxury rebalance?

**Comment by captaincobbs** [comment]
Nope, "vanilla" is +50% (very powerful), ESG is +10% trade value and buyout cost reduction per system level.
