### ISSUE TITLE
Buff lategame influence buildings

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#440]
Buff: 
- Language Institute from 5% inf -> 2 inf per pop, 15% inf. Reduce cost to 20 antimatter
- Intergalactic Lectures from +10% inf in Alliance, 5% inf in Peace -> 20% inf per Alliance, 10% per Peace, 2 inf per pop. Cost 
  remains the same.

**Comment by NingaublesEyes** [comment]
That seems a little obscene but also desirable. 
Language Institute gains +5% influence from peace or an alliance and +2 Inf per population. Cost reduction seems good.

Change Intergalactic Lectures to two separate buildings.
Intergalactic Conferences (+10% for every Empire at peace with you) +15 inf per system level (20 oric) 2020 ind
Intergalactic Coalition (+15% for every Empire in your alliance) +15 inf per system level (20 quad) 2020 ind

**Comment by Mermixer** [comment]
i dislike being forced into going for alliance to be able to use influence buildings
i think both nakalim (lul) and ue should be more than able to win games without having to ally, but if you even make the t4 buildings depend on that its just not good xd
its like saying that f-reality should be 5% science per cold war, 10% per war or something to bring it more in line with battlefield

**Comment by NingaublesEyes** [comment]
That was a little bit my thinking as well. 

This was finished, what changes got made?

**Comment by wakystuf** [comment]
I think it's just what @Arpharnator listed above. Once things are Closed, that's usually when I go through and document them on the wiki, and tag as Documented.

On that note, @Arpharnator , should this be Closed?

**Comment by Arpharnator** [comment]
yea
