### ISSUE TITLE
Sieging and Ground Invasion Rework

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#441]
- Make it so that not the whole fleet manpower is deployed (Manpower over 25% of the fleets manpower cap is deployed. Or only the amount required for that turns ground battle is deployed)
- Defensive improvements are underpowered and in later stages of the game are not impactful.
- Possibly balance between infantry tanks and planes should be emphasized

**Comment by captaincobbs** [comment]
Wouldn't this give a MAJOR advantage to the defender?

**Comment by Mermixer** [comment]
i wouldnt mind giving a bigger defenders advantage, you already get fked by having the fights in your territory (reduced pop growth, no strategics, potential for colony loss, invasions kill your pop and buildings)

**Comment by Mermixer** [comment]
for something where the difference could be 1-2 turns who starts invading who i dont mind it at all

**Comment by captaincobbs** [comment]
If you are gonna make crazy changes please tie it behind a setting

**Comment by Doruk-Coskun** [comment]
what gives major advantage to the defender I don't get? These are all the things discussed over multiple times already

**Comment by Doruk-Coskun** [comment]
Currently you have a death fleet with 6k manpower one shotting every invasion, razing the system and moving on to the next system. Removing that is one of the priorities no doubt.

**Comment by captaincobbs** [comment]
You'll have to test it to make sure that it's still playable lol

**Comment by Arpharnator** [comment]
I guess the goal of these changes is to make ppl able to use pods again right

**Comment by Mermixer** [comment]
fk pods, we rather want to use them for (more) intended purposes of hitting retreating fleets and maybe yoiking 3-4 ships, not oneshot your invading fleet on the first system

**Comment by Arpharnator** [comment]
Defender should be able to always deploy the maximum of its troops during a ground battle imo

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/117511980-fd9be000-af8e-11eb-878c-26a407ab505a.png)
becomes 350 max mp
![image](https://user-images.githubusercontent.com/49691625/117512004-0c829280-af8f-11eb-8096-1f974af5788c.png)
becomes 500mp
![image](https://user-images.githubusercontent.com/49691625/117512019-11474680-af8f-11eb-86ac-0b03ef5bf34f.png)
becomes 500 mp, doubled dmg
![image](https://user-images.githubusercontent.com/49691625/117512039-186e5480-af8f-11eb-92ae-aa8645692d6f.png)
becomes 5k mp, reduced cost
![image](https://user-images.githubusercontent.com/49691625/117512054-20c68f80-af8f-11eb-9d6b-eb202e508cd1.png)
becomes 1k mp, add reduced destruction
Baseline for a colony becomes 500 mp

Most pops that have max mp or ground battle dmg will see their attributes doubled
Faction specific buildings have yet to be specified
Quest buildings have yet to be specified
Siege modules will be made better

The defender will always deploy all its troops in battle
The attacker will only deploy the amount of troops he has capacity for, the rest will stay in the ships

**Comment by Mermixer** [comment]
uc dies a little more inside looking at these buildings~~~~
or maybe new manpowergeneration helps a little

**Comment by Mermixer** [comment]
btw how does all this tie in with sim camp being availible turn 1 (if you start with that t1 military tech anyways ;-;

**Comment by Arpharnator** [comment]
Can someone try to do the thing with the attacker ships dumping all of their manpower thus having their ships be at 0 manpower?

Like make it so they instead deploy ust what is necessary for this one battle and then keep what is not deployed inside their ships.

**Comment by Mermixer** [comment]
Still, you get 185 (500+350+500+500) industry for building the t1 and 2 buildings, and those techs give u sim camp. Compare that to the 85 youd get usually

**Comment by Mermixer** [comment]
Also due to how much manpower (and strength of that manpower) you get, depending on if your faction is able to make enough you can get super defensive aswell. Guess i will only invade once i have planes now.
Btw can unique improvements be destroyed by invasion? Seems like an important thing that they will not be, so that multimind combat doesnt get nuked.... Wanna bet ill also make more core crackers xd

**Comment by wakystuf** [comment]
Well the whole point is to make defensive MP buildings much better, since currently they just get wiped in like 1 turn by a proper invasion fleet.

It's a good question on the unique improvements; I'm not sure. We could probably make Multi-Mind indesctructible, if we wanted to
