### ISSUE TITLE
System Improvement Effect and Cost Rework

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#442]

**Comment by Arpharnator** [comment]
what this for?

**Comment by wakystuf** [comment]
I just added a draft version of most of this, but can tinker more if people have other ideas.

I also need to create a localization pair for the UC building; for some reason the one I tried was causing crashes. Will investigate tomorrow.

**Comment by Arpharnator** [comment]
btw doing stuff in smaller parts is usually better because otherwise when someone makes a small change, you can wind up getting problems with a future merge

**Comment by wakystuf** [comment]
OK, made another attempt at this one, with a diff that is now more accurate since all the reorganization was completed in a prior pull request. This diff still looks like I changed more stuff than I did though, since I lined up indentation for a few buildings (3-4 trade buildings plus Dark Matter) that Github now thinks I deleted and then re-added.

I will still need to figure out the localization thing with the UC version, but I'll do that later.

**Comment by wakystuf** [comment]
OK, I think this one should be all set now. @Doruk-Coskun were you originally intending for this to also capture non-FIDS (defense, behemoth-C4, etc) buildings, or should I close this?

**Comment by Arpharnator** [comment]
keep it open for now but label it as finished so that if we encounter bug we can add them to this issue

**Comment by Arpharnator** [comment]
RB Intergalactic Supermarket bugged, only giving 25 dust instead of 50.

**Comment by wakystuf** [comment]
Do they have their own version of the building that I just forgot about, or is it something else?

**Comment by Arpharnator** [comment]
they have their own version of the building

**Comment by wakystuf** [comment]
This should now be fixed

**Comment by Arpharnator** [comment]
UC versions of some buildings that haven't been changed but should :
![image](https://user-images.githubusercontent.com/49691625/117153641-76e2d980-adbb-11eb-96bf-0c03d17f8323.png)

![image](https://user-images.githubusercontent.com/49691625/117154046-ccb78180-adbb-11eb-9ce5-4a55d4531d32.png)

**Comment by wakystuf** [comment]
Oh, I thought those were already fine in vanilla. They run through the sanctuaries so they are already pretty powerful

**Comment by Arpharnator** [comment]
they are a bit too costly on the strategic side of things, it's not easy for uc to acquire a lot of strategics, especially antimatter since a bunch of buildings already need it

**Comment by wakystuf** [comment]
OK, fair enough. I'll reduce the strat costs to match what we did for the "normal" versions of each building

**Comment by wakystuf** [comment]
OK, I just created a pull request that should fix these, along with the UC versions of Predictive Logistics and Xhiyun
