### ISSUE TITLE
Xenotourism Agencies, Pulvis Production buffs, Colonial Exchange buff, Careful Sweeping buff, epigenetic crop seeding buff

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#446]
Xenotourism Agencies -> 3/3 dust per pop
Pulvis Production -> 4 dust per pop
Colonial Exchange -> 3 dust per pop
Careful Sweeping -> 15 dust per sd, 5% dust per sd, cost is 5 antimatter.
Epigenetic Crop Seeding -> 3 food per pop, +5 food per sd level

**Comment by NingaublesEyes** [comment]
I like the idea of buffing Xenotourism but 3/3 seems a bit strong, why not 2/2 + 1 dust p/luxury?

Would there be a way to boost Pulvis Production based on ship xp buildings already built? 4/4 also seems high. 

Maybe I never understood this game and your mod is like another layer of inaccessible confusion.

**Comment by wakystuf** [comment]
Xeno is really quite bad now. Compare vs the T1 industry building (which costs half as much, is on the same tech as hyperium mining, and industry > dust). It's 1/3 now, so it's just an extra +2.

Pulvis production isn't related to ship XP; it's buyouts and +2 dust per pop. This doubles the bonus
