### ISSUE TITLE
Dark Matter Institute, Punctuated Evolution Foundation buffs

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#447]
Dark Matter Institute : 150 Science per sd level, +25 per anomaly. Cost 4240 on normal, 2120 on fast, 25 antimatter.
Punctuated Evolution Foundation : +2/5/5 Science   per Pop on Pop/Fertile/Cold

**Comment by wakystuf** [comment]
I think Punctuated Evolution Foundation was also going to have cost reduced to 2k on Normal, 1k on fast. At least that's what I put in the spreadsheet and I didn't realize anybody disagreed

**Comment by Arpharnator** [comment]
what you put in the spreadsheet is 1120 on normal, and as such 560 on fast
I think I'll keep the cost as is for now and see where this goes once we play with it

**Comment by wakystuf** [comment]
I went ahead and took care of this

**Comment by Arpharnator** [comment]
since it would seem you based your work on main I denied the pull request, I'm going to take care of it
