### ISSUE TITLE
lessen rng start by making 1 and 2 planet systems disappear/much rarer and increase fertile planets likelihood

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#464]
title
based on a discussion with merm

**Comment by captaincobbs** [comment]
No, it makes the terrain varied and interesting, not every system needs to be amazing

**Comment by Arpharnator** [comment]
I don't need every system to be amzing, I need them to be relevant

**Comment by captaincobbs** [comment]
Use a separate mod

**Comment by Arpharnator** [comment]
make it togglable

**Comment by captaincobbs** [comment]
Not possible, I tried

**Comment by Arpharnator** [comment]
I still stand by that, also because normally spawned fertile planets are more likely to be small

**Comment by wakystuf** [comment]
Cobbs said no to this like 2 weeks ago so I'm closing it. If Arphar wants to continue to fight about it, then that's fine; I'm just trying to clean out the stale issues
