### ISSUE TITLE
Econ Rework, Part I

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#469]
Greatly reduce inflation scaling, and tiny bit reduce buyout cost scaling and fixed cost
Fix hero market (greatly increase hero cost and increase spawn rate)
Cap buyout reduction at 75%
Apply reduced inflation scaling to market tradeables

**Comment by Arpharnator** [comment]
This dust biff is noticeable, and buyouts are something that are really feeling good (if not slightly too powerful), gj

**Comment by wakystuf** [comment]
Great!

**Comment by Arpharnator** [comment]
works
