### ISSUE TITLE
Econ Rework, Part II

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#470]
Fix trade scaling so that other forms of dust production actually matter
Increase upkeeps so that dust is not optional

**Comment by captaincobbs** [comment]
Tied to #385?

**Comment by wakystuf** [comment]
Nah, that's like Part III :)

**Comment by Arpharnator** [comment]
The reduced dust obtained from trading feels more in line, and the luxury increase keep it in line, so I'd say that this is pretty good change.
