### ISSUE TITLE
Make "Normal" Terraforming Cheaper

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#472]
Flat 560 cost for all terraforming, instead of dramatically scaling up later.
Factions that don't benefit: Vodyani (no terraforming), Riftborn (non-standard terraforming), Hissho (only like 3 planets to terraform), UC (non-standard terraforming), Cravers (probably not worth long-term investing in the systems)
Factions that benefit: Everybody else

Thoughts?

**Comment by Arpharnator** [comment]
I would only touch some of the terraformations, namely when you start to terraform into Savannah/Steppes/Monsoon. These cost a lot and do not provide any value whatsoever.

**Comment by wakystuf** [comment]
Yeah, those are the worst. But some of the other later ones to add the fertile tag (ex: Monsoon to Forest) are crazy expensive, so I'd probably also reduce those as well, since the only factions that would benefit are the non-top-tier ones.

**Comment by Arpharnator** [comment]
works
