### ISSUE TITLE
System dev bonus broken again

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#477]
does not give system bonuses, but does give the luxury bonuses and empire ones (bandwidth) and gives the vision range.

**Comment by captaincobbs** [comment]
Can you go into the simulation viewer and check if the system property "LuxuryReworkEnabled" is 1?

**Comment by Arpharnator** [comment]
it is 1

**Comment by captaincobbs** [comment]
And can you for sure confirm this, I really really don't want to look at the code. Like, look at the simulation view and see if the constructible is adding anything

**Comment by Arpharnator** [comment]
constructible?

**Comment by captaincobbs** [comment]
The building object added to the system

**Comment by Arpharnator** [comment]
The problem takes place in 1.3.2 and it would seem that SystemFIDSIFlatDevelopment, PlanetRawFIDSIDevelopment and SystemFIDSIPercentDevelopment are not even being created, but for no apparent reason

**Comment by Arpharnator** [comment]
To be more precise it seems that it's more about this :
<Modifier       TargetProperty="SystemGrowth"       Operation="Addition"        Value="$(SystemFIDSIFlatDevelopment)"                      Path="ClassStarSystem"/>
not even taking place, and not about the stuff I stated earlier not being loaded

**Comment by Arpharnator** [comment]
I suspect it might have something to do with the recent commit I made to pirates

**Comment by Arpharnator** [comment]
nvm I think I found the source of the problem
it's because waki created SimulationDescriptors[StarSystem] which caused the stuff that was for that in [ColonizedStarSystem] to not be useful once again

**Comment by Arpharnator** [comment]
Somebody fix it I'm not fixing this bullshit

**Comment by wakystuf** [comment]
I'll look into it

**Comment by wakystuf** [comment]
OK, this should now be fixed

**Comment by Arpharnator** [comment]
works yay
