### ISSUE TITLE
dust bonzana and school of geniuses not buildable on certain places despite them having anomalies

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#485]

**Comment by wakystuf** [comment]
Oh, yeah that makes sense. I didn't change anything to do with their build conditions when I updated the buildings. I can look into that; thanks for the heads up!

**Comment by wakystuf** [comment]
Should be fixed. I just built it into the pull request for the UC, since it's the same file

**Comment by Arpharnator** [comment]
note to self, the code given makes it buildable everywhere, including the places without anomalies

**Comment by wakystuf** [comment]
Yeah, that's true. Just don't be dumb and you'll be fine :)

**Comment by Arpharnator** [comment]
works
