### ISSUE TITLE
UC bug with sleeper abduction

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#489]
On systems with a bunch of pops, abducting sleepers while you also having a good chunk of sleepers will cause more than one population to vanish from this system and you only receiving one shadow

**Comment by wakystuf** [comment]
Is this with hacking or invasion? If hacking then I think this is a vanilla bug

**Comment by Arpharnator** [comment]
haxx

**Comment by wakystuf** [comment]
Yeah, that happens sometimes in vanilla, especially if you're hacking the capital

**Comment by captaincobbs** [comment]
We can't fix this.
