### ISSUE TITLE
Add Framework for Mavros Major Faction

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#492]
Add framework to let the Mavros Major Faction mod run smoothly with ESG

**Comment by Arpharnator** [comment]
didn't we already succeed

**Comment by captaincobbs** [comment]
Confirmed it works (No gameplay effect, just technical changes)

**Comment by wakystuf** [comment]
I'm listing this one as "Documented" despite not doing anything, since it sounds like it won't (yet) have any impact
