### ISSUE TITLE
Immigration

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#497]
made it usable

Horatio gets a trait giving +40% migration Score

**Comment by wakystuf** [comment]
(happiness *0.4) * (freee pop slot * 0.05 * ) * (0.75 * nbOfWar/nbOfPlayers)

**Comment by wakystuf** [comment]
Also, do we know what determines how quickly a pop actually migrates, if it's in the migration state?

**Comment by Arpharnator** [comment]
25% of food in vanilla goes to migration, but made it so 50% in esg

**Comment by wakystuf** [comment]
OK. And they only migrate to directly adjacent systems?

**Comment by Arpharnator** [comment]
yea, only adjacent systems

**Comment by wakystuf** [comment]
Actually, it looks like the formula is (happiness *0.4) * (1+ [free pop slots] * 0.05) * (1-0.75 * nbOfWar/nbOfPlayers)
