### ISSUE TITLE
Horatio quest changes

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#498]
eco path chapter 1.2 : the system I put is probably a bit good uhhh, but it doesn't come online before turn 25 because the first quest takes like 10 turns and then you need to get free movement and it's slow as fuck since it's been changed and then it needs to be turned into an outpost and uhhhh yea long time for good system.

Changed eco Chapter 1 :  to 13 more major pops instead of 10.

Changed religious chapter 1 : Made it so that the horatio quest requiring luxuries is 40 and not 50 more cuz it's a bit long

Also something broke the horatio ai empire spawn, and the wierd thing is that it occurs in vanilla as well? so I suppose it's a big wierd error

**Comment by wakystuf** [comment]
So for the first part it sounds like you didn't change the quest, you just made the reward (the system) better:?

**Comment by Arpharnator** [comment]
yep
