### ISSUE TITLE
Autonomous Materials has no Science Cost

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#500]

**Comment by wakystuf** [comment]
Are we sure this is an ESG bug and not related to the DLC? I don't think we modded anything related to that tech

**Comment by captaincobbs** [comment]
Nope I have no idea, Cat claims they didn't touch the tech but this error wasn't showing up until the patch, so I'm not sure.

**Comment by wakystuf** [comment]
@captaincobbs Is this still happening?

**Comment by captaincobbs** [comment]
Yes, completely forgot about this

**Comment by wakystuf** [comment]
Should now be fixed

**Comment by captaincobbs** [comment]
Keeping this open for testing

**Comment by wakystuf** [comment]
Sounds like this issue is back, so reopening

**Comment by wakystuf** [comment]
Likely false alarm; closing now
