### ISSUE TITLE
Make special nodes in somebody's influence sphere not vinable

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#505]

**Comment by wakystuf** [comment]
Can't they vine like, actual systems that are not theirs? I would think that is fine, unless I'm missing something.

**Comment by Arpharnator** [comment]
they can't vine other systems than theirs in cold war, but yet are able to vine special nodes inside someones territorry

**Comment by Arpharnator** [comment]
yep

**Comment by captaincobbs** [comment]
I'm not a fan of this since it cripples the Unfallen mechanics, it's just a slightly annoying feature.
