### ISSUE TITLE
Metafolding affinity can't get Sim Camp anymore due to having custom tech in that spot

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#507]

**Comment by wakystuf** [comment]
This will be irrelevant once we push through the whole MP rework, but for now I'll a quick fix for the Vaulters

**Comment by Arpharnator** [comment]
hmm actually I think it's not on the tech even in the rework

**Comment by wakystuf** [comment]
You mean you aren't seeing it even for non-Vaulters factions?

**Comment by wakystuf** [comment]
OK. So I just need to quickly patch it for the Vaulters

**Comment by wakystuf** [comment]
Should be fixed now in #508

**Comment by wakystuf** [comment]
This one isn't even relevant anymore with the other changes, so I'm closing it
