### ISSUE TITLE
Sophon buffs

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#510]
![image](https://user-images.githubusercontent.com/49691625/117554431-ee349980-b057-11eb-85c7-b6c59f797039.png)
![image](https://user-images.githubusercontent.com/49691625/117554434-f42a7a80-b057-11eb-92e7-e432b2bade57.png)
![image](https://user-images.githubusercontent.com/49691625/117554436-f8569800-b057-11eb-8ef9-c525d1f64b1c.png)
![image](https://user-images.githubusercontent.com/49691625/117554437-fab8f200-b057-11eb-83d3-62d4c56e61a7.png)
![image](https://user-images.githubusercontent.com/49691625/117554477-4e2b4000-b058-11eb-8031-5848848336fc.png)
cost of sophon unique building is now 25 antimatter and 2120 ind (on fast), compared to 50 antimatter and 3120 before.

**Comment by captaincobbs** [comment]
Can you compare what you did to vanilla so Waky can document
