### ISSUE TITLE
More Empire Improvements on tech tree

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#520]
@Arpharnator  didn't create an issue for #518

**Comment by captaincobbs** [comment]
Idea to add onto this, give nakalim some additional empire improvements that activate a temporary effect which provides a LARGE bonus. For instance, you re-activate your ancient vaulters, get 1000 dust on empire for 5 turns.

Frost had a bunch of ideas for this, and might as well take the time to do it.
