### ISSUE TITLE
Reduce ship MP and buff boarding pod defenses

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#521]
Makes it harder to invade without a proper invasion fleet
Helps avoid fucking non-invasion fleets when an empire is low on MP

Assuming others agree, what should the stats be? Below is a proposal, but can do something different:
* Scouts/colonizers/leechers/etc: 30
* Small hulls: 60
* Medium hulls: 150
* Carriers: 300

Then probably ~50% reduction in boarding pod health (or buff to flak or something else instead). 

Probably also should then reduce slightly the inherent MP damage on normal modules

**Comment by wakystuf** [comment]
Guys, guys, this was a separate issue from the MP dropping/ boarding pods bullshit. This was my inspiration:

Arphart — Yesterday at 4:39 AM
Yea but that's not that much especially considering you had pretty fat fleets
Like upgraded hunters 450 mp each
And you took that second quest system pretty late
Like turn 20-25
ChaosWillRise — Yesterday at 4:42 AM
alright
I will check the manpower stuff again
ChaosWillRise — Yesterday at 4:42 AM
thats exactly my problem
I dont think fleets not equipped to invade
should invade that easy
and also they should not waste that much manpower
Arphart — Yesterday at 4:45 AM
Yea that makes sense
We still have to do something about pods yoinking whole fleets

**Comment by Doruk-Coskun** [comment]
New base manpower cap for ships are: 
30 scout colonizer etc
60 smalls
150 medium
450 carriers

Increased craver trait for extra manpower on ships to 10->25%

**Comment by Doruk-Coskun** [comment]
In accordance with this change, boarding pod damage and boarding pod health across the board has been reduced

**Comment by Arpharnator** [comment]
works

**Comment by wakystuf** [comment]
@Doruk-Coskun the pull request that this links to seems to contain a bunch of other stuff, right? Is there a separate issue for those other topics?

**Comment by Doruk-Coskun** [comment]
@wakystuf this issue #548 is supposed to encapsulate the remaining changes but apparently I forgot the write everything I changed in the issue
