### ISSUE TITLE
Passive bonuses on tech tree

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#526]
#518 
@Arpharnator good job coding. Bad job documenting.

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/118113507-b2e2f380-b3e6-11eb-8a0a-687a16975db9.png)
![image](https://user-images.githubusercontent.com/49691625/118113517-b5454d80-b3e6-11eb-94f1-1bca02a0331b.png)
![image](https://user-images.githubusercontent.com/49691625/118113528-b8403e00-b3e6-11eb-91b7-31bd74b2eb83.png)
![image](https://user-images.githubusercontent.com/49691625/118113542-ba0a0180-b3e6-11eb-853a-dc04823d91f7.png)
![image](https://user-images.githubusercontent.com/49691625/118113554-bd04f200-b3e6-11eb-8a66-487708c976a4.png)
![image](https://user-images.githubusercontent.com/49691625/118113569-bf674c00-b3e6-11eb-8d4d-10aa5f844eff.png)
![image](https://user-images.githubusercontent.com/49691625/118113582-c2fad300-b3e6-11eb-98f8-cb68afc21171.png)
![image](https://user-images.githubusercontent.com/49691625/118113592-c4c49680-b3e6-11eb-8ab2-d37f22b14d30.png)
![image](https://user-images.githubusercontent.com/49691625/118113605-c7bf8700-b3e6-11eb-9494-92613a2ea18e.png)
![image](https://user-images.githubusercontent.com/49691625/118113611-c9894a80-b3e6-11eb-9c1f-e55876552ac8.png)
![image](https://user-images.githubusercontent.com/49691625/118113620-cc843b00-b3e6-11eb-885d-f3e9c6fe6fb2.png)
![image](https://user-images.githubusercontent.com/49691625/118113630-cf7f2b80-b3e6-11eb-9808-9c8bd6e559e7.png)

**Comment by Arpharnator** [comment]
I am considering nerfing them and deleting the +1 approval per pop

**Comment by wakystuf** [comment]
For approval, you could do +2 per planet instead of +1 per pop; that would be much less likely to get out of control

**Comment by captaincobbs** [comment]
I'm going to move these from the tech stage and make them more interesting. They'll probably end up on lackluster techs with only 1-2 rewards.
