### ISSUE TITLE
Let Lumeris toggle supply ships

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#531]
Replace the "+100% Food from Supply Ships" with "Start sending supplies", once supplies are enabled, +100% food from supply ships is available like normal.

**Comment by NingaublesEyes** [comment]
Is this a way to get faster colonization or are you trying to find a way to make sending supply ships toggled so that you can avoid losing food to an outpost you plan to sell?

**Comment by captaincobbs** [comment]
Yes, but it's not possible sadly.
