### ISSUE TITLE
Vaulters version of Bunkers not Buffed

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#537]
@Arpharnator

**Comment by Arpharnator** [comment]
oiiiiiiiiiii suck it boyyy

**Comment by captaincobbs** [comment]
This seems awfully like an arphar problem

**Comment by Arpharnator** [comment]
I mean I haven't seen it because I don't play vaulters so it doesn't exist

**Comment by Arpharnator** [comment]
we have a problem cuz the building is nowhere to be found in the code

**Comment by captaincobbs** [comment]
StarSystemImprovementDefense1Vaulters

**Comment by Arpharnator** [comment]
work
