### ISSUE TITLE
make minors harder to take, both by force and influence

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#539]

**Comment by wakystuf** [comment]
If we do this, then we should consider adjusting all of the various quests that are dependent upon achieving X level of relations with a minor (RB, Sophons, Vodo, and probably others)

**Comment by Arpharnator** [comment]
minors give more money, are harder to please, their military is supposed to be better but I have yet to make it work, check the plugins pls

**Comment by Arpharnator** [comment]
also they are able to grow more pops and get more buildings built

**Comment by wakystuf** [comment]
This seems like a good idea, but a few questions, Arphar:
1) I assume you cranked up the costs of "praise" and reduced the gain from the "Improve Relations" hacking outcome? By how much?
2) As part of this, we will need to adjust a bunch of main faction quests; just something to keep in mind. That questline for Vody is already dead/irrelevant, but I think some of the others (UC, RB) might actually care.
3) I assume minors also give more [other stuff] too, like MP, essence, science, etc?
