### ISSUE TITLE
Law Rework

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#541]

**Comment by wakystuf** [comment]
[Law Rework.xlsx](https://github.com/captaincobbs/ESG-Mod/files/6502983/Law.Rework.xlsx)

**Comment by captaincobbs** [comment]
Todo - Hissho specific replacements to some laws (Make a separate issue for that, and link it here)

**Comment by wakystuf** [comment]
#553

**Comment by wakystuf** [comment]
Note to self: Mil T5 changed to 1% per 500 MP, and with only 30% cap in republic
