### ISSUE TITLE
Add pirate ships to ind cost formula

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#543]

**Comment by wakystuf** [comment]
I added a pull request to the market-side code in #542 that should act as as failsafe to prevent crashes stemming from this problem. However, the proper solution is to add the pirate hulls to your prior code

**Comment by wakystuf** [comment]
@captaincobbs This is done, right?

**Comment by captaincobbs** [comment]
Not yet, I'll do it tonight, expect a pull request tomorrow

**Comment by wakystuf** [comment]
This now works except for the pirates that initially spawn on the market, which have instead simply been abolished.

**Comment by captaincobbs** [comment]
Confirmed
