### ISSUE TITLE
Deeds Rework

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#549]
Updated Deed module costs and effects. Reduced Deed system improvement strategic costs and updated the effects.

Fixed Weaponized System system improvement troop health and damage boost effect applied wrongly in the code.

**Comment by wakystuf** [comment]
@Doruk-Coskun For the deeds part, it'd be helpful to know the details, so that I can put them on the wiki without having to dig through all the code

**Comment by Doruk-Coskun** [comment]
@wakystuf I know, I will

**Comment by Doruk-Coskun** [comment]
Deployable Ramparts Deed reward siege module effect is reworked to be the same as sieging module and tier 2 crew module. Effects of both of these modules are combined.

Annihilator Beam Deed reward weapon module is nerfed so that it doesn't have any base critic chance anymore. It was a common occurrence that this module crited an enemy carrier and one-shotted it.

System improvement rewards of economy quadrant deed rewards are reworked to have lower strategic and industry costs to match their effects.

**Comment by wakystuf** [comment]
OK, thanks. I went through the code to find the details of the buildings, so this one is now all set
