### ISSUE TITLE
Make Propaganda Usable by Other Governments

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#555]
Now that laws are reworked to matter more, provides players more control over political support

**Comment by captaincobbs** [comment]
Reopened to remind me to do this.
Unlocks Propaganda for parties in the senate on HyperPACs
Unlocks Propaganda for all parties on SLC

**Comment by ThanosDeGraf** [comment]
With #598, every faction should now have access to researchable propaganda.
 
 When you research HyperPACs, you'll get access to propaganda options depending on which ideologies are represented in your senate. Researching SLC with grant access to every propaganda
