### ISSUE TITLE
Balance Hacking

### ISSUE THREAD

**Issue by Doruk-Coskun** [captaincobbs/ESG-Mod#567]

**Comment by wakystuf** [comment]
I thought some about this; I agree with @Doruk-Coskun that we should fix this. My suggestions (some of these ideas are from Cobbs too but he may not agree with all of these):
1) Make each defensive hacking program block a specific capital hack. For example (we can discuss which goes with which more):
1a) Firewall: Blocks "Spawn pirates"
1b) Lockdown: Blocks "Government anarchy"
1c) Track: Blocks "Shut down ships"
1d) Encrypt: Blocks "Steal tech"
2) Make Track less expensive, like 15-20 BW
3) Make Piggyback not worthless/counterproductive. Need ideas for how to accomplish that. I'll think about it more later when I'm less tired. One idea: provide visibility into the affected system while the program is running (like a sleeper, but without any of the stealing and other economic consequences)

Thoughts?

**Comment by captaincobbs** [comment]
What makes piggyback useless? Is the effect not big enough, or will no amount of # tweaking make it good.

**Comment by wakystuf** [comment]
Yeah Piggyback is like the Dust Bonanza of hacking; it costs more bandwidth than it saves. We could probably fix it actually by only tweaking the numbers if we want. I can calculate that later today

**Comment by wakystuf** [comment]
@captaincobbs Updated above based on doing some math for Piggyback. I think you're right that it should be fine, especially if we also buff the numbers on overload (since fundamentally the point of piggyback is to make Overload and Divert less expensive to layer on top of your accelerators).

**Comment by Doruk-Coskun** [comment]
increase fleet hack duration to 2, reduce the pirate hack effects

**Comment by Eighth-of-Third** [comment]
I'm not sure about blocking hacking outcomes on the home system. With the amount of bandwidth that's available in ESG, I think you'd be able to slap all 5 defensive programs on your home system and never have to pay attention to the hacking minigame ever again. The proposed buffs to useless hacking programs are good ideas.

**Comment by wakystuf** [comment]
@Eighth-of-Third  yeah it's a fair concern, but I think workable if we tweak the numbers properly. Here's my math:

Vanilla cost of installing all 5 defensive programs: 15 + 20 + 20 + 30 + 30 = 115
Vanilla BW: 50 base + 5 per program unlocked (of which there are 9) = 95
ESG BW: 3 per SD2, so roughly 30, and 3 more per SD3, so maybe another 15 and 4 per SD4, so maybe 8-12; let's say 10. That's an additional 55 from ESG. If someone is very successful with lux, then they could get modestly more (maybe another 20-30), but I think that's not a crazy reward for a rather large accomplishment.
Total BW in ESG = 95 (Vanilla) + 55 (ESG) = 150

Then, if Overload is buffed to ~30%, the 115 becomes exactly 150, which is the entire Empire's stock of BW. So they literally CAN do it, but only at the risk of entirely surrendering their cyber defenses elsewhere (so they'll never be able to draft ever again in any context, their heroes will be at great risk of wounding, enemies will potentially have sleepers in key production systems, etc). This also implies 0 offensive hacking programs, and 0 backdoors, which is also a fairly significant cost.

If that scenario still bothers you, then we could further buff Overload to like ~40%, at which point it becomes almost entirely impossible to fully defend your capital, even if you are willing to entirely surrender everyplace else.

**Comment by wakystuf** [comment]
@Eighth-of-Third One other point to consider as a thought experiment: As the UC, I personally would greatly prefer a world where I can run around hacking anything I want, as long as I don't touch a capital. Capital hacking as the UC may be the most flashy and sexy strategy, but I think it is generally overstated in importance unless they are going for Supremacy. Gradually grinding away with all 5 hacking operations to gobble up huge numbers of planets (and minors) is a reliable way to build a rather potent FIDS engine through Xenoindustrial, Public-Private Partnerships, the huge Gas % buff, Predictive Logistics and Blue Sky.

**Comment by Eighth-of-Third** [comment]
That's some convincing math. I'm fine with it, then.

**Comment by wakystuf** [comment]
Excellent
