### ISSUE TITLE
Unfallen Vineship hull cost reduced to 50

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#572]
Vine module cost raised to 100

Anybody know which section of the changelog this should go under?

**Comment by captaincobbs** [comment]
It's part of a bug caused by 1.4 so I don't think it's necessary to note it down.

**Comment by wakystuf** [comment]
OK, well for now I'll list as an ESG bug then; that's contrary to what I was told yesterday. I don't play Unfallen so I don't really know/care, but for now will just list as open for us to fix

**Comment by captaincobbs** [comment]
Fixed (supposedly)

**Comment by wakystuf** [comment]
Fixed
