### ISSUE TITLE
Increase Overcol penalties to -15 approval

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#585]
Doesn't apply to UC
Doesn't apply/matter to Hissho

**Comment by Arpharnator** [comment]
why not uc

**Comment by wakystuf** [comment]
UC already has -20

**Comment by Arpharnator** [comment]
so wat

**Comment by wakystuf** [comment]
So -20 is already good. More would be brutal (particularly for their strats output, which I don't want to buff, but shouldn't get nerfed either) and less would be an unneeded buff.
