### ISSUE TITLE
More Custom Faction Tweaks

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#608]
Fixed Ghost Crew being considered a leveled trait
Changed Ghost Crew cost to 10 (was 5)
Changed Ghosts cost to 15 (was 25)
Added Icons to ALL trait types

**Comment by wakystuf** [comment]
I haven't generally been documenting all of the stuff with custom faction points and so forth, but I did list the icons point as a GUI improvement

**Comment by captaincobbs** [comment]
I don't think the specific changes really matter (unlike balance), so that's fine.
