### ISSUE TITLE
Minor Vaulter Smoothing

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#609]
1) Start them with maximum curiosity detection power so that they can see where strategic curiosities will be in the future, but not probe them.

(Edited by Cobbs after deliberation with everyone)

**Comment by Mermixer** [comment]
> Make them able to see the strat resource deposit curiosities earlier (but not explore them until they have unlocked the appropriate probes, as normal).

why not just give them the exploration aswell
knowing which type is on the specific planet is so valuable, and sometimes youre gonne have a subterran that ends up being something else (luxury, loot, etc)
i mean we are already boning them with the reduced nr of systems, and then we can also remove point 1 bc it feels rather irrelevant

**Comment by Arpharnator** [comment]
I don't think 3 is a good idea waki

**Comment by wakystuf** [comment]
@Mermixer If we give them the exploration, then won't they gobble up 100% of those curiosities? I don't think that is the goal, especially since it would kind of screw other science/exploration heavy factions.

@Arpharnator Why not?

**Comment by Arpharnator** [comment]
@wakystuf because it is not very vanilla flavorful

**Comment by wakystuf** [comment]
Hmm...yeah, that could work. The UC will cry, but I suppose I don't really care. So then maybe we just let them explore all strats from T1, but don't buff their Evacuate action. I would probably still rework their Government, in that case, since the exploration buff makes me even less sympathetic to them expanding a bunch.

I'm not sure which was which but yeah apparently Cobbs got a lot of complaints from a variety of people. It sounds like the main issue is picking a system to colonize before you know what resources (especially T2-3) are there.

**Comment by ThanosDeGraf** [comment]
Made a branch to help test this feature out. Might need some help, since I don't have the Vaulters DLC myself.

**Comment by captaincobbs** [comment]
I'm finishing up the hard parts of this, Tuerk did a lot of the work but there were some things in the background that need to change

**Comment by wakystuf** [comment]
Just documenting for later (no worrying about this now, Cobbs!)
* I'm told that this is bugged where the Vaulters can't actually see the strats
* I'm also getting negative feedback from non-Vaulter players about the requirement of T3 probes to find antimatter and adamantian (and similarly for the higher tier strats)

**Comment by wakystuf** [comment]
Update: I've removed this and simply given the Vaulters guaranteed titanium at the beginning (if the randomly selected fertile planet doesn't already have titanium on it, then this will spawn a Quest curiosity that creates a 0-value titanium deposit)
