### ISSUE TITLE
Documentation for immigrattion changes

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#620]
+5 Migration score per sd level
reduced migration gained from free slotss from 0.05 to 0.02

**Comment by Arpharnator** [comment]
what a cunt this cobbs guy is btw

**Comment by wakystuf** [comment]
Thanks for listing. Note that the Needs Documentation tag I added is just how I track what I need to put on the changelog

**Comment by Arpharnator** [comment]
Waky, the changes you made to the minors migration score are pointless because the only thing that matter is >50 and <50

**Comment by wakystuf** [comment]
Oh, really? How does that work?
