### ISSUE TITLE
Improve civ ships by +1 move (horatio only bc merm)

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#621]

**Comment by wakystuf** [comment]
Maybe make this a I/II type trait and give Lumeris the level II (+2 civilian ship move)? Thematically the merchant faction should probably have very good civilian ships and I don't think the Lumeris have another solution on this issue, do they?

I think everybody else is already covered:
* Vodyani and UC don't care
* Cravers, Hissho and RB need no help
* Sophon ships are already fast
* Unfallen ships already move faster along vines
* Vaulters already teleport

UE arguably should get something too, but Merm doesn't want to and I don't care enough to disagree

**Comment by wakystuf** [comment]
I this this one is done, right, @Arpharnator ? If so then I'll document on the changelog

**Comment by Arpharnator** [comment]
no it hasn't been done, and no plans on doing it
