### ISSUE TITLE
Rework Trade Luxes

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#627]
1) Superspuds cost reduction is mostly cringe (not great early on but scales to become kind of OP if you stack up a bunch). Replace with something else. Maybe -20% ship repair/retrofit cost?
2) Gossamer is just...terrible. Replace with something else. Maybe -X% system upkeep?
3) Now that trade yields are lower, Drift Buds can be reverted to vanilla, but then also need a replacement for the ESG buyout effect. Maybe -X% market taxes?

**Comment by Mermixer** [comment]
tax reduction sounds very interesting
i like it
finally tax evasion in es2

**Comment by Arpharnator** [comment]
how do you apply tax evasion on an empire level without making sure its broken and also what of the poor guy building trading wonder

**Comment by wakystuf** [comment]
I think the Lumeris have a trait that does something like that, don't they?

Presumably this reduces the fees of the guy building the TCB, if it works properly. Knowing that this exists will reduce the value of that thing, so it's up to them if they want to burn 120 strats on it anyway

**Comment by Arpharnator** [comment]
I'm not sure there was an agreement on that wonder staying garbage, because then I'm gonna go nerf the Endless park rq

**Comment by wakystuf** [comment]
Well first of all you could just lower the strat cost for TCB and that would help a lot. Maybe like 30/30 but also 10/10 of green/purple?

Second, the Endless park is very, very good so nerfing it a bit might be fine. Mostly the long-term science gain of +20% empire-wide is excellent. I wouldn't necessarily nerf it, but I think that's the part to nerf if you're going to

**Comment by Arpharnator** [comment]
I was planning on reducing it to 2% obviously

**Comment by wakystuf** [comment]
OK, I fiddled around with this and it looks like retrofit is only defined at the empire level, so I don't think that will work for superspuds. Here are a few other ideas:
1) +1 lux deposit value (since trade generates lux it's still trade-related)
2) Simply +25% trade value (I don't like this option since it is useless early-game when trade doesn't even exist)
3) +X dust per defensive MP (probably 0.02-0.05)
4) +1 pop slot per lux deposit

Or we could go less trade related:
5) +2 and 25% hero XP
6) +1 strat deposit value

Thoughts?

**Comment by wakystuf** [comment]
Update: gossamer to 50%, since superspuds are 25% and drift buds are 100%

**Comment by wakystuf** [comment]
> I'm not sure there was an agreement on that wonder staying garbage, because then I'm gonna go nerf the Endless park rq

@Arpharnator was ahead of his time on this one. Where others saw madness, he saw genius...
