### ISSUE TITLE
Siege Module Changes

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#629]
1. Make Siege Modules be associated with the energy-associated strategic resource rather than the kinetic-associated strategic resource.
Titanium -> Hyperium
Adamantian -> Antimatter
Oricalchix -> Quadrinix

2. Move Siege modules to the tech tree (remove from curios)

Do in either 1.4.1 or 1.5

**Comment by wakystuf** [comment]
First part of this is done, but not the second part
