### ISSUE TITLE
Enable retreat and retrofit on pirate systems when in alliance with them

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#636]
Due to complaining from Merm

**Comment by Arpharnator** [comment]
nononononnoonnonononoon

**Comment by wakystuf** [comment]
Why not? I don't especially care, but it seemed fine to me

**Comment by wakystuf** [comment]
Pull request created, but Arphar let me know if you hate it and we don't have to merge

**Comment by captaincobbs** [comment]
Can you explain a bit, what does this change and why is it needed

**Comment by wakystuf** [comment]
Merm was complaining that even if he was best friends with the pirates (able to use their systems for portals, etc) that he still could not retrofit his ships there, and wasn't allowed to retreat to them. I thought he made a good point, so I fixed it.

It sounds like @Arpharnator doesn't agree though, so that's why I requested his review of the code to hear him out before we just start changing stuff.

**Comment by captaincobbs** [comment]
The pirates can't even retrofit in their own territory, I don't think players should be able to. However, I think retreating to them is a good change.

**Comment by wakystuf** [comment]
Maybe make pirates able to? Idk. I don't super care tbh. Merm asked for a nice present and I gave him one

**Comment by captaincobbs** [comment]
They can't because their ship designs are static, they don't have the ability to make new designs

**Comment by wakystuf** [comment]
Oh, well that's a separate issue then. Seems fine for them to provide a friendly port for people to retrofit in that case (but again...I mostly just don't care)
