### ISSUE TITLE
Vaulter quest bugged

### ISSUE THREAD

**Issue by Mermixer** [captaincobbs/ESG-Mod#640]
Final Chapter 'Reunification' of vaulters doesnt work
it requires you to send opbot lvl 10 to the system, so since you get the hero on lvl 9 you need to lvl him a bit
however you can just immediatly send it to the system to complete it immideatly

**Comment by wakystuf** [comment]
@captaincobbs  I'm not planning to document this one; let me know if you disagree and I can list it
