### ISSUE TITLE
Fix all factions having hissho-style mining probes that grant per-pop FIDS % to homeworld

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#67]

**Comment by wakystuf** [comment]
What exactly was this issue? Was there a bug whereby other factions could gain FIDS from mining probes?

**Comment by captaincobbs** [comment]
This was a bug caused by the mod, you can ignore it.

**Comment by wakystuf** [comment]
Fair enough; that's an easy one then.

**Comment by Arpharnator** [comment]
It's so sad to see it go

**Comment by Tat011** [comment]
this should be a feature imo (albeit not everyone should have it and it should be weaker than hissho for those who do)
