### ISSUE TITLE
Make Unfallen fixed-turn colonization 1 turn

### ISSUE THREAD

**Issue by wakystuf** [captaincobbs/ESG-Mod#688]

**Comment by captaincobbs** [comment]
Can I ask why this was changed? Not against it, just curious

**Comment by wakystuf** [comment]
Yeah I'd gotten a lot of complaints from people about this. Their points were:
1) It just takes way longer for a developed system to colonize a new planet than it does for other factions
2) It creates cancer micro, similar to how SD3-4 used to
3) Unfallen could use a boost. This almost certainly doesn't totally solve their issues, but it's at least a step in the right direction
