### ISSUE TITLE
Add Sublustris's quest fixes

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#69]

**Comment by wakystuf** [comment]
Is there any listing of what these included?

**Comment by captaincobbs** [comment]
https://www.games2gether.com/amplitude-studios/endless-space-2/forums/114-bug-reports/threads/36220-the-ugly-plague-horatio-population-quest-completion-trigger-bug-and-fix?page=1#post-297069
https://www.games2gether.com/amplitude-studios/endless-space-2/forums/114-bug-reports/threads/35979-the-reborn-nakalim-solo-quest-completion-trigger-bug-and-fix?page=1#post-295745

**Comment by wakystuf** [comment]
OK, thanks. I'll take a look at these

**Comment by wakystuf** [comment]
Those links were pretty clear, so I think this one is all set
