### ISSUE TITLE
Vodyani Manpower Module and Meditation Module incompatibility

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#7]

**Comment by wakystuf** [comment]
What exactly was this bug? I hadn't seen it previously.

**Comment by captaincobbs** [comment]
It wasn't a bug, we specifically made manpower modules and vodyani meditation modules incompatible, because it would let the vodyani generate near infinite amounts of manpower, making them unbeatable.

**Comment by wakystuf** [comment]
Interesting. I play them a lot and I never thought of that (though I suppose mostly because I just defend in space anyway).

I'll move that out of the bugfix section and clarify.
