### ISSUE TITLE
Change T2 ecology law

### ISSUE THREAD

**Issue by Arpharnator** [captaincobbs/ESG-Mod#701]
![image](https://user-images.githubusercontent.com/49691625/128326718-7466a1af-762f-4ffd-82ae-65e4205b214e.png)
rn this is the second eco law, unlocked at the first election, and is omega useless early game and more than not for most factions.

Instead of that, I believe that this law should instead unlock ALL terraformation and give a 50% discount, but cost 4 influence per pop upkeep.
This allows factions to pick up ecologist later and have something useful, albeit at a certain price and to give ratio an influence sink that isn't minor and a second early game law if he can afford it.

**Comment by Arpharnator** [comment]
The republic version will see its cost reduced to 3 influence per pop instead of yielding better results, bc RB

**Comment by Arpharnator** [comment]
Vodo version stays unchanged, including upkeep cost

**Comment by wakystuf** [comment]
You make a fair point about the early-game uselessness of the law; we should probably fix that.

Is there something less drastic we could do to make the law more useful, like a) simultaneously lower the thresholds for pop collections, b) buff the numbers, or something else related, like % buff to the pop effects?

**Comment by Arpharnator** [comment]
I think that's how the law should be, it opens up interesting possiblities fairly early on by colonising poopoo planets but already managing to make them better

Pop collection etc is not for this place I believe, I prefer to try to synergize the main law and terraformation

**Comment by wakystuf** [comment]
I'm not sure we can code the terraforming thing the way you're describing, but I think your criticism of the current situation is fair. Is there something else we could do to solve the issue instead that's less drastic?

**Comment by Arpharnator** [comment]
it's not about being drastic, it's to make an interesting change. I believe that it's the correct thing to do to make a better game?
I've tried a bit but the best I've managed to do so far was to make me unable to terraform on the planet menu (options greyed out)

**Comment by wakystuf** [comment]
What if we instead did the following?
1) Did the terraform cost reduction as you said, but put that on the T0 main law so that the T0 law is actually useful later on in the game?
2) Provide some other thematic effect to the T2 law that is more generally useful (IE, including to factions that have ecologists at the 2nd party) but doesn't replicate the effects of a T4 tech. For example, food to IDS, but maybe something else?

**Comment by Arpharnator** [comment]
I think giving a 25% FIDSI increase on fertile planets and 50% terraform cost reduction could work. I don't wanna give too much to main law cuz I don't wanna end up with pacifist which is a mishmash of everything. Might want to switch the place of the law to appear after turn 10, meaning instead of the 3rd of 4th law, cuz no doubt it's useless in turns 1-10 unless you start on fertile

**Comment by Arpharnator** [comment]
I want to give incentives to go terraform early on and be still rewarding in the long term (as we know that despite spending ind to get to fertile, desert takes it all)

**Comment by wakystuf** [comment]
Interesting. Hmm...I think it's better to simply provide an effect which most factions would like from the beginning, right? +X% FIDSI on Fertile is thematically appropriate , but what if we made it simply non-Sterile instead? That way Horatio still wants it on their Med planet?

Also, do you mean +25% base planet FIDSI, or something else?

**Comment by wakystuf** [comment]
Also I'd probably put the -50% terraform cost on the T0 law just because it's like utterly worthless lategame otherwise, right? I don't care that much, so not worth fighting about it, but seems like that law could use some kind of a lategame buff. If the Horatio player says no buff needed, however, then I'll take your word for it.
